import {api} from './api.js';
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={new:'Neu',reviewing:'In Prüfung',quoted:'Angebot erstellt',production:'In Umsetzung',completed:'Abgeschlossen',cancelled:'Abgesagt'};
const date=v=>new Date(Number(v)).toLocaleString('de-DE');
export const requestStatus=value=>states[value]||states.new;
export function securityPanel(user,emailReady){if(user.admin)return `<section class="panel account-security"><h2>Interner Admin-Zugang</h2><p>Du bist über den passwortgeschützten Zugang unter /admin angemeldet.</p></section>`;return `<section class="panel account-security"><h2>Zugang & Sicherheit</h2><p>${h(user.email)} · ${user.emailVerified?'E-Mail bestätigt':'E-Mail noch nicht bestätigt'}</p>${emailReady&&!user.emailVerified?'<button class="button" data-action="verify-email">Bestätigungslink senden</button>':''}${emailReady?'<button class="text-button" data-action="forgot-password">Passwort zurücksetzen</button>':'<p class="under-note">E-Mail-Bestätigung und Passwort-Wiederherstellung folgen, sobald der E-Mail-Versand eingerichtet ist.</p>'}</section>`;}
export async function recoveryDialog({kind='forgot',token='',email='',onDone=()=>{}}={}){
 const dialog=document.querySelector('#auth-dialog');
 const title=kind==='reset'?'Neues Passwort festlegen.':kind==='verify'?'E-Mail bestätigen.':'Passwort vergessen?';
 dialog.innerHTML=`<button class="dialog-close" aria-label="Schließen">×</button><h2>${title}</h2><p>${kind==='verify'?'Bestätige mit einem Klick, dass diese E-Mail-Adresse dir gehört.':kind==='reset'?'Wähle ein neues Passwort mit mindestens 12 Zeichen.':'Wir schicken dir einen Link zum Zurücksetzen.'}</p><form>${kind==='forgot'?`<label>E-Mail<input name="email" type="email" required autocomplete="email" value="${h(email)}"></label>`:kind==='reset'?'<label>Neues Passwort<input name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><label>Passwort wiederholen<input name="confirmation" type="password" required minlength="12" autocomplete="new-password"></label>':''}<p class="error" hidden role="alert"></p><button class="button primary">${kind==='forgot'?'Link anfordern':kind==='reset'?'Passwort speichern':'E-Mail bestätigen'} →</button></form>`;
 dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclose=null;
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const error=dialog.querySelector('.error');error.hidden=true;try{const d=new FormData(e.target);if(kind==='reset'&&d.get('password')!==d.get('confirmation'))throw Error('Die Passwörter stimmen nicht überein.');const response=await api('/auth/'+kind,{method:'POST',body:{token,email:d.get('email'),password:d.get('password')}});dialog.innerHTML=`<h2>${kind==='verify'?'E-Mail bestätigt.':kind==='reset'?'Passwort gespeichert.':'Schau in dein Postfach.'}</h2><p>${h(response.message||(kind==='reset'?'Du kannst dich jetzt mit deinem neuen Passwort anmelden.':'Deine E-Mail-Adresse ist bestätigt.'))}</p><button class="button primary" data-done>Weiter</button>`;dialog.querySelector('[data-done]').onclick=()=>{dialog.close();onDone(kind);};}catch(e){error.textContent=e.message;error.hidden=false;b.disabled=false;}};
 if(!dialog.open)dialog.showModal();
}
export async function renderInbox(container,{id='',notice}){
 container.innerHTML='<p role="status">Anfragen werden geladen …</p>';
 try{
  const result=await api('/operator/requests'+(id?'/'+encodeURIComponent(id):''));
  if(!container.isConnected)return;
  if(!id){container.innerHTML=`<nav class="campaign-mode"><a href="/konto/?tab=sales-inquiries" data-view="sales-inquiries">Interessenten</a><a href="/konto/?tab=inbox" aria-current="page">Kampagnenanfragen</a><a href="/konto/?tab=sales-links" data-view="sales-links">Verkaufsseiten</a></nav><div class="page-heading"><div><h1>Eingegangene Anfragen.</h1><p>Die letzten 100 Anfragen · Nur für das Kontaktstoff-Team.</p></div></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Eingang</th><th>Unternehmen</th><th>Kampagne</th><th>Auflage</th><th>Status</th><th></th></tr></thead><tbody>${result.requests.map(r=>`<tr><td>${h(date(r.createdAt))}</td><td>${h(r.company)}</td><td>${h(r.campaign)}</td><td>${h(r.quantity)}</td><td>${h(requestStatus(r.status))}</td><td><button class="text-button" data-open-request="${h(r.id)}">Anfrage öffnen →</button></td></tr>`).join('')}</tbody></table></div>${!result.requests.length?'<div class="empty"><h2>Noch keine Anfragen.</h2><p>Neue Kampagnenanfragen erscheinen automatisch hier.</p></div>':''}</section>`;container.querySelectorAll('[data-open-request]').forEach(b=>b.onclick=()=>renderInbox(container,{id:b.dataset.openRequest,notice}));return;}
  const r=result;container.innerHTML=`<div class="page-heading"><div><button class="text-button" data-back>← Alle Anfragen</button><h1>${h(r.project.name)}</h1><p>${h(r.profile.company)} · ${h(date(r.createdAt))}</p></div><button class="button" data-download>Design & Kontakte herunterladen ↓</button></div><div class="analysis-grid"><section class="panel"><h2>Kampagnenwunsch</h2>${r.submission?`<div class="success"><strong>Vom Kunden geprüft und eingereicht.</strong><p>${h(date(r.submission.checkedAt))} · Entwurfsstand ${h(r.revision)}. Angebot und finale Druckfreigabe noch abstimmen.</p></div>`:''}<dl class="request-details">${[['Ansprechpartner',r.profile.name],['E-Mail',r.email],['Format',r.meta.formatRequest],['Auflage',r.meta.quantity],['Gestaltung',r.meta.designService?'Kontaktstoff gestaltet':'Eigenes Design'],['Kontakte',r.meta.leadSource==='research'?'Lead-Recherche':r.project.recipients.length+' hochgeladen'],['Zielgruppe',r.meta.audience],['Region',r.meta.region],['Unternehmensgröße',r.meta.companySize],['Funktion',r.meta.roles],['Ausschlüsse',r.meta.exclusions],['Ziel-Link',r.meta.targetURL],['Wunschtermin',r.meta.launchDate],['Notiz des Kunden',r.meta.notes]].map(([k,v])=>`<dt>${k}</dt><dd>${h(v||'—')}</dd>`).join('')}</dl><p class="under-note">Gespeicherter Stand beim Absenden. Spätere Änderungen am Entwurf verändern diese Anfrage nicht.</p></section><form class="panel" id="workflow-form"><h2>Bearbeitung</h2><label>Status<select name="status">${Object.entries(states).map(([k,v])=>`<option value="${k}" ${r.status===k?'selected':''}>${v}</option>`).join('')}</select></label><p class="field-help">Diesen Status sieht auch der Kunde.</p><label>Interne Notiz<textarea name="note" rows="6" maxlength="3000">${h(r.note)}</textarea></label><p class="field-help">Nur für euer Team sichtbar.</p><p class="error" hidden role="alert"></p><button class="button primary">Änderungen speichern</button><p class="under-note">Ein Statuswechsel löst keinen Druck, Versand oder E-Mail-Versand aus.</p></form></div>`;
  container.querySelector('[data-back]').onclick=()=>renderInbox(container,{notice});
  container.querySelector('[data-download]').onclick=()=>{const blob=new Blob([JSON.stringify(r.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kontaktstoff-anfrage-'+r.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  container.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('/operator/requests/'+r.id,{method:'PUT',body:{...Object.fromEntries(new FormData(e.target)),workflowRevision:r.workflowRevision}});notice('Anfragestatus gespeichert.');await renderInbox(container,{id,notice});}catch(err){const error=container.querySelector('.error');error.textContent=err.message;error.hidden=false;b.disabled=false;}};
 }catch(e){container.innerHTML=`<section class="panel"><h1>Anfragen</h1><p class="error">${h(e.message)}</p></section>`;}
}
