import {toSelfmailer} from '../../studio/src/selfmailer.js';
import {isSelfmailer,sideLabel,formatCaption} from '../../studio/src/formats.js';
import {api} from './api.js';
import {BUILD_STEPS,hasDesign,campaignReadiness} from './builder-model.js';
import {BRAND_TEMPLATES,createBrandTemplate,PREVIEW_PERSON,brandValue,applyBrandText,recolorBrand} from '../../studio/src/brand-templates.js';
import {FORMATS,KEYS,sideNames,validURL,csvString} from '../../studio/src/core.js';
import {renderCanvas,imageFrom} from '../../studio/src/render.js';
import {Mailing3D} from '../../studio/src/three-d.js';
import {openCSVImport} from '../../studio/src/csv-dialog.js';
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeBuilderEvents;
const input=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${h(value)}" ${extra}></label>`;
export function mountBuilder(root,{record,user,save,submit,saveOnline,notice,navigate,confirm}){
 let c=structuredClone(record),step=Math.max(0,Math.min(3,Math.floor(Number(new URLSearchParams(location.search).get('step')??c.meta.builder?.step??0)||0))),side='front',mode='2d',person=0,paintId=0,pending=Promise.resolve(),failed=null,busy=false,audiences=[],designs=[],category='all';
 let viewer=null;let saveTimer,dirty=false;activeBuilderEvents?.abort();const events=activeBuilderEvents=new AbortController();window.addEventListener('beforeunload',e=>{if(root.isConnected&&dirty){e.preventDefault();e.returnValue='';}},{signal:events.signal});
 c.meta.builder={version:1,step};
 const $=s=>root.querySelector(s),alive=()=>root.isConnected;
 function error(e){failed=e;const el=$('#build-error');if(el){el.textContent=e.message;el.hidden=false;}notice(e.message);}
 function persist(){dirty=true;pending=pending.catch(()=>{}).then(async()=>{const snapshot=structuredClone(c);const signature=JSON.stringify([snapshot.project,snapshot.meta]);snapshot.project.updatedAt=Date.now();const result=await save(snapshot);if(signature===JSON.stringify([c.project,c.meta]))dirty=false;c.id=result.id;c.project.id=result.project.id;c.revision=result.revision;c.local=result.local;c.meta.status=result.meta.status;failed=null;if($('#build-saved'))$('#build-saved').textContent=dirty?'Wird gespeichert …':c.local?'In diesem Browser gespeichert':'Im Konto gespeichert';});return pending;}
 async function flush(){clearTimeout(saveTimer);capture();await persist();if(failed)throw failed;}
 function capture(){if(!c.meta.designService)c.meta.formatRequest=c.project.format;if(c.meta.leadSource==='upload'&&c.project.recipients.length)c.meta.quantity=c.project.recipients.length;const f=$('#build-form');if(!f)return;const d=new FormData(f);for(const key of ['audience','region','targetURL','launchDate','notes','goal','leadSource'])if(d.has(key))c.meta[key]=String(d.get(key)).trim();if(d.has('quantity'))c.meta.quantity=Math.max(1,Math.min(100000,Number(d.get('quantity'))||1));if(d.has('campaignName'))c.project.name=String(d.get('campaignName')).trim()||'Meine Kampagne';for(const el of f.querySelectorAll('[data-brand]'))applyBrandText(c.project,el.dataset.brand,el.value);for(const el of f.querySelectorAll('[data-text-id]')){const field=c.project.sides[el.dataset.side].fields.find(f=>f.id===el.dataset.textId);if(field)field.text=el.value;}if(d.has('brandColor'))recolorBrand(c.project,String(d.get('brandColor')));}
 function studio(view='design'){return '/studio/?'+new URLSearchParams({...(c.local?{local:c.id,workspace:'1'}:{cloud:c.id}),view,build:c.id});}
 function preview(){const f=FORMATS.find(f=>f.id===c.project.format);return `<section class="build-preview"><div class="build-preview-tools"><div class="build-segment">${sideNames(c.project).map(s=>`<button type="button" data-side="${s}" aria-pressed="${side===s}">${mode==='3d'&&isSelfmailer(c.project)?(s==='front'?'Titelseite':'Adressseite'):sideLabel(c.project,s)}</button>`).join('')}</div><div class="build-segment"><button type="button" data-mode="2d" aria-pressed="${mode==='2d'}">${isSelfmailer(c.project)?'Druckbogen · 2D':'2D'}</button><button type="button" data-mode="3d" aria-pressed="${mode==='3d'}" ${sideNames(c.project).length===1?'disabled':''}>${isSelfmailer(c.project)?'Falz · 3D':'3D'}</button></div></div>${mode==='3d'?`<div class="build-stage" tabindex="0" aria-label="Karte drehen: ziehen oder Pfeiltasten"><div class="mailing-3d-card" style="aspect-ratio:${f.width}/${mode==='3d'&&isSelfmailer(c.project)?99:f.height}"><canvas class="build-face front" data-proof="front"></canvas><canvas class="build-face back" data-proof="back"></canvas></div></div>`:`<div class="build-flat"><canvas data-proof="${side}" aria-label="${side==='front'?'Vorderseite':'Rückseite'} des Mailings"></canvas></div>`}<div class="build-preview-caption"><span>${h(formatCaption(c.project))}</span><span>${mode==='3d'?'Geschlossen · ziehen zum Drehen':c.project.recipients.length?'Mit deinen Empfängerdaten':'Beispiel: Anna · Nordlicht Studio'}</span></div>${c.project.recipients.length?`<label class="build-person">Vorschau für<select id="build-person">${c.project.recipients.map((r,i)=>`<option value="${i}" ${i===person?'selected':''}>${h(r.salutation||r.company)} · ${h(r.company)}</option>`).join('')}</select></label>`:''}</section>`;}
 function layouts(){const list=BRAND_TEMPLATES.filter(t=>category==='all'||(category==='photo'?!!t.photo:!t.photo));return `<div class="build-section-heading"><div><h2>Welcher Auftritt passt zu dir?</h2><p>10 fertige Layouts. Texte, Logo und Farbe passt du im nächsten Schritt an.</p></div><span class="badge">DIN lang · 4-seitiger Selfmailer</span></div>${hasDesign(c.project)?`<div class="build-current"><div><strong>Dein aktuelles Design ist bereit.</strong><p>Du kannst damit weiterarbeiten oder unten eine andere Vorlage wählen.</p></div><button type="button" class="button primary" data-next>Mit diesem Design weiter →</button></div>`:''}<div class="build-layout-tools"><div class="build-segment">${[['all','Alle 10'],['photo','Mit Foto'],['type','Typografie']].map(([v,n])=>`<button type="button" data-category="${v}" aria-pressed="${category===v}">${n}</button>`).join('')}</div>${designs.length?`<label>Aus deiner Bibliothek<select id="build-library"><option value="">Gespeichertes Design auswählen</option>${designs.map(d=>`<option value="${d.id}">${h(d.name)}</option>`).join('')}</select></label>`:''}</div><div class="build-template-grid">${list.map((t,i)=>`<button class="build-template ${c.project.templateId===t.id?'selected':''}" type="button" data-template="${t.id}" aria-label="${h(t.name)} auswählen"><div class="build-template-art"><canvas data-layout="${t.id}"></canvas></div><div class="build-template-copy"><span>${h(t.tag)}</span><strong>${h(t.name)}</strong><small>${c.project.templateId===t.id?'Ausgewählt ✓':'Vorlage verwenden →'}</small></div></button>`).join('')}</div><div class="build-alternatives"><a href="${studio()}" data-open-studio>Eigenes PDF hochladen / frei gestalten ↗</a><button class="text-button" type="button" data-service>Gestaltung durch Kontaktstoff anfragen →</button><span>Andere Formate stehen im Detail-Editor bereit.</span></div>`;}
 function design(){const native=BRAND_TEMPLATES.some(t=>t.id===c.project.templateId),roles=[['brand','Deine Marke'],['headline','Überschrift'],['body','Persönliche Nachricht'],['cta','Handlungsaufforderung']];return `<div class="build-section-heading"><div><h2>Mach es zu deinem Mailing.</h2><p>Nur die Inhalte, die zählen. Dein Layout bleibt an seinem Platz.</p></div></div><div class="build-design-grid"><div class="build-controls">${input('Kampagnenname','campaignName',c.project.name,'maxlength="120" required')}${native?`${roles.map(([role,label])=>`<label>${label}<textarea data-brand="${role}" rows="${role==='body'?4:role==='headline'?3:1}" maxlength="${role==='body'?700:role==='headline'?160:100}">${h(brandValue(c.project,role))}</textarea></label>`).join('')}<div class="build-brand-tools">${input('Markenfarbe','brandColor',c.project.brandColor||BRAND_TEMPLATES.find(t=>t.id===c.project.templateId).color,'type="color"')}<label>Logo<input type="file" id="build-logo" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG oder WebP</small></label></div>${Object.values(c.project.sides).some(s=>s.fields.some(f=>f.brandRole==='brand'&&f.type==='image'))?'<button type="button" class="text-button" data-remove-logo>Logo entfernen · Markennamen anzeigen</button>':''}${Object.values(c.project.sides).some(s=>s.fields.some(f=>f.brandRole==='photo'))?'<label>Motiv austauschen<input type="file" id="build-photo" accept="image/png,image/jpeg,image/webp"></label>':''}`:`<p>Dein individuelles Design bleibt erhalten. Bearbeite die Texte hier; Positionen, Bilder und Schriftgrößen im Detail-Editor.</p><label>Kartenseite<select id="build-edit-side"><option value="front" ${side==='front'?'selected':''}>${sideLabel(c.project,'front')}</option>${sideNames(c.project).includes('back')?`<option value="back" ${side==='back'?'selected':''}>${sideLabel(c.project,'back')}</option>`:''}</select></label>${c.project.sides[side].fields.filter(f=>f.type==='text'&&!f.text.includes('{{')).map((f,i)=>`<label>Text ${i+1}<textarea data-text-id="${f.id}" data-side="${side}" rows="2" maxlength="5000">${h(f.text)}</textarea></label>`).join('')}`}<a class="text-button" href="${studio()}" data-open-studio>Details im Editor bearbeiten ↗</a></div>${preview()}</div>`;}
 function personalization(){const result=campaignReadiness(c.project,c.meta);return `<div class="build-section-heading"><div><h2>Eine Karte. Für jeden persönlich.</h2><p>CSV hochladen, Spalten zuordnen und die fertige Karte pro Kontakt ansehen.</p></div></div><div class="build-design-grid"><section class="build-controls"><div class="build-segment"><button type="button" data-leads="upload" aria-pressed="${c.meta.leadSource==='upload'}">Eigene Kontakte</button><button type="button" data-leads="research" aria-pressed="${c.meta.leadSource==='research'}">Recherche anfragen</button></div>${c.meta.leadSource==='research'?`${input('Wen möchtest du erreichen?','audience',c.meta.audience,'placeholder="z. B. inhabergeführte Hotels"')}${input('Region','region',c.meta.region,'placeholder="z. B. Hamburg und Umgebung"')}${input('Gewünschte Anzahl','quantity',c.meta.quantity,'type="number" min="1" max="100000"')}<p>Wir stimmen Zielgruppe, Verfügbarkeit und Preis mit dir ab.</p>`:`<div class="build-upload"><strong>${c.project.recipients.length?c.project.recipients.length+' Kontakte hinterlegt':'Deine Empfängerliste'}</strong><p>Name, Anschrift und Ziel-Link – weitere persönliche Felder sind möglich.</p><label class="button primary">CSV hochladen ↑<input type="file" id="build-csv" accept=".csv,text/csv" hidden></label><button type="button" class="text-button" data-csv-example>CSV-Muster herunterladen ↓</button></div>${audiences.length?`<label>Gespeicherte Zielgruppe<select id="build-audience"><option value="">Zielgruppe auswählen</option>${audiences.map(a=>`<option value="${a.id}">${h(a.name)} · ${a.recipients.length} Kontakte</option>`).join('')}</select></label>`:''}${input('Name der Zielgruppe','audience',c.meta.audience,'placeholder="z. B. Warenkorbabbrecher September"')}${input('Gemeinsamer Ziel-Link (optional)','targetURL',c.meta.targetURL,'type="url" placeholder="https://deine-website.de/angebot"')}<button type="button" class="button" data-fill-links>Fehlende Links ergänzen</button><small>Individuelle Links bleiben erhalten.</small>${c.project.recipients.length?`<a href="${studio('recipients')}" data-open-studio>Empfänger und Platzhalter bearbeiten ↗</a>`:''}`}${result.errors.length?`<div class="build-checks"><strong>Noch zu ergänzen</strong><ul>${result.errors.slice(0,5).map(e=>`<li>${h(e)}</li>`).join('')}</ul></div>`:'<div class="success">Empfängerdaten und Platzhalter sind vollständig.</div>'}<details><summary>Wie werden Platzhalter ersetzt?</summary><p><code>{{first_name}}</code> wird zu <strong>Anna</strong>. <code>{{salutation}}</code> wird zu <strong>Hallo Anna,</strong>. Der QR-Code öffnet den Link des jeweiligen Kontakts.</p></details></section>${preview()}</div>`;}
 function final(){const result=campaignReadiness(c.project,c.meta);return `<div class="build-section-heading"><div><h2>Ein letzter Blick. Dann zu uns.</h2><p>Wir prüfen deinen Entwurf und stimmen Angebot, Druckdaten und Versand mit dir ab.</p></div></div>${c.meta.status==='requested'?'<div class="success"><strong>Deine Anfrage liegt bei Kontaktstoff.</strong><p>Weitere Änderungen am Entwurf verändern die bereits gesendete Anfrage nicht.</p></div>':''}<div class="build-design-grid"><section class="build-controls"><dl class="flow-summary"><dt>Format</dt><dd>${h(FORMATS.find(f=>f.id===c.project.format).name)}</dd><dt>Empfänger</dt><dd>${c.meta.leadSource==='research'?c.meta.quantity+' · Recherche angefragt':c.project.recipients.length+' Kontakte'}</dd><dt>Gestaltung</dt><dd>${c.meta.designService?'Durch Kontaktstoff angefragt':'Eigenes Design'}</dd></dl>${input('Gewünschter Versandtag','launchDate',c.meta.launchDate,'type="date"')}<label>Kampagnenziel<select name="goal">${Object.entries({appointment:'Gespräch / Termin',purchase:'Kauf / Warenkorbrückgewinnung',demo:'Demo ansehen',offer:'Angebot anfragen',event:'Event / Anmeldung'}).map(([v,n])=>`<option value="${v}" ${v===c.meta.goal?'selected':''}>${n}</option>`).join('')}</select></label><label>Mitteilung an Kontaktstoff<textarea name="notes" rows="3" maxlength="3000">${h(c.meta.notes)}</textarea></label>${result.errors.length?`<div class="build-checks"><strong>Vor dem Absenden ergänzen</strong><ul>${result.errors.map(e=>`<li>${h(e)}</li>`).join('')}</ul><button type="button" class="button" data-step="2">Empfängerdaten prüfen →</button></div>`:`<div class="success">${c.meta.designService?'Briefing':'Design und Empfängerdaten'} bereit zur Prüfung.</div>`}${result.warnings.length?`<details><summary>${result.warnings.length} Hinweise zum Entwurf</summary><ul>${result.warnings.map(w=>`<li>${h(w)}</li>`).join('')}</ul></details>`:''}<label class="build-consent"><input type="checkbox" id="build-confirm"> <span>Ich habe ${c.meta.designService?'mein Briefing':'die Kartenseiten und persönlichen Inhalte'} geprüft und möchte diesen Stand an Kontaktstoff zur Prüfung senden.</span></label><button type="button" class="button primary" data-submit ${result.errors.length?'disabled':''}>${c.meta.status==='requested'?'Überarbeitung':'Kampagne'} zur Prüfung senden →</button><small>Unverbindliche Anfrage. Die finale Druckfreigabe und Kosten stimmen wir separat ab.</small>${!c.local?`<a href="/konto/?tab=reviews&source=campaigns:${c.id}" data-leave>Vorher Feedback per Kundenlink einholen ↗</a>`:''}<div class="build-handoff"><strong>So geht es danach weiter</strong><ol><li>Kontaktstoff prüft deine Anfrage.</li><li>Wir stimmen Angebot und letzte Änderungen ab.</li><li>Nach finaler Freigabe organisieren wir Druck und Versand.</li></ol></div></section>${preview()}</div>`;}
 function draw(){if(!alive())return;viewer?.destroy();viewer=null;if(!sideNames(c.project).includes(side))side='front';if(sideNames(c.project).length===1)mode='2d';root.innerHTML=`<div class="build-header"><div><span class="eyebrow">DEINE KAMPAGNE</span><h1>${h(c.project.name)}</h1></div><div class="actions">${c.local?'<button type="button" class="button" data-online>Entwurf online speichern →</button>':''}<a href="/konto/?tab=analytics&id=${c.id}" data-leave class="text-button">Zum Tracking ↗</a></div></div><nav class="build-steps" aria-label="Kampagne vorbereiten">${BUILD_STEPS.map((name,i)=>`<button type="button" data-step="${i}" ${i===step?'aria-current="step"':''}><b>${i+1}</b><span>${name}</span></button>`).join('')}</nav><form id="build-form"><p class="error" id="build-error" role="alert" hidden></p>${[layouts,design,personalization,final][step]()}<div class="build-footer"><button type="button" class="button" data-back ${step?'':'disabled'}>← Zurück</button><span id="build-saved">${c.local?'Entwurf in diesem Browser':'Entwurf im Unternehmenskonto'}</span>${step<3?`<button type="button" class="button primary" data-next>${['Design anpassen','Empfänger hinzufügen','Alles prüfen'][step]} →</button>`:`<button type="button" class="button" data-save>Entwurf speichern</button>`}</div></form>`;bind();paint();}
 async function paint(){const generation=++paintId;try{for(const canvas of root.querySelectorAll('canvas[data-layout],canvas[data-proof]')){if(generation!==paintId||!alive())return;const p=canvas.dataset.layout?toSelfmailer(createBrandTemplate(canvas.dataset.layout)):c.project;const closed=isSelfmailer(p)&&canvas.dataset.layout;await renderCanvas(canvas,p,closed?'front':canvas.dataset.proof||'front',p.recipients[person]||p.recipients[0]||PREVIEW_PERSON,{scale:canvas.dataset.layout?2:4,panel:closed?(canvas.dataset.proof==='back'?'address':'cover'):null,guides:!closed&&isSelfmailer(p)});}if(mode==='3d'&&$('.build-stage')&&generation===paintId){const fresh=!viewer;viewer||=new Mailing3D($('.build-stage'));viewer.setSelfmailer(isSelfmailer(c.project));if(isSelfmailer(c.project))viewer.setSpreads($('[data-proof=front]'),$('[data-proof=back]'));if(fresh&&side==='back')viewer.back();}}catch(e){if(alive())error(e);}}
 async function goto(next){await flush();if(next===1&&!hasDesign(c.project)&&!c.meta.designService)throw Error('Wähle zuerst eine Vorlage oder lade dein eigenes Design hoch.');step=next;c.meta.builder.step=step;await persist();const u=new URL(location.href);u.searchParams.set('step',step);history.replaceState({},'',u);draw();root.scrollIntoView({block:'start',behavior:'smooth'});}
 async function use(project,source){if(!source)project=toSelfmailer(project);if(hasDesign(c.project)&&!await confirm('Layout ersetzen?','Texte und Gestaltung werden durch die ausgewählte Vorlage ersetzt. Deine Empfängerliste bleibt erhalten.','Vorlage verwenden'))return;await flush();const before=c.project;project.id=before.id;project.name=before.name;project.recipients=before.recipients;project.sample=before.sample;c.project=project;c.meta.designService=false;c.meta.formatRequest=project.format;c.meta.designId=source?.id||'';c.meta.designRevision=source?.revision||0;await goto(1);}
 async function upload(file,role){if(!file)return;if(file.size>10*1024*1024)throw Error('Bitte ein Bild mit höchstens 10 MB wählen.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Bitte PNG, JPG oder WebP verwenden.');const url=URL.createObjectURL(file);try{const image=await imageFrom(url),canvas=document.createElement('canvas'),ratio=Math.min(1,1800/Math.max(image.width,image.height));canvas.width=Math.round(image.width*ratio);canvas.height=Math.round(image.height*ratio);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');capture();for(const s of Object.values(c.project.sides))for(const f of s.fields)if(f.brandRole===role){f.type='image';f.data=data;f.fit=role==='brand'?'contain':'cover';}await persist();draw();}finally{URL.revokeObjectURL(url);}}
 function bind(){
  $('#build-form').onsubmit=e=>e.preventDefault();
  $('#build-form').oninput=e=>{if(e.target.matches('textarea,input[name]')){dirty=true;capture();if($('#build-saved'))$('#build-saved').textContent='Wird gespeichert …';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(alive())persist().catch(error);},600);paint();}};
  $('#build-form').onchange=e=>{if(e.target.matches('[data-brand],[data-text-id],[name]')){clearTimeout(saveTimer);dirty=true;capture();persist().then(()=>paint()).catch(error);}};
  if($('#build-csv'))$('#build-csv').onchange=e=>{const file=e.target.files[0];if(!file)return;openCSVImport(file,{keys:[...new Set([...Object.keys(KEYS),...Object.values(c.project.sides).flatMap(s=>s.fields.flatMap(f=>[...f.text.matchAll(/\{\{(\w+)\}\}/g)].map(m=>m[1])))])],existingCount:c.project.recipients.length,onImport:(rows,mode)=>{c.project.recipients=mode==='append'?[...c.project.recipients,...rows]:rows;if(mode==='replace')c.project.sample=false;c.meta.audience||=file.name.replace(/\.csv$/i,'');c.meta.quantity=c.project.recipients.length;person=0;persist().then(draw).catch(error);}});};
  for(const [id,role] of [['#build-logo','brand'],['#build-photo','photo']])if($(id))$(id).onchange=e=>upload(e.target.files[0],role).catch(error);
  if($('#build-person'))$('#build-person').onchange=e=>{person=Number(e.target.value);paint();};
  if($('#build-edit-side'))$('#build-edit-side').onchange=async e=>{try{await flush();side=e.target.value;draw();}catch(e){error(e);}};
  if($('#build-library'))$('#build-library').onchange=e=>{const d=designs.find(d=>d.id===e.target.value);if(d)use(structuredClone(d.project),d).catch(error);};
  if($('#build-audience'))$('#build-audience').onchange=async e=>{try{const a=audiences.find(a=>a.id===e.target.value);if(!a)return;if(c.project.recipients.length&&!await confirm('Empfängerliste ersetzen?','Die gespeicherte Zielgruppe ersetzt die Kontakte in dieser Kampagne.','Übernehmen'))return;capture();c.project.recipients=structuredClone(a.recipients);c.project.sample=false;c.meta.audience=a.name;c.meta.audienceId=a.id;c.meta.audienceRevision=a.revision;c.meta.quantity=Math.max(1,a.recipients.length);person=0;await persist();draw();}catch(e){error(e);}};
 }
 root.onclick=async e=>{const b=e.target.closest('button,a');if(!b)return;if(busy){e.preventDefault();return;}try{
  if(b.hasAttribute('data-leave')||b.hasAttribute('data-open-studio')){e.preventDefault();await flush();location.href=b.href;return;}
  busy=true;b.disabled=true;
  if(b.dataset.template)await use(createBrandTemplate(b.dataset.template));
  if(b.hasAttribute('data-step'))await goto(Number(b.dataset.step));
  if(b.hasAttribute('data-next'))await goto(Math.min(3,step+1));
  if(b.hasAttribute('data-back'))await goto(Math.max(0,step-1));
  if(b.hasAttribute('data-save')){await flush();notice('Entwurf gespeichert.');}
  if(b.dataset.side){capture();side=b.dataset.side;draw();}
  if(b.dataset.mode){capture();mode=b.dataset.mode;draw();}
  if(b.dataset.category){category=b.dataset.category;draw();}
  if(b.dataset.leads){capture();c.meta.leadSource=b.dataset.leads;await persist();draw();}
  if(b.hasAttribute('data-service')){c.meta.designService=true;await goto(2);}
  if(b.hasAttribute('data-remove-logo')){capture();for(const s of Object.values(c.project.sides))for(const f of s.fields)if(f.brandRole==='brand'){f.type='text';delete f.data;delete f.fit;}await persist();draw();}
  if(b.hasAttribute('data-fill-links')){capture();if(!validURL(c.meta.targetURL))throw Error('Trage zuerst einen gültigen Ziel-Link ein.');const key=Object.values(c.project.sides).some(s=>s.fields.some(f=>f.type==='qr'&&f.text.includes('{{cart_url}}')))?'cart_url':'chatbot_url';for(const r of c.project.recipients)if(!r[key])r[key]=c.meta.targetURL;await persist();draw();}
  if(b.hasAttribute('data-csv-example')){const u=URL.createObjectURL(new Blob([csvString([{company:'Beispiel GmbH',first_name:'Anna',last_name:'Beispiel',salutation:'Hallo Anna,',street:'Musterstraße 1',postal_code:'10115',city:'Berlin',country:'Deutschland',chatbot_url:'https://example.org/angebot'}],['company','first_name','last_name','salutation','street','postal_code','city','country','chatbot_url'])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='kontaktstoff-kontakte-muster.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  if(b.hasAttribute('data-online')){await flush();await saveOnline(c);}
  if(b.hasAttribute('data-submit')){capture();if(!$('#build-confirm').checked)throw Error('Bestätige bitte, dass du diesen Stand geprüft hast.');const result=campaignReadiness(c.project,c.meta);if(result.errors.length)throw Error(result.errors[0]);await flush();await submit(c);}
 }catch(e){error(e);}finally{busy=false;b.disabled=false;}};
 draw();if(user)Promise.all([api('/library/audiences'),api('/library/designs')]).then(([a,d])=>{audiences=a.items;designs=d.items;if(alive()&&(step===0||step===2)){capture();draw();}}).catch(error);
 return {flush};
}
