import {sideNames} from '../../studio/src/core.js';
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reviewProgress(r){
 const resolved=new Set(r.events.filter(e=>e.type==='resolve').map(e=>e.commentId));
 const comments=r.events.filter(e=>e.type==='comment'&&e.version===r.version),open=comments.filter(e=>!resolved.has(e.id));
 const state=r.status==='revoked'?'revoked':r.stale?'ready':r.status==='approved'?'approved':open.length?'changes':'open';
 const labels={revoked:'Kundenzugang gesperrt',ready:'Überarbeitung bereit',approved:'Design freigegeben',changes:'Änderungen offen',open:'Wartet auf Kundenfeedback'};
 return {resolved,comments,open,state,label:labels[state]};
}
export function reviewProject(r,{side,zoom,button}){
 const p=reviewProgress(r),editable=!['approved','revoked'].includes(r.status),editURL=`/studio/?${r.sourceKind==='designs'?'design':'cloud'}=${r.sourceId}&review=${r.id}`;
 const descriptions={open:'Teile den Kundenlink. Dein Kunde kann Stellen markieren und das Design freigeben.',changes:`${p.open.length} ${p.open.length===1?'Änderungswunsch wartet':'Änderungswünsche warten'} auf Bearbeitung. Klicke auf eine Markierung oder lies das Feedback rechts.`,ready:'Du hast das Design bearbeitet. Stelle den neuen Stand zur Prüfung bereit – der Kundenlink bleibt gleich.',approved:'Dieser Designstand ist bestätigt. Druck und Versand werden separat beauftragt.',revoked:'Der Kundenlink ist gesperrt. Unter „Weitere Optionen“ kannst du den Zugang verwalten.'};
 const next=p.state==='ready'?button('publish-review','Überarbeitetes Design bereitstellen','',true):p.state==='changes'?`<a class="button primary" href="${editURL}">Änderungen bearbeiten ↗</a>`:p.state==='open'&&r.url?button('copy-review-link','Kundenlink kopieren','',true):'';
 const comment=(e,i,old=false)=>`<article class="flow-comment ${p.resolved.has(e.id)?'is-resolved':''}" id="owner-comment-${e.id}" tabindex="-1"><div><b>${e.type==='approve'?'✓':i+1+'.'} ${h(e.name)}</b><small class="block">${e.side==='front'?'Vorderseite':e.side==='back'?'Rückseite':'Allgemein'}${p.resolved.has(e.id)?' · Erledigt':''}</small><p>${h(e.text)}</p>${!old&&e.side?button('show-mark','Markierung ansehen',`data-id="${e.id}"`):''}</div>${!old&&!p.resolved.has(e.id)&&editable?button('resolve-comment','Als erledigt markieren',`data-id="${e.id}"`):''}</article>`;
 return `<section class="project-next ${p.state==='ready'?'banner':''}" aria-label="Nächster Schritt"><div><span class="badge ${p.state==='approved'?'approved':''}">${p.label}</span><p>${descriptions[p.state]}</p></div>${next}</section>
 <div class="review-project"><section class="panel project-design"><div class="project-toolbar"><div class="project-sides" aria-label="Kartenseite">${sideNames(r.project).map(s=>button('review-side',s==='front'?'Vorderseite':'Rückseite',`data-side="${s}" aria-pressed="${side===s}"`)).join('')}</div><label>Zoom<select id="owner-zoom"><option value="1" ${zoom===1?'selected':''}>Einpassen</option><option value="1.5" ${zoom===1.5?'selected':''}>150 %</option><option value="2" ${zoom===2?'selected':''}>200 %</option></select></label></div><p class="field-help">${editable?'Klicke auf eine Stelle der Karte und schreibe deinen Änderungswunsch.':'Dieser Stand ist schreibgeschützt.'} · Der Kunde sieht diese Version.</p>
 <div class="owner-scroll"><div class="owner-proof" data-owner-sheet="${side}" style="width:${zoom*100}%" role="button" tabindex="${editable?'0':'-1'}" aria-disabled="${!editable}" aria-label="${side==='front'?'Vorderseite':'Rückseite'}: Änderung markieren"><canvas data-review-proof="${side}"></canvas>${p.comments.filter(e=>e.side===side).map(e=>`<button type="button" class="owner-pin ${p.resolved.has(e.id)?'resolved':''}" data-flow="focus-comment" data-id="${e.id}" style="left:${e.x*100}%;top:${e.y*100}%" aria-label="Kommentar ${p.comments.indexOf(e)+1} ansehen">${p.comments.indexOf(e)+1}</button>`).join('')}</div></div>
 <div class="project-design-footer"><a class="text-button" href="${editURL}">Design bearbeiten ↗</a><span>Version ${r.version} · Nur Designfreigabe, kein Druckauftrag</span></div></section>
 <aside class="project-feedback panel"><div class="project-feedback-heading"><h2>Feedback <span class="badge">${p.open.length} offen</span></h2>${editable?button('owner-comment','Kommentar schreiben'):''}</div><p class="field-help">Kommentare hier sind auch für deinen Kunden sichtbar.</p>${p.comments.length?p.comments.map((e,i)=>comment(e,i)).join(''):`<div class="project-empty"><b>Noch keine Änderungswünsche.</b><p>${editable?'Klicke auf die Karte, um die erste Stelle zu markieren.':'Dieser Designstand ist schreibgeschützt.'}</p></div>`}${p.state==='approved'?'<p class="approval-confirmed">✓ Design bestätigt. Es wurde nichts bestellt.</p>':''}</aside></div>
 <section class="panel project-sharing flow-share"><div><h2>Mit deinem Kunden teilen</h2>${r.url?`<label>Dein Kundenlink<input id="share-url" readonly value="${h(r.url)}"></label><div class="actions">${p.state!=='open'?button('copy-review-link','Kundenlink kopieren'):''}<a class="button" href="${h(r.url)}" target="_blank" rel="noopener noreferrer">Kundenansicht öffnen ↗</a></div><p class="field-help">Ohne Anmeldung. Derselbe Link für die gesamte Abstimmung.</p>`:'<p>Der Kundenlink ist momentan nicht verfügbar.</p>'}</div><details class="flow-actions"><summary>Weitere Optionen</summary>${button('rotate-review','Kundenlink ersetzen …')}${button('revoke-review','Kundenzugang sperren',r.status==='revoked'?'disabled':'')}${button('delete-review','Freigabe löschen',`data-id="${r.id}"`)}</details></section>
 <details class="panel project-history"><summary>Bisherige Abstimmung · ${r.versions.length} ${r.versions.length===1?'Version':'Versionen'}</summary>${r.versions.map(v=>`<h3>Version ${v.version} · ${new Date(v.createdAt).toLocaleDateString('de-DE')}</h3>${r.events.filter(e=>e.version===v.version&&e.type!=='resolve'&&(v.version!==r.version||e.type==='approve')).map((e,i)=>comment(e,i,true)).join('')||'<p>Aktuelles Feedback steht neben der Karte.</p>'}`).join('')}</details>`;
}
