import {mountProposalTools} from './proposal-tools.js';
import {api} from './api.js';
import {salesLink,SALES_CASES} from '../../mailings/config.js';
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={new:'Neu',contacted:'Kontaktiert',qualified:'Pilot planen',closed:'Abgeschlossen',archived:'Archiviert'};
const date=v=>new Date(v).toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'});
export async function mountSales(root,{view,notice}){
 const $=s=>root.querySelector(s);let items=[],selected=null,filter='active';
 const nav=()=>`<nav class="campaign-mode"><a href="/konto/?tab=sales-inquiries" data-view="sales-inquiries" ${view==='sales-inquiries'?'aria-current="page"':''}>Interessenten</a><a href="/konto/?tab=inbox" data-view="inbox">Kampagnenanfragen</a><a href="/konto/?tab=sales-links" data-view="sales-links" ${view==='sales-links'?'aria-current="page"':''}>Verkaufslinks</a></nav>`;
 if(view==='sales-links'){await mountProposalTools(root,{notice});return;}
 async function refresh(){items=(await api('/operator/sales')).items;if(root.isConnected)draw();}
 function draw(){if(!root.isConnected)return;if(selected)selected=items.find(i=>i.id===selected.id);root.innerHTML=`<div class="page-heading"><div><h1>${selected?h(selected.company):'Neue Interessenten.'}</h1><p>${selected?'Anfrage über die Verkaufsseite · '+h(date(selected.createdAt)):'Anfragen ohne Konto. Der Einstieg in die nächste Kampagne.'}</p></div><button class="button" data-refresh>Aktualisieren ↻</button></div>${nav()}${selected?detail():list()}`;bind();}
 function list(){const visible=items.filter(i=>filter==='all'||(filter==='archived'?i.status==='archived':i.status!=='archived'));return `<section class="panel"><div class="panel-heading"><h2>${visible.length} Anfragen</h2><label>Status<select id="sales-filter"><option value="active" ${filter==='active'?'selected':''}>Aktive Anfragen</option><option value="archived" ${filter==='archived'?'selected':''}>Archivierte</option><option value="all" ${filter==='all'?'selected':''}>Alle</option></select></label></div>${visible.length?`<div class="table-wrap"><table><thead><tr><th>Eingang</th><th>Unternehmen</th><th>Ansprechpartner</th><th>Ziel</th><th>Status</th><th></th></tr></thead><tbody>${visible.map(i=>`<tr><td>${h(date(i.createdAt))}</td><td>${h(i.company)}</td><td>${h(i.name)}</td><td>${h(SALES_CASES[i.useCase])}</td><td>${h(statuses[i.status])}</td><td><button class="text-button" data-lead="${i.id}">Anfrage öffnen →</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h3>${filter==='archived'?'Keine archivierten Anfragen.':'Hier kommen eure ersten Gespräche an.'}</h3><p>Teile die Verkaufsseite zusammen mit deinem Loom. Anfragen erscheinen automatisch in diesem Bereich.</p><a class="button primary" href="/konto/?tab=sales-links" data-view="sales-links">Verkaufslink erstellen →</a></div>`}<p class="under-note">Die letzten 200 Anfragen. Benachrichtigungen per E-Mail sind noch nicht eingerichtet.</p></section>`;}
 function detail(){const r=selected;return `<button class="text-button" data-back>← Alle Interessenten</button><div class="analysis-grid sales-detail"><section class="panel"><h2>Das möchte ${h(r.name)} besprechen.</h2><dl class="request-details">${[['Name',r.name],['Unternehmen',r.company],['E-Mail',r.email],['Ziel',SALES_CASES[r.useCase]],['Kontakte',r.quantity===2000?'2.000 oder mehr':r.quantity||'Noch offen'],['Nachricht',r.message],['Firmenbezug des geteilten Links',r.sourceCompany||'Allgemeine Verkaufsseite']].map(([k,v])=>`<dt>${k}</dt><dd>${h(v||'—')}</dd>`).join('')}</dl>${r.proposalSlug?`<p><a class="text-button" href="/mailings/?konzept=${encodeURIComponent(r.proposalSlug)}" target="_blank" rel="noopener">Zugehörige Kundenseite ansehen ↗</a></p>`:''}<p class="under-note">Kontaktangaben stammen vom Interessenten. Noch kein Auftrag und kein automatisch angelegtes Kundenkonto.</p></section><form class="panel" id="lead-status-form"><h2>Nächster Schritt</h2><label>Status<select name="status">${Object.entries(statuses).map(([v,n])=>`<option value="${v}" ${v===r.status?'selected':''}>${n}</option>`).join('')}</select></label><label>Interne Notiz<textarea name="note" rows="5" maxlength="3000">${h(r.note)}</textarea></label><p class="error" role="alert" hidden></p><button class="button primary">Speichern</button><p class="under-note">Interne Verwaltung. Es wird keine Nachricht an den Interessenten verschickt.</p></form></div>`;}
 function bind(){if($('#sales-filter'))$('#sales-filter').onchange=e=>{filter=e.target.value;draw();};if($('[data-back]'))$('[data-back]').onclick=()=>{selected=null;draw();};$('[data-refresh]').onclick=()=>refresh().catch(e=>notice(e.message));root.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{selected=items.find(i=>i.id===b.dataset.lead);draw();});if($('#lead-status-form'))$('#lead-status-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const d=Object.fromEntries(new FormData(e.target));await api('/operator/sales/'+selected.id,{method:'PUT',body:{...d,revision:selected.revision}});await refresh();notice('Anfrage aktualisiert.');}catch(err){const el=$('#lead-status-form .error');el.textContent=err.message;el.hidden=false;}finally{if(e.submitter.isConnected)e.submitter.disabled=false;}};}
 root.innerHTML='<p role="status">Interessenten werden geladen …</p>';try{await refresh();}catch(e){root.innerHTML=`<p class="error">${h(e.message)}</p>`;}
}
