import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {connectDB} from '../server/db.js';
import {createAPI} from '../server/api.js';
import {createCampaign} from '../studio/src/core.js';
import {defaults,metrics} from '../konto/src/model.js';
const origin='http://localhost:9000';
async function fixture(){const db=await connectDB({file:':memory:'}),handle=createAPI(db,{origin});async function request(route,{method='GET',body,account,prepared=false,headers={}}={}){const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);Object.assign(req,{url:route,method,headers:{origin,'content-type':'application/json',...(account?{cookie:account.cookie,'x-csrf-token':account.csrf}:{}),...headers},socket:{remoteAddress:'127.0.0.1'},...(prepared?{body}:{})});let status,raw;const received={};const res={setHeader:(k,v)=>received[k]=v,writeHead:(s,h)=>{status=s;Object.assign(received,h);},end:data=>raw=data};await handle(req,res);return {status,headers:received,data:raw?JSON.parse(raw):null};}async function register(email){const r=await request('/api/auth/register',{method:'POST',body:{email,password:'a-test-password-123',profile:{company:'Test GmbH',name:'Mara Test'}}});assert.equal(r.status,201);return {cookie:r.headers['Set-Cookie'].split(';')[0],csrf:r.data.csrf};}return {db,request,register};}
test('real accounts require same-origin writes, hash passwords and isolate campaigns',async()=>{const {db,request,register}=await fixture();try{const a=await register('a@example.org'),b=await register('b@example.org');const project=createCampaign(true),created=await request('/api/campaigns',{method:'POST',account:a,body:{project,meta:defaults()}});assert.equal(created.status,201);const id=created.data.id;assert.equal((await request('/api/campaigns/'+id,{account:b})).status,404);assert.equal((await request('/api/campaigns')).status,401);assert.equal((await request('/api/campaigns/'+id,{method:'DELETE',account:a,headers:{origin:'https://other.example'}})).status,403);assert.equal((await request('/api/campaigns/'+id,{method:'DELETE',account:a,headers:{'x-csrf-token':'bad'}})).status,403);assert.equal((await request('/api/campaigns',{account:b})).data.campaigns.length,0);assert.ok(!(await db.query('SELECT password FROM users')).rows[0].password.includes('a-test-password'));assert.match(a.cookie,/kontaktstoff_session=/);await request('/api/auth/logout',{method:'POST',account:a,body:{}});assert.equal((await request('/api/auth/me',{account:a})).data.user,null);}finally{await db.close();}});
test('optimistic revisions reject stale edits and service requests retain immutable snapshots',async()=>{const {db,request,register}=await fixture();try{const a=await register('request@example.org'),project=createCampaign(true),meta={...defaults(),designService:true,leadSource:'research',audience:'Webdesign-Agenturen',region:'DACH'};const c=(await request('/api/campaigns',{method:'POST',account:a,body:{project,meta}})).data;assert.equal((await request('/api/campaigns/'+c.id,{method:'PUT',account:a,body:{...c,revision:0}})).status,409);const key=crypto.randomUUID(),r=await request('/api/campaigns/'+c.id+'/request',{method:'POST',account:a,body:{key,revision:1}});assert.equal(r.status,201);assert.equal((await request('/api/campaigns/'+c.id+'/request',{method:'POST',account:a,body:{key,revision:1}})).data.id,key);assert.equal((await db.query('SELECT * FROM requests')).rows.length,1);const next=(await request('/api/campaigns/'+c.id,{account:a})).data;next.project.name='Changed after request';const update=await request('/api/campaigns/'+c.id,{method:'PUT',account:a,body:next});assert.equal(update.status,200);assert.notEqual(JSON.parse((await db.query('SELECT payload FROM requests')).rows[0].payload).project.name,'Changed after request');assert.equal(update.data.meta.status,'requested');}finally{await db.close();}});
test('requests validate prerequisites and invalid campaign data is not accepted',async()=>{const {db,request,register}=await fixture();try{const a=await register('invalid@example.org'),project=createCampaign(true);const c=(await request('/api/campaigns',{method:'POST',account:a,body:{project,meta:defaults()}})).data;const r=await request('/api/campaigns/'+c.id+'/request',{method:'POST',account:a,body:{key:crypto.randomUUID(),revision:1}});assert.equal(r.status,400);assert.match(r.data.error,/Kontaktliste/);assert.equal((await request('/api/campaigns',{method:'POST',account:a,body:{project:{},meta:{}}})).status,400);assert.equal((await request('/api/campaigns',{method:'POST',account:a,body:{project,meta:{...defaults(),targetURL:'javascript:alert(1)'}}})).status,400);}finally{await db.close();}});
test('tracking creates per-contact redirects, counts visits, excludes HEAD and stops deleted campaigns',async()=>{const {db,request,register}=await fixture();try{const a=await register('track@example.org'),b=await register('other@example.org'),project=createCampaign();project.sample=false;const c=(await request('/api/campaigns',{method:'POST',account:a,body:{project,meta:defaults()}})).data;const updated=await request('/api/campaigns/'+c.id+'/tracking',{method:'POST',account:a,body:{revision:1}});assert.equal(updated.status,200);const links=updated.data.project.recipients.map(r=>new URL(r.chatbot_url).pathname);assert.equal(new Set(links).size,3);const click=await request(links[0]);assert.equal(click.status,302);assert.equal(click.headers.Location,'https://chattastic.de/');await request(links[0]);await request(links[0],{method:'HEAD'});await request(links[1],{headers:{'user-agent':'crawler'}});const stats=(await request('/api/campaigns/'+c.id+'/stats',{account:a})).data;assert.equal(Number(stats.visits.find(v=>v.recipient_id===project.recipients[0].id).count),2);assert.equal((await request('/api/campaigns/'+c.id+'/stats',{account:b})).status,404);const m=metrics(updated.data.project,updated.data.meta,stats.visits);assert.equal(m.scans,2);assert.equal(m.scannedContacts,1);await request('/api/campaigns/'+c.id,{method:'DELETE',account:a});assert.equal((await request(links[0])).status,404);}finally{await db.close();}});
test('server data survives database reconnection',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'kontaktstoff-db-')),file=path.join(dir,'db.sqlite');try{const first=await connectDB({file});await first.query('INSERT INTO users(id,email,password,profile,created_at) VALUES($1,$2,$3,$4,$5)',['id','persist@example.org','hash','{}',Date.now()]);await first.close();const second=await connectDB({file});assert.equal((await second.query('SELECT email FROM users')).rows[0].email,'persist@example.org');await second.close();}finally{await rm(dir,{recursive:true,force:true});}});
test('funnel and ROI use actual won contribution and cumulative sales stages',()=>{const project={recipients:[{id:'1'},{id:'2'},{id:'3'}]},meta={...defaults(),cost:100,outcomes:{1:{sales:'won',shipping:'sent',contribution:300},2:{sales:'appointment',shipping:'sent',contribution:500},3:{sales:'conversation',shipping:'pending',contribution:0}}};assert.deepEqual({...metrics(project,meta),rows:[]},{sent:2,conversations:3,appointments:2,won:1,contribution:300,cost:100,roi:200,scans:0,scannedContacts:0,rows:[]});assert.equal(metrics(project,{...meta,cost:0}).roi,null);});

test('Vercel parsed-body requests work and malformed bodies are rejected',async()=>{const {db,request,register}=await fixture();try{const a=await register('prepared@example.org');const created=await request('/api/campaigns',{method:'POST',account:a,prepared:true,body:{project:createCampaign(true),meta:defaults()}});assert.equal(created.status,201);assert.equal((await request('/api/profile',{method:'PUT',account:a,prepared:true,body:null})).status,400);assert.equal((await request('/api/campaigns',{method:'POST',account:a,prepared:true,body:[]})).status,400);}finally{await db.close();}});
