import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {csvString} from '../studio/src/core.js';
const origin='http://127.0.0.1:4183';await mkdir('test-results/builder',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin+'/konto/?tab=new-campaign');await page.locator('[name=name]').fill('Nordwerk · September');await page.locator('#start-campaign-form button').click();await expect(page).toHaveURL(/tab=build/);await expect(page.locator('[data-template]')).toHaveCount(10);await expect(page.locator('[data-layout=personal-letter]')).toHaveJSProperty('width',420);await page.screenshot({path:'test-results/builder/layouts.png',fullPage:true});
 await page.locator('[data-template=stacked-note]').click();await expect(page.locator('[data-brand=brand]')).toBeVisible();await page.locator('[data-brand=brand]').fill('NORDWERK');await page.locator('[data-brand=headline]').fill('Deine nächste\ngute Idee.');await page.locator('[data-brand=body]').fill('Wir haben einen Vorschlag für dich. Lass uns gemeinsam herausfinden, was zu deinem Unternehmen passt.');await page.locator('[data-brand=cta]').fill('Persönlichen Termin wählen →');await page.locator('[data-brand=cta]').blur();await expect(page.locator('#build-saved')).toContainText('gespeichert');
 await page.locator('[data-mode="3d"]').click();await expect(page.locator('.build-stage')).toBeVisible();await page.locator('[data-side=back]').click();await page.screenshot({path:'test-results/builder/design-3d.png',fullPage:true});await page.locator('[data-mode="2d"]').click();await page.locator('[data-side=front]').click();await page.screenshot({path:'test-results/builder/design.png',fullPage:true});
 await page.reload();await expect(page.locator('[data-brand=brand]')).toHaveValue('NORDWERK');await page.locator('[data-next]').click();await expect(page.locator('#build-csv')).toBeAttached();
 const rows=[{company:'Nordlicht',first_name:'Anna',last_name:'Muster',salutation:'Hallo Anna,',street:'Musterweg 1',postal_code:'01234',city:'Berlin',country:'Deutschland',chatbot_url:'https://example.org/anna'},{company:'Hafenblick',first_name:'Max',last_name:'Test',salutation:'Hallo Max,',street:'Teststraße 2',postal_code:'20095',city:'Hamburg',country:'Deutschland',chatbot_url:'https://example.org/max'}];await writeFile('test-results/builder/contacts.csv',csvString(rows,Object.keys(rows[0])));await page.locator('#build-csv').setInputFiles('test-results/builder/contacts.csv');await expect(page.locator('#csv-confirm')).toBeEnabled();await page.locator('#csv-confirm').click();await expect(page.locator('.build-upload')).toContainText('2 Kontakte');await page.locator('#build-person').selectOption('1');await page.screenshot({path:'test-results/builder/personalization.png',fullPage:true});await page.locator('[data-next]').click();await expect(page.locator('[data-submit]')).toBeEnabled();await page.locator('[data-submit]').click();await expect(page.locator('#build-error')).toContainText('Bestätige');await page.locator('#build-confirm').check();await page.locator('[data-submit]').click();await expect(page.locator('#auth-dialog')).toBeVisible();
 const email='builder-'+Date.now()+'@example.org';await page.locator('#auth-form [name=company]').fill('Nordwerk Test');await page.locator('#auth-form [name=name]').fill('Anna Test');await page.locator('#auth-form [name=email]').fill(email);await page.locator('#auth-form [name=password]').fill('builder-safe-password-123');await page.locator('#auth-form button').click();await expect(page).toHaveURL(/tab=overview/);await expect(page.locator('.tracking-status')).toContainText('Neu');await expect(page.locator('h1')).toHaveText('Nordwerk · September');
 await page.locator('.sidebar [data-view=analytics]').click();await page.getByRole('button',{name:'Kampagnen-Links aktivieren',exact:true}).click();await page.locator('#confirm-dialog button[value=yes]').click();await expect(page.locator('.tracking-status')).toContainText('2 Tracking-Links aktiv');
 const campaigns=await page.evaluate(async()=>await(await fetch('/api/campaigns')).json());const c=campaigns.campaigns.find(c=>c.project.name==='Nordwerk · September');assert.equal(c.project.recipients.length,2);assert.equal(c.meta.builder.step,3);assert.equal(c.meta.status,'requested');await context.request.get(c.project.recipients[0].chatbot_url);await context.request.get(c.project.recipients[0].chatbot_url);await page.getByRole('button',{name:'Aktualisieren ↻',exact:true}).click();await expect(page.locator('.metric').filter({hasText:'QR-Aufrufe'}).locator('strong')).toHaveText('2');await expect(page.locator('.scan-chart')).toBeVisible();await page.screenshot({path:'test-results/builder/tracking.png',fullPage:true});
 await page.locator('.campaign-mode [data-view=build]').click();await page.locator('[data-step="1"]').click();await page.getByRole('link',{name:'Details im Editor bearbeiten ↗'}).click();await expect(page.locator('#workspace-link')).toHaveText('Zurück zur Kampagne');await page.locator('#workspace-link').click();await expect(page).toHaveURL(/tab=build.*step=1/);await expect(page.locator('[data-brand=brand]')).toHaveValue('NORDWERK');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/builder/mobile-design.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('[data-step="0"]').click();await page.screenshot({path:'test-results/builder/mobile-layouts.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 assert.deepEqual(errors,[]);console.log('Guided guest draft, ten layouts, branding, 2D/3D, persistence, CSV, checked handoff, account adoption, real QR metrics, editor return and mobile passed.');
}catch(e){await page.screenshot({path:'test-results/builder/failure.png',fullPage:true});console.error(errors);throw e;}finally{await browser.close();}
