import {chromium,expect} from '@playwright/test';
import {build} from 'esbuild';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import jsQR from 'jsqr';
import {PDFDocument} from 'pdf-lib';
await mkdir('test-results',{recursive:true});await build({stdin:{contents:"export {renderCanvas} from './studio/src/render.js';",resolveDir:process.cwd()},outfile:'test-results/card-audit.mjs',bundle:true,format:'esm'});
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const root='http://127.0.0.1:4177';
const csv='Kontakt;Link zur Terminbuchung;Organisation;Einstieg;Postcode\nLena;https://example.org/lena;Atelier Test;Eine Idee für eure Agentur.;01067\nTom;;Digital Test;Wir möchten euch kennenlernen.;01068';
async function upload(text=csv){await page.locator('#csv-file').setInputFiles({name:'kontakte.csv',mimeType:'text/csv',buffer:Buffer.from(text)});await expect(page.locator('#csv-import-dialog')).toBeVisible();}
async function project(){const event=page.waitForEvent('download');await page.locator('#project-export').click();return JSON.parse(await readFile(await(await event).path(),'utf8'));}
try{
 await page.goto(root+'/fuer/money-making-sprint/');await expect(page.locator('#client-stage')).toHaveAttribute('aria-busy','false');
 const images=[];for(let i=0;i<3;i++){await page.locator(`[data-client-person="${i}"]`).click();await expect(page.locator('#client-status')).toContainText(['Anna','Jonas','Sarah'][i]);assert.equal(await page.locator('#client-request [name=audience]').evaluate(s=>s.selectedIndex),i);await expect(page.locator('#client-stage')).toHaveAttribute('aria-busy','false');images.push(await page.locator('#client-front').evaluate(c=>c.toDataURL()));const pixels=await page.locator('#client-back').evaluate(c=>({data:Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}));assert.equal(new URL(jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height).data).searchParams.get('utm_content'),'demo_'+(i+1));}
 assert.equal(new Set(images).size,3);await page.locator('[data-view=flat]').click();await page.locator('#client-flat').screenshot({path:'test-results/mms-new-spread.png'});
 await page.locator('.client-customize summary').click();await page.locator('#client-name').fill('Mara');await page.locator('#client-company').fill('Meine Agentur');await page.locator('#client-note').fill('Mara, eure Content-Ideen haben Potenzial. Lass uns über eure Kundengewinnung sprechen.');await expect(page.locator('#client-status')).toContainText('Meine Agentur');
 const pdfEvent=page.waitForEvent('download');await page.locator('#client-pdf').click();assert.equal((await PDFDocument.load(await readFile(await(await pdfEvent).path()))).getPageCount(),2);
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'MMS overflow '+width);await page.screenshot({path:`test-results/mms-new-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:1440,height:1050});await page.locator('#client-studio').click();await expect(page.locator('#example-use')).toBeVisible();const handoff=await project();assert.equal(handoff.recipients[0].first_name,'Mara');assert.equal(handoff.recipients[0].company,'Meine Agentur');assert.match(handoff.recipients[0].personal_note,/Content-Ideen/);
 await page.locator('#example-use').click();await page.locator('[data-tab=recipients]').click();await expect(page.locator('#csv-drop-zone')).toBeVisible();await page.screenshot({path:'test-results/csv-empty.png',fullPage:true});
 await upload();await page.locator('[data-csv-close]').first().click();assert.equal((await project()).recipients.length,0);
 await upload();await page.locator('[data-csv-map=first_name]').selectOption('0');await page.locator('[data-csv-map=chatbot_url]').selectOption('1');await page.locator('[data-csv-map=personal_note]').selectOption('3');await page.locator('#csv-common-url').fill('https://example.org/general');await page.locator('.csv-extra summary').click();await page.locator('[data-csv-map=postal_code]').selectOption('4');await expect(page.locator('#csv-review')).toContainText('Hallo Lena,');await expect(page.locator('#csv-review')).toContainText('Eine Idee für eure Agentur.');
 await page.locator('#csv-import-dialog').screenshot({path:'test-results/csv-mapping.png'});await page.setViewportSize({width:390,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/csv-mapping-mobile.png'});await page.setViewportSize({width:1440,height:1050});
 await page.locator('#csv-confirm').click();await expect(page.locator('#data-count')).toHaveText('2 Empfänger');let c=await project();assert.equal(c.recipients[0].postal_code,'01067');assert.equal(c.recipients[0].salutation,'Hallo Lena,');assert.equal(c.recipients[0].chatbot_url,'https://example.org/lena');assert.equal(c.recipients[1].chatbot_url,'https://example.org/general');assert.equal(c.sample,false);
 await upload('Firma;Vorname;Link\nDritte Firma;Ada;https://example.org/ada');await page.locator('#csv-confirm').click();assert.equal((await project()).recipients.length,3);
 await upload('Firma;Vorname;Link\nErsetzt;Jo;https://example.org/jo');await page.locator('[name=csv-import-mode][value=replace]').check();await page.locator('#csv-confirm').click();assert.equal((await project()).recipients.length,1);
 await upload('Firma;Vorname\n;Ohne Firma');await expect(page.locator('#csv-confirm')).toBeDisabled();await expect(page.locator('#csv-import-error')).toContainText('Firmenname');await page.locator('[data-csv-close]').first().click();assert.equal((await project()).recipients.length,1);
 await expect(page.locator('#save-state')).toContainText('Lokal gespeichert');await page.reload();await page.locator('[data-tab=recipients]').click();await expect(page.locator('[data-key=company]')).toHaveValue('Ersetzt');
 await page.locator('#contact-columns').check();await page.locator('[data-key=salutation]').fill('Hey Jo,');await page.locator('[data-key=first_name]').fill('Jona');assert.equal((await project()).recipients[0].salutation,'Hey Jona,');
 const fits=await page.evaluate(async()=>{const {createClientCampaign}=await import('/studio/src/client-campaigns.js'),{renderCanvas}=await import('/test-results/card-audit.mjs');const c=createClientCampaign('money-making-sprint'),out=[];for(const r of c.recipients)for(const side of ['front','back'])out.push(...await renderCanvas(document.createElement('canvas'),c,side,r));return out;});assert.deepEqual(fits,[]);assert.deepEqual(errors,[]);
 console.log('CSV + MMS passed: three tailored segments and decoded QR targets, PDF, customized studio handoff, mapping, preview, cancellation, append/replace, validation, postal codes, shared URLs, persistence and responsive layouts.');
}finally{await browser.close();}
