import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:4183';await mkdir('test-results/fold',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 const auth=await context.request.post(origin+'/api/auth/admin',{headers:{origin},data:{password:process.env.TEST_ADMIN_PASSWORD||'local-sales-test-only'}});assert.equal(auth.status(),200);
 const records=(await (await context.request.get(origin+'/api/library/designs')).json()).items,record=records.find(d=>d.project.format==='selfmailer-dl-4'&&d.project.templateId==='reha-sleep');assert.ok(record);
 await page.goto(origin+'/studio/?design='+record.id+'&view=preview');await expect(page.locator('#three-d-stage')).toBeVisible();
 const stage=page.locator('#three-d-stage');await expect(stage.locator('[data-fold-face=cover]')).toHaveJSProperty('width',1050);await expect(stage).toHaveAttribute('data-fold','0');
 const matching=await page.evaluate(()=>{const out=document.querySelector('#three-d-front'),inside=document.querySelector('#three-d-back');return [['cover',out,1],['postal',out,0],['inside-top',inside,0],['inside-bottom',inside,1]].every(([face,src,lower])=>{const expected=document.createElement('canvas'),actual=document.querySelector(`[data-fold-face="${face}"]`);expected.width=src.width;expected.height=src.height/2;expected.getContext('2d').drawImage(src,0,lower*src.height/2,src.width,src.height/2,0,0,expected.width,expected.height);return expected.toDataURL()===actual.toDataURL();});});assert.equal(matching,true);
 await page.locator('#three-d-view').screenshot({path:'test-results/fold/desktop-closed.png'});await page.locator('[data-fold-toggle]').click();await expect(stage).toHaveAttribute('data-fold','100');await page.locator('#three-d-view').screenshot({path:'test-results/fold/desktop-open.png'});await page.locator('.fold-range input').fill('50');await page.locator('#three-d-view').screenshot({path:'test-results/fold/desktop-half.png'});
 await page.locator('[data-fold-play]').click();await expect(stage).toHaveAttribute('data-loop','playing');await page.waitForFunction(()=>Number(document.querySelector('#three-d-stage').dataset.fold)>20);await page.locator('[data-fold-play]').click();await expect(stage).toHaveAttribute('data-loop','paused');await page.locator('[data-fold-play]').click();await page.locator('#preview-mode-2d').click();await expect(page.locator('.fold-controls')).toBeHidden();await expect(stage).toHaveAttribute('data-loop','paused');await page.locator('#preview-mode-3d').click();await page.locator('#three-d-reset').click();
 await page.setViewportSize({width:390,height:844});await page.locator('[data-fold-toggle]').click();await expect(stage).toHaveAttribute('data-fold','100');await stage.scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#three-d-view').screenshot({path:'test-results/fold/mobile-open.png'});
 const bounds=await stage.boundingBox();for(const leaf of await stage.locator('.fold-leaf').all()){const b=await leaf.boundingBox();assert.ok(b.x>=bounds.x-1&&b.x+b.width<=bounds.x+bounds.width+1&&b.y>=bounds.y-1&&b.y+b.height<=bounds.y+bounds.height+1,'Unfolded leaf fits mobile stage');}
 const before=await stage.locator('.mailing-3d-card').getAttribute('style');await page.mouse.move(bounds.x+bounds.width*.5,bounds.y+bounds.height*.6);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.7,bounds.y+bounds.height*.7,{steps:8});await page.mouse.up();assert.notEqual(await stage.locator('.mailing-3d-card').getAttribute('style'),before);
 await page.setViewportSize({width:1440,height:1100});const campaigns=(await (await context.request.get(origin+'/api/campaigns')).json()).campaigns,c=campaigns.find(c=>c.project.format==='selfmailer-dl-4');await page.goto(origin+'/konto/?tab=build&id='+c.id+'&step=1');await page.locator('[data-mode="3d"]').click();await expect(page.locator('.fold-flap')).toBeVisible();await page.locator('[data-fold-toggle]').click();await expect(page.locator('.build-stage')).toHaveAttribute('data-fold','100');await page.screenshot({path:'test-results/fold/builder.png'});
 assert.deepEqual(errors,[]);console.log('Passed: four textures, folding, animation pause, hidden-view stop, mobile fit, rotation and builder.');
}catch(e){await page.screenshot({path:'test-results/fold/failure.png'});console.log('Browser errors:',errors);throw e;}finally{await browser.close();}
