import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1080},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4177/');await expect(page.locator('#hero-stage')).toHaveAttribute('aria-busy','false');
 await expect(page.locator('[data-preview-example]')).toHaveCount(3);await expect(page.locator('#example-dialog')).not.toBeVisible();for(const id of ['nutzen','wirkung','leistung','fragen'])await expect(page.locator('#'+id)).not.toHaveAttribute('open','');await expect(page.locator('.journey-steps li')).toHaveCount(3);await expect(page.locator('.value-always')).toContainText('Always');await expect(page.locator('#wirkung')).toContainText('keine gemessenen Ergebnisse');
 await expect(page.locator('#impact-visitors')).toHaveText('50');await expect(page.locator('#impact-leads')).toHaveText('10');await expect(page.locator('#impact-total')).toHaveText('1 %');
 await page.locator('#wirkung>summary').click();await page.locator('#impact-mailings').focus();await page.keyboard.press('Home');await expect(page.locator('#impact-mailings-value')).toHaveText('100');await expect(page.locator('#impact-visitors')).toHaveText('5');await expect(page.locator('#impact-leads')).toHaveText('1');
 await page.locator('#impact-scan').focus();await page.keyboard.press('Home');await expect(page.locator('#impact-leads')).toHaveText('0');await expect(page.locator('#impact-total')).toHaveText('0 %');await page.keyboard.press('ArrowRight');await expect(page.locator('#impact-visitors')).toHaveText('1');await expect(page.locator('#impact-leads')).toHaveText('0');await expect(page.locator('#impact-total')).toHaveText('0,1 %');
 await page.locator('#impact-conversion').focus();await page.keyboard.press('End');await expect(page.locator('#impact-leads')).toHaveText('1');await expect(page.locator('#impact-total')).toHaveText('0,5 %');
 await page.locator('.measurement-note summary').click();await expect(page.locator('.measurement-note p')).toBeVisible();await expect(page.locator('.measurement-note p')).toContainText('keine Scans oder Conversions');await page.locator('.measurement-note summary').click();
 // Reset to the illustrative defaults using keyboard controls.
 await page.locator('#impact-mailings').focus();await page.keyboard.press('End');await page.locator('#impact-scan').focus();for(let i=0;i<9;i++)await page.keyboard.press('ArrowRight');await page.locator('#impact-conversion').focus();await page.keyboard.press('Home');for(let i=0;i<4;i++)await page.keyboard.press('ArrowRight');
 await page.locator('#wirkung>summary').click();for(const width of [1512,390]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await page.screenshot({path:`test-results/homepage-simple-${width}.png`,fullPage:true});}await page.locator('#wirkung>summary').click();await page.locator('#nutzen>summary').click();for(const width of [1512,1024,768,390]){await page.setViewportSize({width,height:1080});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow '+width);for(const id of ['ablauf','nutzen','wirkung'])await page.locator('#'+id).screenshot({path:`test-results/homepage-${id}-${width}.png`});}
 await page.locator('[data-preview-example="chattastic"]').click();await expect(page.locator('#example-dialog')).toBeVisible();await page.locator('#gallery-open').scrollIntoViewIfNeeded();await page.locator('.promotion-tabs [data-promotion="morgen"]').click();await expect(page.locator('#gallery-open')).toHaveAttribute('href','studio/?example=morgen');
 await page.keyboard.press('Escape');await expect(page.locator('#example-dialog')).toBeHidden();await expect(page.locator('[data-preview-example="chattastic"]')).toBeFocused();await page.locator('[data-preview-example="raumwerk"]').click();await expect(page.locator('#gallery-open')).toHaveAttribute('href','studio/?example=raumwerk');await page.locator('#example-close').click();await page.goto('http://127.0.0.1:4177/#wirkung');await expect(page.locator('#wirkung')).toHaveAttribute('open','');await page.locator('[data-start-campaign]').click();await expect(page.locator('#tutorial-view')).toBeVisible();assert.deepEqual(errors,[]);
 console.log('Homepage passed: distinct journey and benefits, scenario arithmetic, zero/fractional rates, keyboard input, honest measurement labels, four responsive widths, gallery and tutorial entry.');
}finally{await browser.close();}
