import {chromium,expect} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {unzipSync,strFromU8} from 'fflate';
import {PDFDocument} from 'pdf-lib';
import assert from 'node:assert/strict';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1080},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:4177';
async function download(selector){const event=page.waitForEvent('download');await page.locator(selector).click();const d=await event;return await readFile(await d.path());}
async function project(){return JSON.parse((await download('#project-export')).toString());}
async function shot(name){await page.waitForTimeout(180);await page.locator('#toast').evaluateAll(nodes=>nodes.forEach(n=>n.classList.remove('show')));await page.screenshot({path:`test-results/product-${name}.png`,fullPage:true});}
try{
 await page.goto(base);await page.locator('#demo-company').fill('Hotel Nordlicht');await expect(page.locator('#hero-front')).toHaveAttribute('aria-label','Vorderseite für Hotel Nordlicht');
 const original=await page.locator('#hero-card').getAttribute('style');await page.locator('#hero-flip').click();assert.notEqual(await page.locator('#hero-card').getAttribute('style'),original);await expect(page.locator('#hero-flip')).toContainText('Vorderseite');await page.locator('#hero-reset').click();
 await shot('homepage');
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Home overflow '+width);if(width===390)await shot('homepage-mobile');}
 await page.setViewportSize({width:1512,height:1080});await page.goto(base+'/studio/');await expect(page.locator('#dashboard-empty')).toBeVisible();await expect(page.locator('.dashboard-card')).toHaveCount(0);await shot('dashboard-empty');
 await page.locator('[data-dashboard-template="dialog"]').click();await expect(page.locator('#setup-view')).toBeVisible();let c=await project();assert.equal(c.recipients.length,0);assert.equal(c.sample,false);assert.ok(c.sides.front.fields.every(f=>['text','shape'].includes(f.type)));assert.ok(c.sides.back.fields.some(f=>f.type==='qr'));
 await page.locator('[data-guide-action="next"]').click();await page.locator('[data-guide-action="next"]').click();await page.locator('[data-guide-action="edit-front"]').click();await page.locator('[data-layer]').first().click();await page.locator('#field-text').fill('NORDLICHT STUDIO');
 await page.locator('#add-shape').click();c=await project();const shape=c.sides.front.fields.at(-1);assert.equal(shape.type,'shape');await page.locator('#layer-back').click();c=await project();assert.equal(c.sides.front.fields.at(-2).id,shape.id);await page.locator('#layer-front').click();await page.locator('#delete-field').click();
 const logo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=150;const x=c.getContext('2d');x.fillStyle='#e2ff54';x.fillRect(0,0,250,150);return c.toDataURL().split(',')[1];});
 await page.locator('#image-file').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:Buffer.from(logo,'base64')});await expect(page.locator('#inspector h3')).toContainText('Logo / Bild');c=await project();assert.equal(c.sides.front.fields.at(-1).type,'image');assert.match(c.sides.front.fields.at(-1).data,/^data:image\/png/);await page.locator('#field-x').fill('115');await page.locator('#field-x').press('Tab');await shot('editor');
 await page.locator('[data-tab="recipients"]').click();
 await page.locator('#csv-file').setInputFiles({name:'kontakte.csv',mimeType:'text/csv',buffer:Buffer.from('Firma;Vorname;Ansprache;Link;Straße;PLZ;Ort;Land\nHotel Nordlicht;Anna;Hallo Anna,;https://example.org/anna;Hafenweg 4;20095;Hamburg;Deutschland\nHotel Hafenblick;Ben;Hallo Ben,;https://example.org/ben;Kai 8;20457;Hamburg;Deutschland')});await page.locator('[data-result="replace"]').click();await expect(page.locator('#recipient-count')).toHaveText('2');await expect(page.locator('[data-key="street"]').first()).toHaveValue('Hafenweg 4');
 await page.locator('#recipient-search').fill('Hafenblick');await expect(page.locator('[data-recipient-index="0"]')).toBeHidden();await expect(page.locator('#recipient-filter-count')).toHaveText('1 von 2 Empfängern');await page.locator('#recipient-search').fill('');
 await page.locator('#open-preview').click();await page.locator('#audit-all').click();await expect(page.locator('#audit-results')).toContainText('Alle Empfänger geprüft');await shot('proof');
 await page.locator('#handoff-export').click();const zipData=await download('[data-result="export"]');const files=unzipSync(zipData);assert.equal(Object.keys(files).length,5);const pdf=await PDFDocument.load(files['mailings-ansicht.pdf']);assert.equal(pdf.getPageCount(),4);assert.ok(Math.abs(pdf.getPage(0).getWidth()-210*72/25.4)<.01);const report=JSON.parse(strFromU8(files['uebergabe.json']));assert.equal(report.pages[1].back,4);assert.equal(report.issues.filter(i=>i.level==='error').length,0);assert.match(strFromU8(files['empfaenger.csv']),/Hafenweg 4/);const portable=JSON.parse(strFromU8(files['kampagne.kontaktstoff.json']));assert.equal(portable.sides.front.fields.at(-1).type,'image');
 // A nonselected recipient can overflow; the global audit must still catch it.
 await page.locator('[data-tab="design"]').click();await page.locator('[data-side="back"]').click();const salutation=portable.sides.back.fields.find(f=>f.text==='{{salutation}}');await page.locator(`[data-layer="${salutation.id}"]`).click();await page.locator('#field-fit').uncheck();await page.locator('[data-tab="recipients"]').click();await page.locator('[data-row="1"][data-key="salutation"]').fill('X'.repeat(500));await page.locator('#open-preview').click();await page.locator('#preview-recipient').selectOption('0');await page.locator('#audit-all').click();await expect(page.locator('#audit-results')).toContainText('Hotel Hafenblick');await expect(page.locator('#audit-results')).toContainText('passt nicht');await page.locator('[data-audit-recipient]').first().click();await expect(page.locator('#active-recipient')).toHaveValue('1');await expect(page.locator('#audit-results')).toBeHidden();
 await page.locator('[data-tab="recipients"]').click();await page.locator('[data-row="1"][data-key="salutation"]').fill('Hallo Ben,');
 await page.locator('#breadcrumb-campaigns').click();await expect(page.locator('.dashboard-card')).toHaveCount(1);await page.locator('[data-dashboard-copy]').click();await expect(page.locator('.dashboard-card')).toHaveCount(2);await shot('dashboard');await page.locator('#campaign-search').fill('Kopie');await expect(page.locator('.dashboard-card:visible')).toHaveCount(1);await page.locator('[data-dashboard-delete]:visible').click();await page.locator('[data-result="ok"]').click();await expect(page.locator('.dashboard-card')).toHaveCount(1);await page.reload();await expect(page.locator('#dashboard-view')).toBeVisible();await expect(page.locator('.dashboard-card')).toHaveCount(1);
 // Delete the active campaign. A delayed autosave must not recreate it.
 await page.locator('[data-dashboard-delete]').click();await page.locator('[data-result="ok"]').click();await expect(page.locator('#dashboard-empty')).toBeVisible();await page.reload();await expect(page.locator('.dashboard-card')).toHaveCount(0);
 await page.locator('[data-dashboard-import]').click();await page.locator('#project-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(portable))});await expect(page.locator('#rename-campaign')).toContainText('Import');c=await project();assert.equal(c.recipients.length,2);assert.equal(c.sides.front.fields.at(-1).type,'image');
 await page.locator('#breadcrumb-campaigns').click();for(const width of [1024,768,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Dashboard overflow '+width);if(width===390)await shot('dashboard-mobile');}
 await page.locator('.campaign-card-content [data-dashboard-open]').first().click();await page.locator('.guide-step-picker summary').click();await page.locator('[data-guide-step="5"]').click();await page.locator('[data-guide-action="finish"]').click();await expect(page.locator('#handoff-export')).toBeVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('handoff-mobile');
 assert.deepEqual(errors,[]);console.log('Product tests passed: homepage interactions, mobile layout, empty dashboard, editable templates, layers, logo upload, address aliases, recipient search, global audit, 4-page ZIP handoff, nonselected overflow, duplication, deletion without resurrection, portable import and responsive dashboard.');
}finally{await browser.close();}
