import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const origin='http://127.0.0.1:4183';await mkdir('test-results/proposals',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),admin=await browser.newContext({viewport:{width:1440,height:1000}}),guest=await browser.newContext({viewport:{width:1440,height:1000}}),page=await admin.newPage(),publicPage=await guest.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));publicPage.on('pageerror',e=>errors.push(e.message));
try{
 const login=await admin.request.post(origin+'/api/auth/admin',{headers:{origin},data:{password:'local-sales-test-only'}});assert.equal(login.status(),200);
 await page.goto(origin+'/konto/?tab=sales-links');await expect(page.locator('#proposal-generate')).toBeVisible();await page.locator('#mms-example').click();await expect(page.locator('#proposal-canvas')).toHaveJSProperty('width',1050);
 await page.locator('[name=loom]').fill('https://www.loom.com/share/1234567890abcdef1234567890abcdef');await page.locator('[name=cardHeadline]').fill('wer holt den\nnächsten Kunden\nfür euch rein?');await page.locator('#proposal-save').click();await expect(page.locator('#proposal-save-state')).toContainText('Entwurf gespeichert');
 const popupPromise=page.waitForEvent('popup');await page.locator('#proposal-preview').click();const preview=await popupPromise;await expect(preview.locator('#proposal-hero-card')).toHaveJSProperty('width',840);await expect(preview.locator('#proposal-inquiry [type=submit]')).toBeDisabled();await guest.newPage().then(async p=>{await p.goto(preview.url());await expect(p.locator('h1')).toContainText('nicht verfügbar');await p.close();});await preview.close();
 await page.locator('#proposal-publish').click();await expect(page.locator('#proposal-link')).toBeVisible();const link=await page.locator('#proposal-link').inputValue();await publicPage.goto(link);await expect(publicPage.locator('#example-front')).toHaveJSProperty('width',1050);await expect(publicPage.locator('h1')).toContainText('Euer nächstes Gespräch');await expect(publicPage.locator('.proposal-loom')).toBeVisible();await publicPage.screenshot({path:'test-results/proposals/desktop.png',fullPage:true});await publicPage.locator('[data-side=back]').click();await publicPage.locator('[data-mode="2d"]').click();await expect(publicPage.locator('#sales-flat')).toBeVisible();await publicPage.locator('#proposal-zoom').click();await expect(publicPage.locator('#proposal-zoom-dialog')).toBeVisible();await publicPage.locator('#proposal-zoom-range').fill('150');await publicPage.locator('#proposal-zoom-close').click();
 await page.locator('[name=headline]').fill('Eine neue Idee für eure Wunschkunden.');await page.locator('#proposal-save').click();await expect(page.locator('#proposal-save-state')).toContainText('Link aktiv');await publicPage.reload();await expect(publicPage.locator('h1')).toContainText('Euer nächstes Gespräch');await page.locator('#proposal-publish').click();await expect(page.locator('#proposal-save-state')).toContainText('Link aktiv');assert.equal(await page.locator('#proposal-link').inputValue(),link);await publicPage.reload();await expect(publicPage.locator('h1')).toContainText('Eine neue Idee');
 await publicPage.locator('[name=name]').fill('Test Interessent');await publicPage.locator('[name=email]').fill('proposal-'+Date.now()+'@example.org');await publicPage.route('**/api/sales-inquiries',r=>r.abort(),{times:1});await publicPage.locator('#proposal-inquiry [type=submit]').click();await expect(publicPage.locator('#proposal-error')).toBeVisible();await publicPage.locator('#proposal-inquiry [type=submit]').click();await expect(publicPage.locator('#proposal-success')).toBeVisible();
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/proposals/editor-mobile.png',fullPage:true});await publicPage.setViewportSize({width:390,height:844});await publicPage.reload();await expect(publicPage.locator('#example-front')).toHaveJSProperty('width',1050);assert.ok(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await publicPage.screenshot({path:'test-results/proposals/mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-preview-side=back]').click();await page.screenshot({path:'test-results/proposals/editor.png',fullPage:true});await page.goto(origin+'/konto/?tab=sales-inquiries');await page.locator('[data-lead]').first().click();await expect(page.locator('.sales-detail')).toContainText('Money Making Sprint');await expect(page.locator('.sales-detail')).toContainText('Test Interessent');
 await page.goto(origin+'/konto/?tab=sales-links');await page.locator('[data-proposal]').first().click();page.once('dialog',d=>d.accept());await page.locator('#proposal-disable').click();await expect(page.locator('#proposal-link')).toHaveCount(0);await publicPage.reload();await expect(publicPage.locator('h1')).toContainText('nicht verfügbar');
 assert.deepEqual(errors,[]);console.log('Personal proposals: edit, draft preview protection, publish stable link, separate drafts, Loom, 2D/3D/zoom, inquiry attribution, disable, mobile and no browser errors passed.');
}catch(e){await page.screenshot({path:'test-results/proposals/failure.png',fullPage:true});console.log(errors);throw e;}finally{await browser.close();}
