import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const origin='http://127.0.0.1:4183';await mkdir('test-results/sales',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin+'/mailings/');await expect(page.locator('#hero-card')).toHaveJSProperty('width',840);await expect(page.locator('#example-front')).toHaveJSProperty('width',1050);await expect(page.locator('#loom-note')).toBeHidden();await page.screenshot({path:'test-results/sales/desktop.png',fullPage:true});
 for(const kind of ['recovery','reactivation','b2b']){await page.locator('[data-case='+kind+']').click();await expect(page.locator('#sales-inquiry [name=useCase]')).toHaveValue(kind);await page.locator('[data-side=back]').click();await page.locator('[data-mode="2d"]').click();await expect(page.locator('#sales-flat')).toBeVisible();await expect(page.locator('#example-flat')).toHaveJSProperty('width',1050);await page.locator('[data-mode="3d"]').click();}
 await page.locator('#sales-inquiry [name=name]').fill('Anna Vertriebtest');await page.locator('#sales-inquiry [name=company]').fill('Nordlicht Test '+Date.now());await page.locator('#sales-inquiry [name=email]').fill('browser-'+Date.now()+'@example.org');await page.locator('#sales-inquiry [name=message]').fill('Wir möchten einen Pilot mit 100 Kontakten besprechen.');
 await page.route('**/api/sales-inquiries',route=>route.abort(),{times:1});await page.locator('#sales-inquiry [type=submit]').click();await expect(page.locator('#form-error')).toBeVisible();await expect(page.locator('[name=name]')).toHaveValue('Anna Vertriebtest');await page.locator('#sales-inquiry [type=submit]').click();await expect(page.locator('#form-success')).toBeVisible();
 const admin=await browser.newContext({viewport:{width:1440,height:1000}}),adminPage=await admin.newPage();adminPage.on('pageerror',e=>errors.push(e.message));const login=await admin.request.post(origin+'/api/auth/admin',{headers:{origin},data:{password:'local-sales-test-only'}});assert.equal(login.status(),200);
 await adminPage.goto(origin+'/konto/?tab=sales-inquiries');await adminPage.locator('[data-lead]').first().click();await expect(adminPage.locator('.sales-detail')).toContainText('Anna Vertriebtest');await adminPage.locator('[name=status]').selectOption('qualified');await adminPage.locator('[name=note]').fill('Pilotumfang abstimmen');await adminPage.locator('#lead-status-form button').click();await expect(adminPage.locator('#notice')).toContainText('aktualisiert');await adminPage.reload();await adminPage.locator('[data-lead]').first().click();await expect(adminPage.locator('[name=note]')).toHaveValue('Pilotumfang abstimmen');await adminPage.screenshot({path:'test-results/sales/inquiry.png',fullPage:true});
 const link=origin+'/mailings/?fuer=Nordlicht%20%26%20Partner&ziel=recovery&video=https%3A%2F%2Fwww.loom.com%2Fshare%2F1234567890abcdef1234567890abcdef';
 await adminPage.goto(origin+'/konto/?tab=sales-links');await expect(adminPage.locator('#proposal-generate')).toBeVisible();
 await page.goto(link);await expect(page.locator('#personal-intro')).toContainText('Nordlicht & Partner');await expect(page.locator('#loom-link')).toHaveAttribute('href','https://www.loom.com/share/1234567890abcdef1234567890abcdef');await expect(page.locator('#sales-inquiry [name=useCase]')).toHaveValue('recovery');
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/sales/mobile.png',fullPage:true});await page.locator('[data-side=back]').click();await page.locator('[data-mode="2d"]').click();await page.locator('.form-note [data-privacy]').click();await expect(page.locator('#privacy-dialog')).toBeVisible();await page.locator('.dialog-close').click();
 await adminPage.setViewportSize({width:390,height:844});assert.ok(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await adminPage.screenshot({path:'test-results/sales/link-mobile.png',fullPage:true});
 await page.goto(origin+'/mailings/?fuer='+encodeURIComponent('<img src=x onerror=alert(1)>')+'&video=javascript:alert(1)');await expect(page.locator('#personal-intro img')).toHaveCount(0);await expect(page.locator('#loom-note')).toBeHidden();
 await page.goto(origin+'/?info=privacy');await expect(page.locator('#info-dialog')).toBeVisible();await expect(page.locator('#info-body')).toContainText('Verkaufsseite');
 assert.deepEqual(errors,[]);console.log('Sales page, 3 campaign examples, 2D/3D, personal Loom links, retry-safe inquiry, operator inbox, status persistence, privacy links and mobile passed.');await admin.close();
}catch(e){await page.screenshot({path:'test-results/sales/failure.png',fullPage:true});console.error(errors);throw e;}finally{await browser.close();}
