import {chromium,expect} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {PDFDocument} from 'pdf-lib';
import assert from 'node:assert/strict';
import jsQR from 'jsqr';
import {createExampleCampaign} from '../studio/src/templates.js';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1080},acceptDownloads:true,reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function project(){const event=page.waitForEvent('download');await page.locator('#project-export').click();return JSON.parse(await readFile(await(await event).path(),'utf8'));}
async function shot(name){await page.locator('#toast').evaluate(e=>e.classList.remove('show'));await page.screenshot({path:'test-results/focus-'+name+'.png',fullPage:true});}
async function next(){await page.locator('[data-tutorial-action="next"]').click();}
try{
 await page.goto('http://127.0.0.1:4177/studio/?start=blank');await page.locator('#setup-name').fill('Entwurf bleibt erhalten');await page.locator('.focus-details').filter({hasText:'Ich möchte zuerst'}).locator('summary').click();await page.locator('[data-guide-action="tutorial"]').click();
 await expect(page.locator('#tutorial-title')).toHaveText('Fangen wir mit einer fertigen Karte an.');await expect(page.locator('.steps')).toBeHidden();await expect(page.locator('.campaign-heading')).toBeHidden();await expect(page.locator('#setup-tab')).toBeHidden();await expect(page.locator('#tutorial-view .primary:visible')).toHaveCount(1);await page.waitForFunction(()=>document.querySelector('#tutorial-front').width>500);await shot('start');
 await next();await page.locator('[data-tutorial-data="first_name"]').fill('Mia');await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Mia,');await page.locator('[data-tutorial-data="company"]').fill('Mias Beispielstudio');await page.waitForTimeout(450);await page.reload();await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Mia,');assert.equal((await project()).recipients[0].company,'Mias Beispielstudio');await shot('name');
 await page.locator('.focus-details summary').click();await page.locator('#tutorial-text').fill('{{unbekannt}}');await expect(page.locator('#tutorial-text-help')).toContainText('fehlt ein Wert');await page.locator('[data-tutorial-action="reset-text"]').click();await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Mia,');
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('name-'+width);}await page.setViewportSize({width:1512,height:1080});
 await next();await page.locator('#tutorial-url').fill('https://example.org/mia');await expect(page.locator('#tutorial-qr-status')).toContainText('genau den Link');await page.waitForFunction(()=>document.querySelector('#tutorial-qr').width===440);await page.waitForTimeout(200);const pixels=await page.locator('#tutorial-qr').evaluate(c=>({data:Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}));assert.equal(jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height).data,'https://example.org/mia');await page.locator('#tutorial-url').fill('kein-link');await expect(page.locator('#tutorial-qr-status')).toContainText('HTTP(S)');await page.locator('#tutorial-url').fill('https://example.org/mia');await shot('link');
 await next();await expect(page.locator('#tutorial-view .primary:visible')).toHaveCount(1);await page.locator('.focus-details summary').click();await page.locator('[data-tutorial-action="three-d"]').click();await expect(page.locator('#example-preview-note')).toBeHidden();await expect(page.locator('#setup-tab')).toBeHidden();await page.locator('#three-d-flip').click();await expect(page.locator('#three-d-stage')).toHaveAttribute('data-face','back');await page.locator('#back-to-tutorial').click();await expect(page.locator('#tutorial-title')).toContainText('eigenes Mailing');
 await page.locator('.focus-details summary').click();const pdfEvent=page.waitForEvent('download');await page.locator('[data-tutorial-action="pdf"]').click();assert.equal((await PDFDocument.load(await readFile(await(await pdfEvent).path()))).getPageCount(),2);
 const sample=await project();await page.locator('[data-tutorial-action="own"]').click();await expect(page.locator('#setup-view')).toBeVisible();await expect(page.locator('.focus-topline:visible')).toContainText('SCHRITT 1 VON 2');let own=await project();assert.notEqual(own.id,sample.id);assert.equal(own.sample,false);assert.equal(own.recipients.length,0);assert.ok(!own.tutorial);assert.deepEqual(own.sides.front,sample.sides.front);await expect(page.locator('#setup-view .primary:visible')).toHaveCount(1);await shot('own-contact');
 await page.locator('[name="company"]').fill('Echte Testfirma');await page.locator('[name="first_name"]').fill('Lea');await page.locator('[name="chatbot_url"]').fill('https://example.org/lea');await page.locator('#guide-recipient-form [type="submit"]').click();await expect(page.locator('.focus-topline:visible')).toContainText('SCHRITT 2 VON 2');await expect(page.locator('#setup-view .primary:visible')).toHaveCount(1);await page.locator('[data-guide-action="previous"]').click();await expect(page.locator('[name="company"]')).toHaveValue('Echte Testfirma');await page.locator('[name="company"]').fill('Meine Testfirma');await page.locator('#guide-recipient-form [type="submit"]').click();await page.locator('[data-guide-action="finish"]').click();await expect(page.locator('#preview-view')).toBeVisible();await expect(page.locator('#setup-tab')).toBeHidden();await expect(page.locator('#tutorial-return')).toBeHidden();own=await project();assert.equal(own.recipients.length,1);assert.equal(own.recipients[0].first_name,'Lea');await page.locator('#audit-all').click();await expect(page.locator('#audit-results')).toContainText('Alle Empfänger geprüft');
 await page.locator('#breadcrumb-campaigns').click();await expect(page.locator('.dashboard-card')).toHaveCount(3);await page.locator('.campaign-card-content [data-dashboard-open]').filter({hasText:'chattastic · Mein Mitmach-Tutorial'}).click();await page.locator('#start-tutorial').click();await page.locator('.focus-details summary').click();await page.locator('[data-tutorial-action="three-d"]').click();await expect(page.locator('#back-to-tutorial')).toBeVisible();await page.locator('#back-to-tutorial').click();
 // Old tutorial projects migrate in place, retaining edits but dropping the competing six-step guide.
 const old=createExampleCampaign(),field=old.sides.back.fields.find(f=>f.text==='{{salutation}}');field.text='Hallo {{first_name}},';old.tutorial={active:true,step:6,fieldId:field.id};old.recipients[0].first_name='Erhalten';
 await page.locator('#project-file').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});await expect(page.locator('#tutorial-return')).toBeVisible();await page.locator('#back-to-tutorial').click();await expect(page.locator('.focus-topline:visible')).toContainText('4 VON 4');const migrated=await project();assert.equal(migrated.tutorial.version,2);assert.equal(migrated.recipients[0].first_name,'Erhalten');assert.ok(!migrated.onboarding);await page.reload();await expect(page.locator('#tutorial-title')).toContainText('eigenes Mailing');
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('finish-'+width);}
 await page.locator('[data-tutorial-action="skip"]').click();await expect(page.locator('#design-view')).toBeVisible();assert.equal((await project()).recipients.length,0);
 assert.deepEqual(errors,[]);console.log('Focused tutorial passed: single primary action, no competing guide, live names and QR, 4 steps, PDF/3D, clean adoption into real campaign, first-recipient handoff, audit, old-project migration, persistence and mobile layouts.');
}finally{await browser.close();}
