import {chromium,expect} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {PDFDocument} from 'pdf-lib';
import assert from 'node:assert/strict';
import jsQR from 'jsqr';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1080},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function project(){const event=page.waitForEvent('download');await page.locator('#project-export').click();return JSON.parse(await readFile(await(await event).path(),'utf8'));}
async function step(i){await page.locator(`[data-tutorial-step="${i}"]`).click();await expect(page.locator('.tutorial-progress')).toContainText('SCHRITT '+(i+1));}
async function shot(name){await page.locator('#toast').evaluate(e=>e.classList.remove('show'));await page.screenshot({path:'test-results/tutorial-'+name+'.png',fullPage:true});}
try{
 await page.goto('http://127.0.0.1:4177/studio/?start=blank');await page.locator('#setup-name').fill('Entwurf bleibt erhalten');await page.locator('[data-guide-action="tutorial"]').click();await expect(page.locator('#tutorial-view')).toBeVisible();await expect(page.locator('#tutorial-title')).toHaveText('Wir bauen ein Mailing für Anna.');await expect(page.locator('.tutorial-contacts button')).toHaveCount(3);await shot('start');
 await step(1);await page.waitForFunction(()=>document.querySelector('#tutorial-back').width>500);await page.locator('[data-tutorial-action="design"]').click();await expect(page.locator('#tutorial-return')).toBeVisible();await expect(page.locator('#design-view')).toBeVisible();await page.locator('#back-to-tutorial').click();await expect(page.locator('.tutorial-progress')).toContainText('SCHRITT 2');
 await step(2);await expect(page.locator('.tutorial-mapping')).toContainText('{{company}}');await expect(page.locator('.tutorial-mapping')).toContainText('Nordlicht Immobilien');await page.locator('#tutorial-person').selectOption('1');await expect(page.locator('.tutorial-mapping')).toContainText('Studio Hafenblick');await expect(page.locator('.tutorial-mapping')).toContainText('Jonas');await shot('mapping');
 await step(3);await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Jonas,');await page.locator('#tutorial-text').fill('Hallo {{first_name}}, willkommen!');await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Jonas, willkommen!');await page.locator('#tutorial-person').selectOption('0');await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Anna, willkommen!');let c=await project();assert.equal(c.sides.back.fields.find(f=>f.id===c.tutorial.fieldId).text,'Hallo {{first_name}}, willkommen!');
 await page.locator('#tutorial-text').fill('{{unbekannt}}');await expect(page.locator('#tutorial-text-help')).toContainText('fehlt ein Wert');await page.locator('[data-tutorial-action="reset-text"]').click();await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Anna,');await page.locator('#tutorial-text').fill('Für ');await page.locator('[data-tutorial-token="company"]').click();await expect(page.locator('#tutorial-resolved')).toHaveText('Für Nordlicht Immobilien');await page.locator('[data-tutorial-action="reset-text"]').click();await shot('playground');
 await step(4);await page.locator('[data-tutorial-data="first_name"]').fill('Mia');await page.locator('[data-tutorial-data="first_name"]').press('Tab');await expect(page.locator('[data-tutorial-data="salutation"]')).toHaveValue('Hallo Mia,');await page.locator('[data-tutorial-data="company"]').fill('Mias Beispielstudio');await page.locator('[data-tutorial-data="company"]').press('Tab');await step(3);await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Mia,');await page.waitForTimeout(450);await page.reload();await expect(page.locator('#tutorial-view')).toBeVisible();await expect(page.locator('.tutorial-progress')).toContainText('SCHRITT 4');await expect(page.locator('#tutorial-resolved')).toHaveText('Hallo Mia,');
 await step(5);await page.locator('#tutorial-url').fill('https://example.org/mia');await page.locator('#tutorial-url').press('Tab');await page.waitForFunction(()=>document.querySelector('#tutorial-qr').width===440);await page.waitForTimeout(150);const pixels=await page.locator('#tutorial-qr').evaluate(c=>({data:Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}));assert.equal(jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height).data,'https://example.org/mia');await page.locator('#tutorial-url').fill('kein-link');await page.locator('#tutorial-url').press('Tab');await expect(page.locator('#tutorial-qr-status')).toContainText('HTTP(S)');await page.locator('#tutorial-url').fill('https://example.org/mia');await page.locator('#tutorial-url').press('Tab');await shot('qr');
 await step(6);await page.locator('[data-tutorial-action="three-d"]').click();await expect(page.locator('#three-d-view')).toBeVisible();await page.locator('#three-d-flip').click();await expect(page.locator('#three-d-stage')).toHaveAttribute('data-face','back');await page.locator('#back-to-tutorial').click();await expect(page.locator('.tutorial-progress')).toContainText('SCHRITT 7');
 await step(7);const event=page.waitForEvent('download');await page.locator('[data-tutorial-action="pdf"]').click();assert.equal((await PDFDocument.load(await readFile(await(await event).path()))).getPageCount(),2);await page.locator('[data-tutorial-action="audit"]').click();await expect(page.locator('#audit-results')).toContainText('Alle Empfänger geprüft');await page.locator('#back-to-tutorial').click();
 for(const width of [1024,768,390]){await page.setViewportSize({width,height:950});for(const n of [0,2,3,4,5,7]){await step(n);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow at '+width+' step '+n);}await shot('mobile-'+width);}
 await page.locator('[data-tutorial-action="finish"]').click();await expect(page.locator('#tutorial-return')).toBeHidden();assert.equal((await project()).tutorial.active,false);await page.locator('#breadcrumb-campaigns').click();await expect(page.locator('.dashboard-card')).toHaveCount(2);await page.locator('.campaign-card-content [data-dashboard-open]').filter({hasText:'Entwurf bleibt erhalten'}).click();assert.equal((await project()).recipients.length,0);
 await page.goto('http://127.0.0.1:4177/studio/?tutorial=1');await expect(page.locator('#tutorial-view')).toBeVisible();assert.ok(!page.url().includes('tutorial='));await page.reload();await expect(page.locator('#tutorial-view')).toBeVisible();assert.deepEqual(errors,[]);console.log('Tutorial passed: original preserved, all 8 steps, live tokens, name edits, missing values, decoded QR, view return, progress reload, PDF, full audit, completion and responsive layouts.');
}finally{await browser.close();}
