import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createCartCampaign} from '../studio/src/cart-campaigns.js';
import {csvString,FORMATS,createCampaign,uid,checks,validateCampaign,sideNames} from '../studio/src/core.js';
const origin='http://127.0.0.1:4183';await mkdir('test-results/workflow',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const testEmail='workflow-'+Date.now()+'@example.org';
const auth=await context.request.post(origin+'/api/auth/register',{headers:{origin},data:{email:testEmail,password:'safe-test-password-123',profile:{company:'Teststudio',name:'Anna Test'}}});assert.equal(auth.status(),201);const {csrf}=await auth.json();
const request=async(path,method='GET',data)=>{const r=await context.request.fetch(origin+'/api'+path,{method,headers:{origin,'x-csrf-token':csrf},...(data?{data}:{})});const result=await r.json();assert.ok(r.ok(),JSON.stringify(result));return result;};
try{
 // Guests can plan and persist a draft before choosing to sign in.
 const guestContext=await browser.newContext({viewport:{width:1440,height:1050}}),guest=await guestContext.newPage();
 guest.on('pageerror',e=>errors.push(e.message));
 await guest.goto(origin+'/konto/?tab=new-campaign');await guest.locator('[name=name]').fill('Mein Entwurf ohne Konto');
 await guest.locator('#start-campaign-form button').click();await expect(guest).toHaveURL(/tab=build/);await expect(guest.locator('#auth-dialog')).not.toBeVisible();
 await expect(guest.locator('.build-header h1')).toHaveText('Mein Entwurf ohne Konto');
 await guest.getByRole('button',{name:'Entwurf online speichern →',exact:true}).click();
 await expect(guest.locator('#auth-dialog')).toContainText('Ein Konto für alle deine Kampagnen');
 await guest.locator('[data-auth-close]').click();await expect(guest.locator('.build-header h1')).toHaveText('Mein Entwurf ohne Konto');
 await guest.screenshot({path:'test-results/workflow/guest-draft.png',fullPage:true});
 await guest.getByRole('button',{name:'Entwurf online speichern →',exact:true}).click();await guest.locator('[data-auth-switch]').click();
 await guest.locator('#auth-form [name=email]').fill(testEmail);await guest.locator('#auth-form [name=password]').fill('safe-test-password-123');await guest.locator('#auth-form button').click();
 await expect(guest.locator('#notice')).toContainText('jetzt in deinem Konto gespeichert');
 assert.equal((await request('/campaigns')).campaigns.filter(c=>c.project.name==='Mein Entwurf ohne Konto').length,1);
 await guest.reload();await expect(guest.locator('.build-header h1')).toHaveText('Mein Entwurf ohne Konto');await guestContext.close();
 await page.goto(origin+'/konto/?tab=audiences');await page.getByRole('button',{name:'+ Zielgruppe anlegen',exact:true}).click();await page.locator('[name=name]').fill('RehaSleep Checkouts');
 const rows=createCartCampaign('reha-sleep').recipients.map(r=>({...r,street:'Musterstraße 1',postal_code:'10115',city:'Berlin'}));await writeFile('test-results/workflow/contacts.csv',csvString(rows,Object.keys(rows[0]).filter(k=>!['id','company'].includes(k))));
 await page.locator('#audience-file').setInputFiles('test-results/workflow/contacts.csv');await page.locator('#csv-confirm').click();await expect(page.locator('#audience-form')).toContainText('3 Kontakte');await page.getByRole('button',{name:'Zielgruppe speichern ✓'}).click();await expect(page.locator('#notice')).toContainText('Zielgruppe gespeichert');await page.screenshot({path:'test-results/workflow/audience.png',fullPage:true});
 await page.goto(origin+'/konto/?tab=designs');await page.getByRole('button',{name:'+ Design erstellen',exact:true}).click();await page.locator('#flow-dialog [name=name]').fill('RehaSleep Freigabe');await page.locator('#flow-dialog [name=template]').selectOption('client:reha-sleep');await page.locator('#flow-dialog button[type=submit]').click();await page.waitForURL('**/studio/?design=*');await expect(page.locator('#rename-campaign')).toHaveText('RehaSleep Freigabe');
 await page.locator('#rename-campaign').click();await page.locator('#modal input').fill('RehaSleep Kartenentwurf');await page.locator('#modal [data-result=ok]').click();await expect(page.locator('#save-state')).toContainText('Im Konto gespeichert');
 const reviewObserver=await context.newPage();await reviewObserver.goto(origin+'/konto/?tab=reviews');await expect(reviewObserver.getByRole('heading',{name:'Feedback direkt auf dem Design.'})).toBeVisible();
 await page.goto(origin+'/konto/?tab=designs');await page.getByRole('button',{name:'Zur Freigabe',exact:true}).click();await page.locator('#flow-dialog input[type=checkbox]').check();await page.locator('#flow-dialog button[type=submit]').click();await expect(page.locator('#share-url')).toBeVisible();const url=await page.locator('#share-url').inputValue();
 await reviewObserver.getByRole('button',{name:'Aktualisieren ↻',exact:true}).click();await expect(reviewObserver.getByRole('heading',{name:'RehaSleep Kartenentwurf',exact:true})).toBeVisible();await expect(reviewObserver.locator('.page-heading p')).toContainText('1 Kundenfreigaben');await reviewObserver.getByRole('button',{name:'Feedback öffnen →',exact:true}).click();await expect(reviewObserver.locator('#share-url')).toHaveValue(url);await expect(reviewObserver.getByRole('link',{name:'Kundenansicht öffnen ↗'})).toHaveAttribute('href',url);await expect(reviewObserver.locator('.flow-share')).not.toContainText('In diesem Browser');await reviewObserver.screenshot({path:'test-results/workflow/persistent-link.png',fullPage:true});await reviewObserver.close();
 // Team comments are created directly on the card, persist after reload and are shared with the customer.
 await page.getByRole('button',{name:'Rückseite',exact:true}).click();await page.locator('#owner-zoom').selectOption('1.5');
 await page.locator('[data-owner-sheet=back]').click({position:{x:90,y:80}});await expect(page.locator('#flow-dialog')).toContainText('Markierung auf der Rückseite');
 await page.locator('#flow-dialog textarea').fill('Bitte den QR-Code etwas größer setzen.');await page.locator('#flow-dialog button[type=submit]').click();
 await expect(page.locator('.project-feedback')).toContainText('QR-Code etwas größer');await expect(page.locator('.project-next')).toContainText('Änderungen offen');
 await page.reload();await expect(page.locator('h1')).toHaveText('RehaSleep Kartenentwurf');await expect(page.locator('.project-feedback')).toContainText('QR-Code etwas größer');
 await page.getByRole('button',{name:'Markierung ansehen',exact:true}).click();await expect(page.locator('[data-owner-sheet=back]')).toBeVisible();
 await page.getByRole('button',{name:'Als erledigt markieren'}).click();
 await page.screenshot({path:'test-results/workflow/project-comments.png',fullPage:true});
 const publicContext=await browser.newContext({viewport:{width:1440,height:1050}}),review=await publicContext.newPage();review.on('pageerror',e=>errors.push(e.message));await review.goto(url);await expect(review.locator('[data-sheet=front] canvas')).toHaveJSProperty('width',1680);await review.getByRole('button',{name:'Rückseite',exact:true}).click();await expect(review.locator('[data-sheet=back]')).toBeVisible();await review.locator('#zoom-in').click();await review.locator('#zoom-in').click();await expect(review.locator('#zoom-value')).toHaveText('150 %');await review.getByRole('button',{name:'Vorderseite',exact:true}).click();await review.locator('#zoom-reset').click();await expect(review.locator('#zoom-value')).toHaveText('100 %');await review.locator('[data-sheet=front]').click({position:{x:80,y:70}});await expect(review.locator('#comment-dialog')).toBeVisible();await review.locator('#comment-form [name=name]').fill('Kunde Test');await review.locator('#comment-form textarea').fill('Bitte das Logo größer machen.');const concurrent=(await request('/reviews')).items[0];let concurrentReview=await request('/reviews/'+concurrent.id+'/comment','POST',{revision:concurrent.revision,version:concurrent.version,text:'Abstimmung läuft parallel.'});concurrentReview=await request('/reviews/'+concurrent.id+'/resolve','POST',{revision:concurrentReview.revision,commentId:concurrentReview.events.at(-1).id});await review.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(review.locator('#comment-form textarea')).toHaveValue('Bitte das Logo größer machen.');await review.locator('#comment-form button[type=submit]').click();await expect(review.locator('#comment-error')).toContainText('Dein Text ist noch da');await expect(review.locator('#comment-form textarea')).toHaveValue('Bitte das Logo größer machen.');await review.locator('#comment-form button[type=submit]').click();await expect(review.locator('.review-comment').filter({hasText:'Logo größer'})).toBeVisible();await review.screenshot({path:'test-results/workflow/review-comment.png',fullPage:true});await expect(review.locator('#start-approve')).toBeDisabled();
 await page.getByRole('button',{name:'Feedback aktualisieren ↻'}).click();await page.getByRole('button',{name:'Als erledigt markieren'}).click();await expect(review.locator('#start-approve')).toBeEnabled({timeout:22000});await review.locator('#start-approve').click();await review.locator('#approve-form [name=name]').fill('Kunde Test');await review.locator('#approve-form [name=confirm]').check();await review.locator('#approve-form button').click();await expect(review.locator('#review-state')).toHaveText('Design freigegeben');
 await page.getByRole('link',{name:'Design bearbeiten ↗',exact:true}).click();await expect(page.locator('#workspace-link')).toHaveText('Zurück zur Abstimmung');await page.locator('#rename-campaign').click();await page.locator('#modal input').fill('RehaSleep Revision 2');await page.locator('#modal [data-result=ok]').click();await page.locator('#workspace-link').click();await expect(page).toHaveURL(/tab=reviews&review=/);await expect(page.locator('h1')).toHaveText('RehaSleep Kartenentwurf');await expect(page.locator('.project-next')).toContainText('Design bearbeitet');await page.getByRole('button',{name:'Überarbeitetes Design bereitstellen'}).click();await page.locator('#flow-dialog button[type=submit]').click();await expect(page.locator('.page-heading p')).toContainText('Version 2');await expect(page.locator('#share-url')).toHaveValue(url);await review.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(review.locator('#review-state')).toHaveText('Wartet auf dein Feedback');await expect(review.locator('.review-title .eyebrow')).toContainText('DEIN DESIGNENTWURF');
 await review.setViewportSize({width:390,height:844});assert.ok(await review.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await review.screenshot({path:'test-results/workflow/review-mobile.png',fullPage:true});await review.locator('[data-sheet=front]').click({position:{x:60,y:50}});await expect(review.locator('#comment-dialog')).toBeVisible();await review.screenshot({path:'test-results/workflow/review-comment-mobile.png',fullPage:true});await review.locator('#comment-close').click();
 await page.goto(origin+'/konto/?tab=new-campaign');await page.locator('#start-campaign-form [name=name]').fill('September Rückgewinnung');await page.locator('#start-campaign-form button').click();await page.locator('#build-library').selectOption({index:1});await expect(page.locator('[data-proof=front]')).toBeVisible();await page.locator('[data-next]').click();await page.locator('#build-audience').selectOption({index:1});await expect(page.locator('.build-upload')).toContainText('3 Kontakte');await page.screenshot({path:'test-results/workflow/campaign-proof.png',fullPage:true});await page.locator('[data-next]').click();await page.locator('[name=goal]').selectOption('purchase');await page.locator('[data-save]').click();const campaigns=(await request('/campaigns')).campaigns;assert.equal(campaigns.find(c=>c.project.name==='September Rückgewinnung').project.recipients.length,3);
 const reviewCount=(await request('/reviews')).items.length;const source=(await request('/library/designs')).items[0];await page.goto(origin+'/konto/?tab=reviews&source=designs:'+source.id);await expect(page.locator('#share-url')).toBeVisible();await expect(page.locator('h1')).toHaveText('RehaSleep Kartenentwurf');assert.equal((await request('/reviews')).items.length,reviewCount);
 await page.setViewportSize({width:1000,height:900});await expect(page.locator('nav [data-view=contacts]')).toHaveText('Kontakte');const sidebar=page.locator('.sidebar');assert.ok(await sidebar.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:'test-results/workflow/reviews-sidebar.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await page.locator('.sidebar nav a').evaluateAll(links=>links.every(a=>a.scrollWidth<=a.clientWidth+1)));await page.screenshot({path:'test-results/workflow/project-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1050});
 // Delete a review without deleting the design; recover it through the UI.
 await page.getByRole('button',{name:'← Alle Freigaben',exact:true}).click();
 await page.getByRole('button',{name:'Löschen',exact:true}).click();await page.locator('#flow-dialog button[type=submit]').click();
 await expect(page.getByRole('heading',{name:'Feedback direkt auf dem Design.'})).toBeVisible();
 await page.getByRole('button',{name:'Papierkorb öffnen',exact:true}).click();await expect(page.locator('.review-trash')).toContainText('RehaSleep Kartenentwurf');
 await page.getByRole('button',{name:'Wiederherstellen',exact:true}).click();await expect(page.getByRole('button',{name:'Feedback öffnen →',exact:true})).toBeVisible();
 assert.equal((await request('/reviews')).items.length,reviewCount);
 // A saved draft can still defer contacts and use the full editor later.
 await page.goto(origin+'/konto/?tab=new-campaign');await page.locator('#start-campaign-form [name=name]').fill('Erst mal eine Idee');await page.locator('#start-campaign-form button').click();await expect(page).toHaveURL(/tab=build/);
 const draft=(await request('/campaigns')).campaigns.find(c=>c.project.name==='Erst mal eine Idee');assert.equal(draft.project.recipients.length,0);
 await page.goto(origin+'/studio/?cloud='+draft.id+'&view=recipients&build='+draft.id);await expect(page.locator('#rename-campaign')).toHaveText('Erst mal eine Idee');await page.locator('#csv-file').setInputFiles('test-results/workflow/contacts.csv');await page.locator('#csv-confirm').click();await expect(page.locator('#save-state')).toContainText('Im Konto gespeichert');assert.equal((await request('/campaigns/'+draft.id)).project.recipients.length,3);
 // Each print format is a real, saved studio geometry; one-sided A4 exports one page.
 for(const format of FORMATS){const p=createCampaign(true);p.name=format.name;p.format=format.id;p.recipients=[{id:uid(),company:'Beispiel',first_name:'Anna'}];const f={id:uid(),type:'text',text:'Hallo {{first_name}}',x:10,y:10,w:100,h:20,fontSize:18,color:'#26382a',weight:'700',align:'left',background:'transparent',autoFit:true};p.sides.front.fields=[f];if(format.pages===2)p.sides.back.fields=[{...f,id:uid()}];assert.ok(validateCampaign(p));assert.equal(checks(p).filter(i=>i.level==='error').length,0);const saved=await request('/library/designs','POST',{project:p});if(format.pages===1){await page.goto(origin+'/studio/?design='+saved.id);await expect(page.locator('#dimensions')).toHaveText('210 × 297 mm');await expect(page.locator('[data-side=back]')).toBeHidden();await page.locator('#open-preview').click();const download=page.waitForEvent('download');await page.locator('#pdf-export').click();await(await download).saveAs('test-results/workflow/a4-single.pdf');}}
 await page.goto(origin+'/konto/?tab=designs');await page.screenshot({path:'test-results/workflow/designs.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/workflow/designs-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('CSV audience, B2C mapping, saved design editor, annotated review, approval, revision reset, campaign composition, seven formats, one-page A4 PDF and mobile layouts passed.');
}catch(e){await page.screenshot({path:'test-results/workflow/failure.png',fullPage:true});console.error('Browser errors:',errors);throw e;}finally{await browser.close();}
