import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const root=process.env.WORKSPACE_URL||'http://127.0.0.1:4181';
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1020},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(root+'/');await expect(page.locator('h1')).toContainText('B2B-Outreach.');await expect(page.locator('a[href="/konto/"]')).toBeVisible();
 await page.goto(root+'/konto/?demo=1');await expect(page.locator('h1')).toHaveText('Neue Projektkunden');await expect(page.locator('.metric').last()).toContainText('433,3');await page.screenshot({path:'test-results/workspace-demo-desktop.png',fullPage:true});
 for(const width of [768,390]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`test-results/workspace-demo-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:1440,height:1020});await page.goto(root+'/konto/');await expect(page.locator('h1')).toHaveText('Dein Arbeitsplatz.');await page.screenshot({path:'test-results/workspace-empty.png',fullPage:true});
 await page.locator('[data-action=service]').click();await page.locator('[name=audience]').fill('Webdesign-Agenturen');await page.locator('[name=region]').fill('DACH');await page.locator('[name=roles]').fill('Geschäftsführung');await page.locator('[name=notes]').fill('Ein persönlicher Einstieg für unser Angebot.');await page.locator('#brief-form button[type=submit]').click();await expect(page.locator('#auth-dialog')).toBeVisible();
 const email='workspace-'+Date.now()+'@example.org';await page.locator('#auth-form [name=company]').fill('Testfirma Studio');await page.locator('#auth-form [name=name]').fill('Mara Muster');await page.locator('#auth-form [name=email]').fill(email);await page.locator('#auth-form [name=password]').fill('Sicheres-Testpasswort-123');await page.locator('#auth-form button').click();await expect(page.locator('.success')).toContainText('Deine Anfrage ist gespeichert.');await page.screenshot({path:'test-results/workspace-request.png',fullPage:true});
 const accountCookie=(await context.cookies()).find(c=>c.name==='kontaktstoff_session');assert.equal(accountCookie.httpOnly,true);
 await page.locator('[data-view=company]').click();await page.locator('[name=street]').fill('Beispielweg 3');await page.locator('[name=postalCode]').fill('01067');await page.locator('[name=city]').fill('Dresden');await page.locator('#profile-form button').click();await page.reload();await expect(page.locator('[name=postalCode]')).toHaveValue('01067');
 // Open an account campaign, fill it with a real design and CSV, then return to the workspace.
 await page.locator('[data-view=campaigns]').click();await page.locator('.tile-actions a').first().click();await expect(page.locator('#save-state')).toContainText('Im Konto gespeichert');await page.locator('#empty-add-text').click();await page.locator('#field-text').fill('Hallo {{first_name}},');await expect(page.locator('#save-state')).toContainText('Im Konto gespeichert');
 await page.locator('[data-tab=recipients]').click();await page.locator('#csv-file').setInputFiles({name:'kunden.csv',mimeType:'text/csv',buffer:Buffer.from('Firma;Vorname;Nachname;Funktion;Link;PLZ\nAtelier Beispiel;Anna;Muster;Inhaberin;https://example.org/anna;01067\nAgentur Test;Jonas;Test;CEO;https://example.org/jonas;20095')});await page.locator('#csv-confirm').click();await expect(page.locator('#save-state')).toContainText('Im Konto gespeichert');await page.locator('#workspace-link').click();await expect(page.locator('h1')).toHaveText('Meine Kampagnenidee');
 await page.locator('nav [data-view=contacts]').click();await expect(page.locator('tbody')).toContainText('Anna Muster');await page.locator('[data-action=contact]').first().click();await page.locator('[name=shipping]').selectOption('sent');await page.locator('[name=sales]').selectOption('won');await page.locator('[name=contribution]').fill('1800');await page.locator('[name=wonAt]').fill('2026-09-21');await page.locator('#contact-form button').click();
 await page.locator('nav [data-view=analytics]').click();await page.locator('[name=cost]').fill('300');await page.locator('#cost-form button').click();await expect(page.locator('.result-list')).toContainText('500 %');await page.locator('[data-action=tracking]').click();await page.locator('#confirm-dialog button[value=yes]').click();await expect(page.locator('#notice')).toContainText('Links aktiviert');
 await page.locator('nav [data-view=overview]').click();await expect(page.locator('.metrics')).toContainText('1');await page.screenshot({path:'test-results/workspace-live-dashboard.png',fullPage:true});
 await page.locator('.page-heading a').click();await page.locator('[data-tab=recipients]').click();await expect(page.locator('[data-key=chatbot_url]').first()).toHaveValue(/\/r\//);const url=await page.locator('[data-key=chatbot_url]').first().inputValue();const click=await context.request.get(url,{maxRedirects:0});assert.equal(click.status(),302);await page.locator('#workspace-link').click();await expect(page.locator('.funnel')).toContainText('Kontakte mit Scan');
 // An account is available on a second device; guest drafts do not leak as server campaigns.
 const second=await browser.newContext(),p2=await second.newPage();await p2.goto(root+'/konto/');await p2.locator('[data-action=login]').click();await p2.locator('#auth-form [name=email]').fill(email);await p2.locator('#auth-form [name=password]').fill('Sicheres-Testpasswort-123');await p2.locator('#auth-form button').click();await expect(p2.locator('h1')).toHaveText('Meine Kampagnenidee');await p2.locator('[data-action=logout]').click();await expect(p2.locator('h1')).toHaveText('Dein Arbeitsplatz.');await second.close();
 // Money Making Sprint carries the customized personal draft into the request form.
 await page.goto(root+'/fuer/money-making-sprint/');await page.locator('.client-customize summary').click();await page.locator('#client-name').fill('Lena');await page.locator('#client-company').fill('Lenas Agentur');await page.locator('#client-request button[type=submit]').click();await expect(page.locator('#brief-form')).toBeVisible();await expect(page.locator('[name=audience]')).toHaveValue('Webdesign-Agenturen');
 await page.setViewportSize({width:390,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'test-results/workspace-brief-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 console.log('Workspace passed: unchanged homepage linked, responsive demo, guest brief, registration gate, persisted request, company data, cloud editor, CSV, sales/ROI, real tracking redirects, second-device login and MMS handoff.');
}finally{await browser.close();}
