import {createBrandTemplate,applyBrandText,PREVIEW_PERSON} from '../studio/src/brand-templates.js';
import {renderCanvas} from '../studio/src/render.js';
import {Mailing3D} from '../studio/src/three-d.js';
import {salesConfig} from './config.js';
const $=s=>document.querySelector(s),config=salesConfig(new URLSearchParams(location.search));
const cases={
 b2b:{template:'stacked-note',brand:'chattastic.',headline:'Mehr Zeit für\ndeine Interessenten.',message:'Fragen zu Exposés, zur Lage oder zum nächsten Besichtigungstermin: Ein Website-Assistent könnte dein Team bei den ersten Antworten unterstützen.',cta:'Deine Demo kennenlernen →',kicker:'NEUE GESCHÄFTSKUNDEN',title:'Ein konkreter Anlass statt einer Massenansprache.',body:'Zeige deinen Wunschkunden, warum dein Angebot zu ihrem Alltag passt. Die Karte führt direkt zu einer Demo, einem Termin oder einer persönlichen Landingpage.',points:['Unternehmen und Ansprechpartner einsetzen','Eine relevante Idee auf der Karte zeigen','Direkt zur passenden Zielseite führen']},
 recovery:{template:'return-ticket',brand:'DEIN SHOP',headline:'Deine Auswahl.\nNoch einen Schritt\nentfernt.',message:'Du hattest etwas für dich entdeckt. Falls der Moment noch nicht gepasst hat: Hier findest du deine Auswahl wieder. Schau in Ruhe weiter.',cta:'Zurück zu deiner Auswahl →',kicker:'WARENKORBRÜCKGEWINNUNG',title:'Das Interesse ist schon da. Hol es zurück ins Blickfeld.',body:'Eine persönliche Erinnerung greift die ausgewählten Produkte auf. Der QR-Code öffnet den Rückkehr-Link aus deinem Shop.',points:['Geeignete Checkouts per CSV übernehmen','Persönliche Ansprache und Produktauswahl nutzen','Bereits erfolgte Käufe vor dem Versand ausschließen']},
 reactivation:{template:'product-moment',brand:'DEINE MARKE',headline:'Lange nicht\ngesehen. Schön,\ndass du da bist.',message:'Es gibt Neues zu entdecken. Wir möchten dich persönlich einladen, wieder vorbeizuschauen – mit einer Auswahl, die zu dir passen könnte.',cta:'Neues entdecken →',kicker:'BESTANDSKUNDENAKTIVIERUNG',title:'Wieder ins Gespräch kommen. Mit Menschen, die euch kennen.',body:'Ein neuer Anlass, ein passendes Angebot oder eine persönliche Einladung bringt deine Marke zurück auf den Tisch.',points:['Passende Bestandskunden auswählen','Anlass und Angebot je Zielgruppe abstimmen','Reaktionen der Kampagne zuordnen']}
};
let current=config.useCase,side='front',mode='3d',generation=0;
const three=new Mailing3D($('#sales-stage'));
if(config.company){$('#personal-intro').textContent='EINE MAILING-IDEE FÜR '+config.company;document.title=config.company+' × Kontaktstoff · Persönliche Mailings';$('#sales-inquiry [name=company]').value=config.company;}
if(config.loom){$('#loom-note').hidden=false;$('#loom-link').href=config.loom;}
function project(kind){const d=cases[kind],p=createBrandTemplate(d.template);applyBrandText(p,'brand',d.brand);applyBrandText(p,'headline',d.headline);applyBrandText(p,'body',d.message);applyBrandText(p,'cta',d.cta);return p;}
async function paint(){const version=++generation,d=cases[current],p=project(current);$('#case-kicker').textContent=d.kicker;$('#case-title').textContent=d.title;$('#case-body').textContent=d.body;$('#case-points').replaceChildren(...d.points.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===current)));$('#sales-inquiry [name=useCase]').value=current;
 try{for(const face of ['front','back']){const canvas=document.createElement('canvas');await renderCanvas(canvas,p,face,PREVIEW_PERSON,{scale:5});if(version!==generation)return;const dest=$('#example-'+face);dest.width=canvas.width;dest.height=canvas.height;dest.getContext('2d').drawImage(canvas,0,0);}flat();}catch{$('#view-help').textContent='Vorschau konnte nicht geladen werden. Bitte neu laden.';}
}
function flat(){const source=$('#example-'+side),dest=$('#example-flat');dest.width=source.width;dest.height=source.height;dest.getContext('2d').drawImage(source,0,0);}
function view(){document.querySelectorAll('[data-side]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.side===side)));document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#sales-stage').hidden=mode==='2d';$('#sales-flat').hidden=mode==='3d';$('#view-help').textContent=mode==='3d'?'Ziehen zum Drehen':'Beispielkontakt: Anna';if(mode==='3d')side==='front'?three.front():three.back();else flat();}
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{current=b.dataset.case;side='front';view();paint();});document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;view();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;view();});
document.querySelectorAll('[data-privacy]').forEach(b=>b.onclick=()=>$('#privacy-dialog').showModal());$('#privacy-dialog .dialog-close').onclick=()=>$('#privacy-dialog').close();
const form=$('#sales-inquiry');let requestId='',lastPayload='';
form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;$('#form-error').hidden=true;try{const data=Object.fromEntries(new FormData(form));Object.assign(data,{sourceCompany:config.company,loom:config.loom});const serialized=JSON.stringify(data);if(serialized!==lastPayload||!requestId){requestId=crypto.randomUUID();lastPayload=serialized;}const response=await fetch('/api/sales-inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,id:requestId})});let result;try{result=await response.json();}catch{throw Error('Die Verbindung hat nicht geklappt. Deine Angaben bleiben stehen; bitte erneut versuchen.');}if(!response.ok)throw Error(result.error||'Bitte erneut versuchen.');for(const child of form.children)child.hidden=true;$('#form-success').hidden=false;$('#form-success').focus();}catch(e){$('#form-error').hidden=false;$('#form-error').textContent=e.message;button.disabled=false;}};
await document.fonts.ready;const hero=createBrandTemplate('personal-letter');applyBrandText(hero,'brand','kontaktstoff.');applyBrandText(hero,'headline','Eine gute Idee.\nPersönlich für dich.');applyBrandText(hero,'cta','Dein nächster Kontakt beginnt hier →');await renderCanvas($('#hero-card'),hero,'front',PREVIEW_PERSON,{scale:4});await paint();
