import {randomUUID,randomBytes} from 'node:crypto';
import {HTTPError,text} from './validation.js';
import {readWebsite,websiteURL} from './website-preview.js';
import {MMS_PROPOSAL} from '../mailings/proposal-config.js';
import {loomURL,SALES_CASES} from '../mailings/config.js';
const layouts=['personal-letter','bold-type','return-ticket','photo-story','product-moment','stacked-note','editorial','hello-team','invitation','fresh-start','money-making-sprint'];
const fields={company:100,website:500,headline:150,intro:650,audience:200,rationale:650,offer:350,cardHeadline:150,cardBody:550,cardCta:60,target:500,recipientName:35,recipientCompany:65,sender:80,sourceTitle:180,sourceDescription:500,sourceHeadline:180};
const proposalFormats=['a5-landscape','selfmailer-dl-4'];
function image(v){if(!v)return '';if(typeof v!=='string'||v.length>650000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(v))throw new HTTPError(400,'Bitte PNG, JPG oder WebP bis 450 KB verwenden.');return v;}
export function validateProposal(input){const d={};if(input.format&&!proposalFormats.includes(input.format))throw new HTTPError(400,'Unbekanntes Mailingformat.');d.format=input.format||'a5-landscape';for(const [key,max]of Object.entries(fields))d[key]=text(input[key]||'',max);if(!d.company||!d.headline||!d.cardHeadline||!d.cardBody)throw new HTTPError(400,'Unternehmen, Überschrift und Kartentexte fehlen.');d.website=websiteURL(d.website).href;d.target=websiteURL(d.target||d.website).href;d.useCase=Object.hasOwn(SALES_CASES,input.useCase)?input.useCase:'b2b';d.layout=layouts.includes(input.layout)?input.layout:'personal-letter';d.color=/^#[\da-f]{6}$/i.test(input.color||'')?input.color:'#24483e';d.logo=image(input.logo);d.photo=image(input.photo);d.loom=loomURL(input.loom||'');if(input.loom&&!d.loom)throw new HTTPError(400,'Bitte einen gültigen Loom-Freigabelink verwenden.');d.warnings=Array.isArray(input.warnings)?input.warnings.slice(0,5).map(v=>text(v,200)):[];return d;}
export function suggestProposal(site,useCase='b2b'){
 if(new URL(site.url).hostname.replace(/^www\./,'')==='money-making-sprint.de')return {...MMS_PROPOSAL,sourceTitle:site.title,sourceDescription:site.description,sourceHeadline:site.headline,warnings:MMS_PROPOSAL.warnings};
 if(!Object.hasOwn(SALES_CASES,useCase))useCase='b2b';const recovery=useCase==='recovery',reactivation=useCase==='reactivation',name=site.name,context=(site.title+' '+site.description+' '+site.headline).toLowerCase();
 const category=/agentur|agency|freelancer/.test(context)?'Unternehmen mit Bedarf an externer Unterstützung':/hotel|restaurant|gastronomie/.test(context)?'Gäste aus der Region':/immobil|real estate/.test(context)?'Eigentümer und Immobilieninteressenten':'passende Interessenten für euer Angebot';
 const offer=site.description||site.headline||'Euer Angebot persönlich kennenlernen';
 return {format:'selfmailer-dl-4',company:name,website:site.url,useCase,layout:recovery?'return-ticket':site.photo?'photo-story':'stacked-note',color:site.color||'#24483e',logo:site.logo||'',photo:site.photo||'',loom:'',headline:recovery?'Eine gute Auswahl verdient eine zweite Chance.':reactivation?'Ein neuer Anlass, wieder bei euch vorbeizuschauen.':name+'. Persönlich auf dem Schreibtisch eurer Wunschkunden.',intro:recovery?'Wir bringen eure Marke zurück ins Blickfeld: mit einer persönlichen Karte und dem direkten Weg zurück zur Auswahl.':`Eine Mailing-Idee für ${name}: euer Angebot, eine persönliche Ansprache und ein QR-Code zum nächsten Schritt.`,audience:recovery?'Checkout-Abbrecher mit vorhandener Postanschrift':reactivation?'Geeignete Bestandskunden':category,rationale:recovery?'Das Mailing knüpft an ein bestehendes Interesse an. Empfänger, Produkt und Rückkehr-Link werden vor dem Versand aus euren Shop-Daten übernommen.':`Die Karte macht ${name} greifbar und gibt der Nachricht einen eigenen Platz im Alltag. Persönliche Ansprache und eine klare Einladung führen direkt zu eurem Angebot.`,offer:offer.slice(0,350),cardHeadline:recovery?'Deine Auswahl.\nNoch einen Schritt\nentfernt.':reactivation?'Schön, wenn wir\nuns wiedersehen.':'Eine Idee für dich.\nVon '+name+'.',cardBody:recovery?'Du hattest etwas für dich entdeckt. Falls der Moment noch nicht gepasst hat: Schau in Ruhe noch einmal vorbei. Über den QR-Code findest du den nächsten Schritt.':`${offer.slice(0,280)}\n\nKlingt interessant? Schau dir unser Angebot in Ruhe an.`,cardCta:recovery?'Deine Auswahl ansehen →':'Unser Angebot kennenlernen →',target:site.url,recipientName:'Anna',recipientCompany:'Studio Nordlicht',sender:'Dein Team von '+name,sourceTitle:site.title,sourceDescription:site.description,sourceHeadline:site.headline,warnings:[...(site.warnings||[]),'Automatisch vorbereiteter Entwurf. Angebot, Zielgruppe, Bild und Ansprache vor dem Teilen prüfen.']};
}
const pack=r=>({id:r.id,slug:r.slug,revision:Number(r.revision),updatedAt:Number(r.updated_at),live:Boolean(r.published),draft:JSON.parse(r.draft)});
export function proposalService(db){return {
 async generate(input){return {draft:suggestProposal(await readWebsite(text(input.website||'',500)),input.useCase)};},
 async list(){const rows=(await db.query('SELECT * FROM sales_proposals ORDER BY updated_at DESC LIMIT 100')).rows;return {items:rows.map(r=>({id:r.id,slug:r.slug,revision:Number(r.revision),updatedAt:Number(r.updated_at),live:Boolean(r.published),company:JSON.parse(r.draft).company}))};},
 async get(id){const r=(await db.query('SELECT * FROM sales_proposals WHERE id=$1',[id])).rows[0];if(!r)throw new HTTPError(404,'Vorschlag nicht gefunden.');return pack(r);},
 async public(slug){const r=(await db.query('SELECT published FROM sales_proposals WHERE slug=$1',[slug])).rows[0];if(!r?.published)throw new HTTPError(404,'Diese persönliche Seite ist nicht verfügbar. Bitte wende dich an das Kontaktstoff-Team.');const d=JSON.parse(r.published);delete d.warnings;delete d.sourceTitle;delete d.sourceDescription;delete d.sourceHeadline;return {proposal:d,slug};},
 async save(id,input){const d=validateProposal(input.draft||{});if(!id){id=randomUUID();const base=d.company.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55)||'konzept';const slug=base+'-'+randomBytes(4).toString('hex');await db.query('INSERT INTO sales_proposals(id,slug,draft,published,revision,updated_at) VALUES($1,$2,$3,$4,1,$5)',[id,slug,JSON.stringify(d),input.publish===true?JSON.stringify(d):null,Date.now()]);}else{const r=await db.query('UPDATE sales_proposals SET draft=$1,published=CASE WHEN $2=1 THEN $1 ELSE published END,revision=revision+1,updated_at=$3 WHERE id=$4 AND revision=$5 RETURNING id',[JSON.stringify(d),input.publish===true?1:0,Date.now(),id,Number(input.revision)||0]);if(!r.rows.length)throw new HTTPError(409,'Der Vorschlag wurde inzwischen geändert. Bitte neu öffnen.');}return this.get(id);},
 async disable(id,input){const r=await db.query('UPDATE sales_proposals SET published=NULL,revision=revision+1,updated_at=$1 WHERE id=$2 AND revision=$3 RETURNING id',[Date.now(),id,Number(input.revision)||0]);if(!r.rows.length)throw new HTTPError(409,'Der Vorschlag wurde inzwischen geändert. Bitte neu öffnen.');return this.get(id);}
};}
