import {readCSVTable,guessMapping,mappedRecipients} from './csv-import.js';
import {KEYS} from './core.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openCSVImport(file,{keys,existingCount=0,onImport}){
 const dialog=document.querySelector('#csv-import-dialog');const revision=Symbol();dialog.importRevision=revision;const current=()=>dialog.open&&dialog.importRevision===revision;let table=null;
 dialog.innerHTML=`<div class="csv-modal-header"><div><span class="eyebrow">KONTAKTE IMPORTIEREN</span><h2>Deine Liste. Richtig zugeordnet.</h2></div><button class="icon-button" data-csv-close aria-label="Import schließen">×</button></div><div class="csv-modal-body"><p id="csv-import-status" role="status">Datei wird gelesen …</p><p id="csv-import-error" class="csv-error" role="alert" hidden></p><div id="csv-import-content" hidden></div></div><div class="csv-modal-footer"><button class="button" data-csv-close>Abbrechen</button><button class="button primary" id="csv-confirm" disabled>Kontakte übernehmen →</button></div>`;
 dialog.querySelectorAll('[data-csv-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.showModal();
 let mapping={},result=null;
 const error=message=>{dialog.querySelector('#csv-import-error').textContent=message;dialog.querySelector('#csv-import-error').hidden=!message;};
 function preview(){
  mapping=Object.fromEntries([...dialog.querySelectorAll('[data-csv-map]')].map(s=>[s.dataset.csvMap,Number(s.value)]));
  try{result=mappedRecipients(table,mapping,{fallbackURL:dialog.querySelector('#csv-common-url').value.trim(),salutationStyle:dialog.querySelector('#csv-salutation-style').value});error('');
   const notices=[];if(result.missingLinks)notices.push(`${result.missingLinks} Kontakte haben noch keinen Ziel-Link.`);if(result.invalidLinks)notices.push(`${result.invalidLinks} Links sind ungültig. Bitte nach dem Import korrigieren.`);
   const missingNotes=result.recipients.filter(r=>!r.personal_note).length;if(keys.includes('personal_note')&&missingNotes)notices.push(`${missingNotes} persönliche Nachrichten sind noch leer.`);
   dialog.querySelector('#csv-review').innerHTML=`<div class="csv-review-heading"><strong>So kommen deine Kontakte an</strong><span>${table.rows.length} Kontakte · Vorschau der ersten ${Math.min(3,table.rows.length)}</span></div>${result.recipients.slice(0,3).map(r=>`<article><strong>${esc(r.company)}</strong><span>${esc(r.salutation)}</span><p>${esc(r.personal_note||'Deine persönliche Nachricht ergänzt du im Studio.')}</p><small>${esc(r.chatbot_url||'Ziel-Link noch offen')}</small></article>`).join('')}<p class="csv-import-notice">${notices.length?esc(notices.join(' '))+' Du kannst importieren und die offenen Angaben anschließend ergänzen.':'Namen und Links sind zugeordnet. Deine Liste ist bereit.'}</p>`;
   dialog.querySelector('#csv-confirm').disabled=false;dialog.querySelector('#csv-confirm').textContent=`${table.rows.length} Kontakte übernehmen →`;
  }catch(e){result=null;error(e.message);dialog.querySelector('#csv-confirm').disabled=true;dialog.querySelector('#csv-review').innerHTML='';}
 }
 (async()=>{try{
  if(file.size>5*1024*1024)throw Error('Bitte eine CSV mit maximal 5 MB hochladen.');const input=await file.text();if(!current())return;table=readCSVTable(input);
  mapping=guessMapping(table.headers,keys);const main=['company','first_name','last_name','chatbot_url'];
  const field=key=>`<label><span>${esc(KEYS[key]||key)}</span><select data-csv-map="${esc(key)}" aria-label="CSV-Spalte für ${esc(KEYS[key]||key)}"><option value="-1">Nicht in meiner Liste</option>${table.headers.map((h,i)=>`<option value="${i}" ${mapping[key]===i?'selected':''}>${esc(h)} · ${esc(table.rows[0][i].slice(0,45))}</option>`).join('')}</select></label>`;
  dialog.querySelector('#csv-import-status').textContent=`${file.name} · ${table.rows.length} Kontakte erkannt. Prüfe kurz, welche Spalte zu welchem Inhalt gehört.`;
  dialog.querySelector('#csv-import-content').innerHTML=`<div class="csv-map-grid">${main.map(field).join('')}</div><details class="csv-extra"><summary>Anrede, Anschrift & weitere Spalten zuordnen</summary><div class="csv-map-grid">${keys.filter(k=>!main.includes(k)).map(field).join('')}</div></details><div class="csv-import-options"><label>Wenn keine Anrede vorhanden ist<select id="csv-salutation-style"><option value="du">Hallo Vorname,</option><option value="formal">Guten Tag,</option></select></label><label>Ein gemeinsamer Link für Kontakte ohne Link <span>(optional)</span><input id="csv-common-url" type="url" placeholder="https://deine-website.de/termin"><small>Vorhandene individuelle Links bleiben erhalten.</small></label></div><div id="csv-review" aria-live="polite"></div>${existingCount?`<fieldset class="csv-import-mode"><legend>Du hast bereits ${existingCount} Kontakte.</legend><label><input type="radio" name="csv-import-mode" value="append" checked> Neue Kontakte hinzufügen</label><label><input type="radio" name="csv-import-mode" value="replace"> Vorhandene Liste ersetzen</label></fieldset>`:''}<p class="csv-local-note">Nicht zugeordnete Spalten werden ausgelassen. Deine Datei wird lokal in diesem Browser verarbeitet.</p>`;
  dialog.querySelector('#csv-import-content').hidden=false;dialog.querySelector('#csv-import-content').addEventListener('change',preview);dialog.querySelector('#csv-common-url').addEventListener('input',preview);preview();
 }catch(e){if(!current())return;error(e.message);dialog.querySelector('#csv-import-status').textContent='Die Datei wurde noch nicht übernommen.';}})();
 dialog.querySelector('#csv-confirm').onclick=()=>{preview();if(!result)return;const mode=dialog.querySelector('[name=csv-import-mode]:checked')?.value||'replace';if(mode==='append'&&existingCount+result.recipients.length>1000){error('Zusammen wären es mehr als 1.000 Kontakte. Wähle „Liste ersetzen“ oder verkleinere die CSV.');return;}onImport(result.recipients,mode);dialog.close();};
}
