import {PROMOTIONS} from './promotions.js';
import {TEMPLATES} from './templates.js';
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function dashboardHTML(campaigns,deleted=[]){
 const own=campaigns.filter(c=>!c.sample),examples=campaigns.filter(c=>c.sample);
 const cardHTML=c=>`<article class="dashboard-card" data-campaign-card="${h(c.id)}" data-name="${h(c.name.toLowerCase())}"><button class="campaign-visual" data-dashboard-open="${h(c.id)}" aria-label="${h(c.name)} öffnen"><canvas data-dashboard-thumb="${h(c.id)}"></canvas><span>Weiterarbeiten ↗</span></button><div class="campaign-card-content"><span class="campaign-status">${c.sample?'Beispiel':'Entwurf'}</span><h3><button data-dashboard-open="${h(c.id)}">${h(c.name)}</button></h3><p>${c.recipients.length} Empfänger · ${new Date(c.updatedAt).toLocaleDateString('de-DE')}</p><div class="campaign-card-actions"><button data-dashboard-copy="${h(c.id)}">Duplizieren</button><button class="creation-delete" data-dashboard-delete="${h(c.id)}" aria-label="${h(c.name)} löschen">Löschen</button></div></div></article>`;
 return `<header class="studio-welcome"><div><span class="eyebrow">DEIN KAMPAGNENSTUDIO</span><h1>Dein nächstes Mailing.<br>Hier geht’s los.</h1><p>Starte deine eigene Karte. Wir führen dich von der Gestaltung bis zur fertigen Vorschau.</p><button class="button primary" data-dashboard-new>Eigene Kampagne starten →</button><span class="welcome-next">1. Karte gestalten <span>→</span> 2. Empfänger ergänzen <span>→</span> 3. Vorschau ansehen</span></div></header><section class="dashboard-inspiration" aria-labelledby="inspiration-title"><header><h2 id="inspiration-title">Lieber erst ein Beispiel ansehen?</h2><p>Such dir eine Karte aus. Du kannst das Design anschließend für deine Kampagne verwenden.</p></header><div class="dashboard-promotions">${PROMOTIONS.map(p=>`<button data-dashboard-example="${p.id}"><div class="dashboard-promotion-art" style="--promotion-color:${p.color}"><canvas data-promotion-thumb="${p.id}" aria-label="Fertiges ${p.name} Mailing"></canvas></div><span class="example-card-label"><strong>${p.name}</strong><b>Ansehen →</b></span></button>`).join('')}</div></section>
 <header class="creations-header"><div><span class="eyebrow">DEIN ARBEITSPLATZ</span><h2>Meine Kreationen.</h2><p>Hier findest du deine lokal gespeicherten Kampagnen.</p></div></header>
 <div class="dashboard-tools"><label><span class="sr-only">Kampagnen suchen</span><input id="campaign-search" type="search" placeholder="Kreation suchen …"></label><span>${own.length} ${own.length===1?'Kreation':'Kreationen'}</span><button class="button" data-dashboard-import>↑ Projekt importieren</button></div>
 <div id="dashboard-cards" class="dashboard-cards">${own.map(cardHTML).join('')}</div>
 <div class="dashboard-empty" id="dashboard-empty" ${own.length?'hidden':''}><span>↗</span><h3>Platz für deine erste Idee.</h3><p>Sobald du startest, erscheint deine Kampagne hier. Du kannst sie jederzeit weiterbearbeiten.</p></div><p id="search-empty" class="dashboard-empty" hidden>Keine Kreation mit diesem Namen gefunden.</p>
 ${examples.length?`<details class="saved-examples" id="saved-examples"><summary>Gespeicherte Beispiele <span>${examples.length}</span></summary><p>Deine bisherigen Beispiel- und Tutorial-Entwürfe. Du kannst sie öffnen oder löschen.</p><div class="dashboard-cards">${examples.map(cardHTML).join('')}</div></details>`:''}
 <details class="creation-trash" id="creation-trash"><summary>Papierkorb <b>${deleted.length}</b></summary><p>Gelöschte Kreationen bleiben hier in diesem Browser und können wiederhergestellt werden.</p>${deleted.length?deleted.map(c=>`<div class="trash-row"><span><strong>${h(c.name)}</strong><small>Gelöscht am ${new Date(c.deletedAt).toLocaleDateString('de-DE')}</small></span><button class="button" data-dashboard-restore="${h(c.id)}">Wiederherstellen</button></div>`).join(''):'<p>Dein Papierkorb ist leer.</p>'}</details>
 <details class="dashboard-library"><summary>Weitere Vorlagen entdecken <span>Bearbeitbare Startpunkte für dein eigenes Design.</span></summary><div class="dashboard-heading"><div><h2>Eine Vorlage für deinen Entwurf.</h2><p>Alles bleibt bearbeitbar. Du ergänzt deine eigenen Empfänger.</p></div></div><div class="template-grid">${TEMPLATES.map(t=>`<button class="template-card" data-dashboard-template="${t.id}"><div class="template-art" style="--template-color:${t.color};--template-accent:${t.accent}"><span>${t.tag}</span><strong>${t.name}</strong><b>↗</b></div><div><h3>${t.id==='chattastic'?'Website-Assistent':t.name}</h3><p>${t.description}</p><span>Vorlage verwenden →</span></div></button>`).join('')}</div></details>
 <aside class="dashboard-storage"><span>◉</span><div><strong>Dein Arbeitsplatz liegt in diesem Browser.</strong><p>Mit „Projekt sichern“ nimmst du deine Kampagne als Datei mit. Beim Löschen der Browserdaten gehen auch Kreationen und Papierkorb verloren.</p></div><a href="../">Zur Homepage ↗</a></aside>`;
}
