import {PROMOTIONS} from './promotions.js';
import {TEMPLATES} from './templates.js';
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function dashboardHTML(campaigns){
 return `<div class="dashboard-welcome"><div><span class="eyebrow">DEIN KONTAKTSTOFF-ARBEITSPLATZ</span><h1>Gute Kontakte<br>fangen hier an<span>.</span></h1><p>Deine Idee. Dein Design. Für jeden Empfänger persönlich.</p></div><div class="dashboard-start"><span class="mini-k">k.</span><h2>Ein weißes Blatt.<br>Alle Möglichkeiten.</h2><p>Wir begleiten dich von der Idee bis zum fertigen Kampagnenpaket.</p><button class="button primary" data-dashboard-new>Erste Kampagne starten ↗</button><small>Tutorial mit Beispielen · jederzeit überspringbar</small></div></div>
 <div class="dashboard-heading"><div><span class="eyebrow">ERST EINMAL DAS ERGEBNIS SEHEN</span><h2>Drei fertige Beispielpromotionen.</h2><p>Mit echten Fotos und fiktiven Kontakten. Öffne ein Beispiel in 3D oder starte direkt dein Tutorial.</p></div><button class="button" data-dashboard-tutorial>Tutorial starten →</button></div><div class="dashboard-promotions">${PROMOTIONS.map(p=>`<button data-dashboard-example="${p.id}"><div class="dashboard-promotion-art" style="--promotion-color:${p.color}"><canvas data-promotion-thumb="${p.id}" aria-label="Fertiges ${p.name} Mailing"></canvas></div><span>${p.category}</span><strong>${p.name} ↗</strong><p>${p.description}</p><b>Beispiel öffnen →</b></button>`).join('')}</div>
 <div class="dashboard-heading"><div><span class="eyebrow">DEINE KAMPAGNEN</span><h2>Raum für den nächsten Kontakt.</h2></div><button class="button" data-dashboard-import>↑ Projekt importieren</button></div>
 <div class="dashboard-tools"><label><span class="sr-only">Kampagnen suchen</span><input id="campaign-search" type="search" placeholder="Kampagne suchen …"></label><span>${campaigns.length} ${campaigns.length===1?'Kampagne':'Kampagnen'} · lokal in diesem Browser</span></div>
 <div id="dashboard-cards" class="dashboard-cards">${campaigns.map(c=>`<article class="dashboard-card" data-campaign-card="${h(c.id)}" data-name="${h(c.name.toLowerCase())}"><button class="campaign-visual" data-dashboard-open="${h(c.id)}" aria-label="${h(c.name)} öffnen"><canvas data-dashboard-thumb="${h(c.id)}"></canvas><span>Weiterarbeiten ↗</span></button><div class="campaign-card-content"><span class="campaign-status">${c.sample?'Beispiel':c.onboarding?.active?'Im Aufbau':'Entwurf'}</span><h3><button data-dashboard-open="${h(c.id)}">${h(c.name)}</button></h3><p>${c.recipients.length} Empfänger · ${new Date(c.updatedAt).toLocaleDateString('de-DE')}</p><div class="campaign-card-actions"><button data-dashboard-copy="${h(c.id)}">Duplizieren</button><button data-dashboard-delete="${h(c.id)}" aria-label="${h(c.name)} löschen">Löschen</button></div></div></article>`).join('')}</div>
 <div class="dashboard-empty" id="dashboard-empty" ${campaigns.length?'hidden':''}><span>↗</span><h3>Deine erste Kampagne wartet.</h3><p>Beginne mit einer leeren Karte oder wähle eine Vorlage. Deine Arbeit wird während der Bearbeitung automatisch gespeichert.</p><button class="button dark" data-dashboard-new>Erste Kampagne starten</button></div><p id="search-empty" class="dashboard-empty" hidden>Keine Kampagne mit diesem Namen gefunden.</p>
 <div class="dashboard-heading"><div><span class="eyebrow">EIN VORSPRUNG FÜR DEINE IDEE</span><h2>Vorlage wählen. Deine machen.</h2><p>Jeder Text, jede Farbe und jeder QR-Code ist bearbeitbar. Du ergänzt deine eigenen Empfänger.</p></div></div><div class="template-grid">${TEMPLATES.map(t=>`<button class="template-card" data-dashboard-template="${t.id}"><div class="template-art" style="--template-color:${t.color};--template-accent:${t.accent}"><span>${t.tag}</span><strong>${t.name}</strong><b>↗</b></div><div><h3>${t.id==='chattastic'?'Website-Assistent':t.name}</h3><p>${t.description}</p><span>Vorlage verwenden →</span></div></button>`).join('')}</div>
 <aside class="dashboard-storage"><span>◉</span><div><strong>Dein Arbeitsplatz liegt in diesem Browser.</strong><p>Mit „Projekt sichern“ nimmst du deine Kampagne als Datei mit. Browserdaten löschen entfernt lokale Entwürfe. Uploads und Empfängerdaten werden hier lokal verarbeitet.</p></div><a href="../">Zur Homepage ↗</a></aside>`;
}
