import {PROMOTIONS} from './promotions.js';
import {TEMPLATES} from './templates.js';
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function dashboardHTML(campaigns,deleted=[]){
 return `<header class="creations-header"><div><span class="eyebrow">DEIN ARBEITSPLATZ</span><h1>Meine Kreationen.</h1><p>Hier findest du deine lokal gespeicherten Kampagnen.</p></div><button class="button primary" data-dashboard-new>Neue Kampagne starten ↗</button></header>
 <div class="dashboard-tools"><label><span class="sr-only">Kampagnen suchen</span><input id="campaign-search" type="search" placeholder="Kreation suchen …"></label><span>${campaigns.length} ${campaigns.length===1?'Kreation':'Kreationen'}</span><button class="button" data-dashboard-import>↑ Projekt importieren</button></div>
 <div id="dashboard-cards" class="dashboard-cards">${campaigns.map(c=>`<article class="dashboard-card" data-campaign-card="${h(c.id)}" data-name="${h(c.name.toLowerCase())}"><button class="campaign-visual" data-dashboard-open="${h(c.id)}" aria-label="${h(c.name)} öffnen"><canvas data-dashboard-thumb="${h(c.id)}"></canvas><span>Weiterarbeiten ↗</span></button><div class="campaign-card-content"><span class="campaign-status">${c.sample?'Beispiel':'Entwurf'}</span><h3><button data-dashboard-open="${h(c.id)}">${h(c.name)}</button></h3><p>${c.recipients.length} Empfänger · ${new Date(c.updatedAt).toLocaleDateString('de-DE')}</p><div class="campaign-card-actions"><button data-dashboard-copy="${h(c.id)}">Duplizieren</button><button class="creation-delete" data-dashboard-delete="${h(c.id)}" aria-label="${h(c.name)} löschen">Löschen</button></div></div></article>`).join('')}</div>
 <div class="dashboard-empty" id="dashboard-empty" ${campaigns.length?'hidden':''}><span>↗</span><h3>Platz für deine erste Idee.</h3><p>Starte mit einer Vorlage, deinem eigenen Design oder einer leeren Karte.</p><button class="button dark" data-dashboard-new>Erste Kampagne starten</button></div><p id="search-empty" class="dashboard-empty" hidden>Keine Kreation mit diesem Namen gefunden.</p>
 <details class="creation-trash" id="creation-trash"><summary>Papierkorb <b>${deleted.length}</b></summary><p>Gelöschte Kreationen bleiben hier in diesem Browser und können wiederhergestellt werden.</p>${deleted.length?deleted.map(c=>`<div class="trash-row"><span><strong>${h(c.name)}</strong><small>Gelöscht am ${new Date(c.deletedAt).toLocaleDateString('de-DE')}</small></span><button class="button" data-dashboard-restore="${h(c.id)}">Wiederherstellen</button></div>`).join(''):'<p>Dein Papierkorb ist leer.</p>'}</details>
 <details class="dashboard-library"><summary>Vorlagen & Beispiele entdecken <span>Ein bisschen Inspiration für deine nächste Kampagne.</span></summary><div class="dashboard-heading"><div><h2>Erst einmal das Ergebnis sehen.</h2><p>Drei fertige Beispiele mit Fotos und fiktiven Kontakten.</p></div></div><div class="dashboard-promotions">${PROMOTIONS.map(p=>`<button data-dashboard-example="${p.id}"><div class="dashboard-promotion-art" style="--promotion-color:${p.color}"><canvas data-promotion-thumb="${p.id}" aria-label="Fertiges ${p.name} Mailing"></canvas></div><span>${p.category}</span><strong>${p.name} ↗</strong><p>${p.description}</p><b>Beispiel öffnen →</b></button>`).join('')}</div><div class="dashboard-heading"><div><h2>Eine Vorlage für deinen Entwurf.</h2><p>Alles bleibt bearbeitbar. Du ergänzt deine eigenen Empfänger.</p></div></div><div class="template-grid">${TEMPLATES.map(t=>`<button class="template-card" data-dashboard-template="${t.id}"><div class="template-art" style="--template-color:${t.color};--template-accent:${t.accent}"><span>${t.tag}</span><strong>${t.name}</strong><b>↗</b></div><div><h3>${t.id==='chattastic'?'Website-Assistent':t.name}</h3><p>${t.description}</p><span>Vorlage verwenden →</span></div></button>`).join('')}</div></details>
 <aside class="dashboard-storage"><span>◉</span><div><strong>Dein Arbeitsplatz liegt in diesem Browser.</strong><p>Mit „Projekt sichern“ nimmst du deine Kampagne als Datei mit. Beim Löschen der Browserdaten gehen auch Kreationen und Papierkorb verloren.</p></div><a href="../">Zur Homepage ↗</a></aside>`;
}
