import { icon } from './icons.js';
import { setupProgress } from './core.js';
const h = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
export const GUIDE_STEPS = ['Idee & Ziel', 'Format', 'Dein Design', 'Persönliche Felder', 'Empfänger', 'Ansehen & prüfen'];
const button = (action, label, primary = false, extra = '') => `<button class="button ${primary ? 'primary' : ''}" data-guide-action="${action}" ${extra}>${label}</button>`;
export function guideHTML(campaign) {
  const step = campaign.onboarding?.step || 0;
  const designReady=campaign.onboarding?.designReady&&step>=4;
  const contact=designReady?campaign.recipients[0]||{}:{};
  const needsLink=Object.values(campaign.sides).some(s=>s.fields.some(f=>f.type==='qr'));
  const progress = setupProgress(campaign);
  const brief = campaign.brief || {};
  const front = campaign.sides.front, back = campaign.sides.back;
  const sideCard = (s, label, number) => `<article class="guide-design-card"><div class="guide-design-thumb"><canvas id="guide-${s}"></canvas>${campaign.sides[s].background.kind === 'blank' && !campaign.sides[s].fields.length ? `<div class="empty-design-label">${icon('upload')}<strong>${label}</strong><span>Noch ganz unbeschrieben.</span></div>` : ''}</div><div class="guide-design-caption"><b>${number} / ${label}</b><span>${campaign.sides[s].background.kind === 'image' ? h(campaign.sides[s].background.name) : campaign.sides[s].fields.length ? `${campaign.sides[s].fields.length} eigene Elemente` : 'Dein Platz für eine gute Botschaft'}</span></div><div class="guide-design-actions">${button('upload-'+s, icon('upload')+' Design hochladen',true)}${button('edit-'+s,'Selbst gestalten ↗')}</div></article>`;
  const bodies = [
    `<div class="guide-intro"><span class="eyebrow">ERST DIE IDEE. DANN DAS MAILING.</span><h2>Wen möchtest du erreichen?</h2><p>Du brauchst noch kein fertiges Design und keine Empfängerliste. Wir bauen deine Kampagne gemeinsam auf, einen Schritt nach dem anderen.</p></div><div class="brief-grid"><label>Wie heißt deine Kampagne? <span>Pflichtfeld</span><input id="setup-name" data-brief="name" maxlength="120" value="${h(campaign.name)}" placeholder="z. B. Herbstkampagne für Hotels"></label><label>Wer ist der Absender?<input data-brief="sender" maxlength="120" value="${h(brief.sender)}" placeholder="Deine Firma oder Marke"></label><label>Wen willst du ansprechen?<input data-brief="audience" maxlength="240" value="${h(brief.audience)}" placeholder="z. B. inhabergeführte Hotels in Hamburg"></label><label>Was soll nach dem Scan passieren?<select data-brief="goal">${[['chatbot','Einen persönlichen Chatbot ausprobieren'],['appointment','Einen Termin vereinbaren'],['website','Ein Angebot auf einer Website ansehen'],['contact','Kontakt aufnehmen']].map(([v,t])=>`<option value="${v}" ${(brief.goal||'chatbot')===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="brief-wide">Was möchtest du anbieten?<textarea data-brief="offer" maxlength="1000" placeholder="Ein Satz reicht: Welches Problem löst du für diese Unternehmen?">${h(brief.offer)}</textarea></label></div><div class="guide-tip">${icon('info')}<p>Diese Angaben sind dein Briefing. Sie erscheinen nicht automatisch auf dem Mailing. Nur der Kampagnenname ist erforderlich.</p></div>`,
    `<div class="guide-intro"><span class="eyebrow">ETWAS, DAS MAN IN DIE HAND NIMMT.</span><h2>Wir starten mit DIN A5.</h2><p>Eine Karte, zwei Seiten und genug Platz für eine klare Botschaft. Die Vorderseite weckt Interesse. Die Rückseite erklärt dein Angebot und zeigt den nächsten Schritt.</p></div><div class="format-explainer"><div class="format-model"><span class="format-measure">210 mm</span><div><b>A5</b><span>Vorderseite + Rückseite</span></div><small>148 mm</small></div><div><span class="selected-format">${icon('check')} Ausgewählt</span><h3>DIN A5 · Querformat</h3><p>210 × 148 mm · beidseitig<br>Als Karte für einen Umschlag gedacht.</p><ul><li>Wichtige Inhalte mindestens 5 mm vom Rand halten.</li><li>Ideale Bildgröße: etwa 2.480 × 1.748 Pixel bei 300 dpi.</li><li>Für den späteren Druck stimmen wir Beschnitt und Papier separat ab.</li></ul><div class="future-formats">Später: A5 hoch · A6 · DIN lang</div></div></div>`,
    `<div class="guide-intro"><span class="eyebrow">ZWEI SEITEN. EINE KLARE IDEE.</span><h2>Gib deinem Mailing ein Gesicht.</h2><p>Lade fertige Designs hoch oder beginne auf einer leeren Fläche mit Farbe und Text. Du kannst jederzeit zwischen Anleitung und Editor wechseln.</p></div><div class="guide-design-grid">${sideCard('front','Vorderseite','01')}${sideCard('back','Rückseite','02')}</div><div class="guide-tip">${icon('sparkles')}<p><strong>Ein guter Anfang:</strong> Vorn eine große, neugierig machende Aussage. Hinten dein konkreter Nutzen und eine Einladung zum Scannen. PDF, PNG, JPG und WebP funktionieren; eine zweiseitige PDF kann beide Seiten auf einmal liefern.</p></div>`,
    `<div class="guide-intro"><span class="eyebrow">AUS EINER KARTE WIRD DEINE KARTE.</span><h2>Was soll sich je Empfänger ändern?</h2><p>Ein persönliches Feld ist ein Platzhalter. Im fertigen Mailing wird daraus zum Beispiel der Firmenname oder der Link zum jeweiligen Chatbot.</p></div><div class="personalization-example"><div><span>Im Design</span><code>Hallo {{first_name}},</code></div><b>→</b><div><span>Mit deinen Empfängerdaten</span><strong>Hallo Anna,</strong></div></div><div class="guide-side-select"><label for="guide-field-side">Felder hinzufügen auf</label><select id="guide-field-side"><option value="front">Vorderseite</option><option value="back">Rückseite</option></select></div><div class="guide-field-grid">${[['company','type','Firmenname','So sieht der Empfänger sofort: Das ist für mein Unternehmen.'],['salutation','user','Persönliche Ansprache','Aus „Hallo {{first_name}},“ wird eine persönliche Begrüßung.'],['qr','qr','Eigener QR-Code','Jeder Code öffnet genau den Link aus der Empfängerzeile.']].map(([action,ic,title,desc])=>`<button data-guide-action="field-${action}" class="guide-field-card">${icon(ic)}<strong>${title}</strong><p>${desc}</p><span>Feld hinzufügen +</span></button>`).join('')}</div><div class="guide-field-status">${front.fields.length+back.fields.length} Elemente angelegt · ${button('edit-fields','Im Design platzieren ↗')}</div><label class="guide-optional"><input id="skip-personalization" type="checkbox" ${campaign.onboarding?.personalizationSkipped?'checked':''}> Für diese Kampagne brauche ich keine Personalisierung.</label>`,
    `<div class="guide-intro"><span class="eyebrow">FANG MIT EINEM MENSCHEN AN.</span><h2>Dein erster Empfänger.</h2><p>Für den ersten Entwurf reichen eine Firma, ein Vorname und ein Link. Daraus entstehen die persönliche Ansprache und der QR-Code auf deiner Karte.</p></div>${campaign.recipients.length&&!designReady?`<div class="guide-recipient-ready">${icon('check')}<div><strong>${campaign.recipients.length} Empfänger vorhanden</strong><p>${h(campaign.recipients.slice(0,3).map(r=>r.company||'Ohne Firmennamen').join(' · '))}</p></div>${button('recipients','Liste bearbeiten ↗')}</div>`:''}<form id="guide-recipient-form" class="brief-grid"><label>Firmenname <span>Pflichtfeld</span><input name="company" required maxlength="240" value="${h(contact.company||'')}" placeholder="z. B. Nordlicht Hotel"></label><label>Vorname<input name="first_name" maxlength="120" value="${h(contact.first_name||'')}" placeholder="z. B. Anna"></label><label class="brief-wide">Persönlicher Ziel-Link <span>${needsLink?'Pflichtfeld':'Für QR-Codes'}</span><input name="chatbot_url" value="${h(contact.chatbot_url||'')}" type="url" ${needsLink?'required':''} maxlength="1000" placeholder="https://deine-seite.de/persoenliche-demo"><small>Hier kommt ein bereits vorhandener Link hinein. Das Studio erstellt den QR-Code dafür.</small></label><div class="brief-wide guide-recipient-actions"><button type="submit" class="button primary">${designReady?(campaign.recipients.length?'Änderungen speichern & weiter →':'Empfänger speichern & weiter →'):icon('plus')+' Empfänger hinzufügen'}</button>${!designReady?button('csv','Stattdessen CSV importieren'):''}</div></form><div class="guide-tip">${icon('info')}<p>Deine Eingaben werden lokal gespeichert. Weitere Empfänger kannst du später ergänzen.</p></div>`,
    `<div class="guide-intro"><h2>Deine Karte ist bereit zum Ansehen.</h2><p>Öffne die Vorschau und prüfe den Firmennamen, die Ansprache und den QR-Code. Danach kannst du eine PDF herunterladen.</p></div><div class="guide-finish-real"><canvas id="guide-finish-front" aria-label="Deine Karte mit den Daten deines Empfängers"></canvas><p>Dein Design für ${h(campaign.recipients[0]?.company||'deinen Empfänger')}.</p></div><p class="focus-reassurance">Es wird nichts bestellt oder verschickt. Du kannst deinen Entwurf jederzeit ändern.</p>`
  ];
  return `<div class="setup-shell"><div class="setup-content"><div class="focus-topline"><span>DEINE KAMPAGNE · SCHRITT ${designReady?step-3:step+1} VON ${designReady?2:6}</span><span>${designReady?'Design übernommen':h(campaign.name)}</span></div>${!designReady?`<details class="focus-details guide-step-picker"><summary>Schritte im Überblick</summary><nav aria-label="Anleitungsschritte">${GUIDE_STEPS.map((label,i)=>`<button data-guide-step="${i}" aria-current="${i===step?'step':'false'}">${i+1}. ${label}</button>`).join('')}</nav></details>`:''}${bodies[step]}${designReady&&step===4?'':`<div class="guide-bottom">${step===0||designReady&&step===4?'<span></span>':button('previous','← Zurück')}<span>${step===4?'Weitere Empfänger kannst du später hinzufügen.':''}</span>${designReady&&step===4&&!campaign.recipients.length?'':button(step===5?'finish':'next',step===5?'Vorschau öffnen →':'Weiter →',true,step===4&&!campaign.recipients.length?'disabled':'')}</div>`}${step===0?`<details class="focus-details"><summary>Ich möchte zuerst ein Beispiel ausprobieren</summary><p>Die kurze Übung erklärt Namen und QR-Codes an einer fertigen Karte.</p>${button('tutorial','Beispiel ausprobieren')}${button('example','Fertige Kampagne ansehen')}</details>`:''}</div></div>`;
}
