import { icon } from './icons.js';
import { setupProgress } from './core.js';
const h = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
export const GUIDE_STEPS = ['Idee & Ziel', 'Format', 'Dein Design', 'Persönliche Felder', 'Empfänger', 'Ansehen & prüfen'];
const button = (action, label, primary = false, extra = '') => `<button class="button ${primary ? 'primary' : ''}" data-guide-action="${action}" ${extra}>${label}</button>`;
export function guideHTML(campaign) {
  const step = campaign.onboarding?.step || 0;
  const progress = setupProgress(campaign);
  const brief = campaign.brief || {};
  const front = campaign.sides.front, back = campaign.sides.back;
  const sideCard = (s, label, number) => `<article class="guide-design-card"><div class="guide-design-thumb"><canvas id="guide-${s}"></canvas>${campaign.sides[s].background.kind === 'blank' && !campaign.sides[s].fields.length ? `<div class="empty-design-label">${icon('upload')}<strong>${label}</strong><span>Noch ganz unbeschrieben.</span></div>` : ''}</div><div class="guide-design-caption"><b>${number} / ${label}</b><span>${campaign.sides[s].background.kind === 'image' ? h(campaign.sides[s].background.name) : campaign.sides[s].fields.length ? `${campaign.sides[s].fields.length} eigene Elemente` : 'Dein Platz für eine gute Botschaft'}</span></div><div class="guide-design-actions">${button('upload-'+s, icon('upload')+' Design hochladen',true)}${button('edit-'+s,'Selbst gestalten ↗')}</div></article>`;
  const bodies = [
    `<div class="guide-intro"><span class="eyebrow">ERST DIE IDEE. DANN DAS MAILING.</span><h2>Wen möchtest du erreichen?</h2><p>Du brauchst noch kein fertiges Design und keine Empfängerliste. Wir bauen deine Kampagne gemeinsam auf, einen Schritt nach dem anderen.</p></div><div class="brief-grid"><label>Wie heißt deine Kampagne? <span>Pflichtfeld</span><input id="setup-name" data-brief="name" maxlength="120" value="${h(campaign.name)}" placeholder="z. B. Herbstkampagne für Hotels"></label><label>Wer ist der Absender?<input data-brief="sender" maxlength="120" value="${h(brief.sender)}" placeholder="Deine Firma oder Marke"></label><label>Wen willst du ansprechen?<input data-brief="audience" maxlength="240" value="${h(brief.audience)}" placeholder="z. B. inhabergeführte Hotels in Hamburg"></label><label>Was soll nach dem Scan passieren?<select data-brief="goal">${[['chatbot','Einen persönlichen Chatbot ausprobieren'],['appointment','Einen Termin vereinbaren'],['website','Ein Angebot auf einer Website ansehen'],['contact','Kontakt aufnehmen']].map(([v,t])=>`<option value="${v}" ${(brief.goal||'chatbot')===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="brief-wide">Was möchtest du anbieten?<textarea data-brief="offer" maxlength="1000" placeholder="Ein Satz reicht: Welches Problem löst du für diese Unternehmen?">${h(brief.offer)}</textarea></label></div><div class="guide-tip">${icon('info')}<p>Diese Angaben sind dein Briefing. Sie erscheinen nicht automatisch auf dem Mailing. Nur der Kampagnenname ist erforderlich.</p></div>`,
    `<div class="guide-intro"><span class="eyebrow">ETWAS, DAS MAN IN DIE HAND NIMMT.</span><h2>Wir starten mit DIN A5.</h2><p>Eine Karte, zwei Seiten und genug Platz für eine klare Botschaft. Die Vorderseite weckt Interesse. Die Rückseite erklärt dein Angebot und zeigt den nächsten Schritt.</p></div><div class="format-explainer"><div class="format-model"><span class="format-measure">210 mm</span><div><b>A5</b><span>Vorderseite + Rückseite</span></div><small>148 mm</small></div><div><span class="selected-format">${icon('check')} Ausgewählt</span><h3>DIN A5 · Querformat</h3><p>210 × 148 mm · beidseitig<br>Als Karte für einen Umschlag gedacht.</p><ul><li>Wichtige Inhalte mindestens 5 mm vom Rand halten.</li><li>Ideale Bildgröße: etwa 2.480 × 1.748 Pixel bei 300 dpi.</li><li>Für den späteren Druck stimmen wir Beschnitt und Papier separat ab.</li></ul><div class="future-formats">Später: A5 hoch · A6 · DIN lang</div></div></div>`,
    `<div class="guide-intro"><span class="eyebrow">ZWEI SEITEN. EINE KLARE IDEE.</span><h2>Gib deinem Mailing ein Gesicht.</h2><p>Lade fertige Designs hoch oder beginne auf einer leeren Fläche mit Farbe und Text. Du kannst jederzeit zwischen Anleitung und Editor wechseln.</p></div><div class="guide-design-grid">${sideCard('front','Vorderseite','01')}${sideCard('back','Rückseite','02')}</div><div class="guide-tip">${icon('sparkles')}<p><strong>Ein guter Anfang:</strong> Vorn eine große, neugierig machende Aussage. Hinten dein konkreter Nutzen und eine Einladung zum Scannen. PDF, PNG, JPG und WebP funktionieren; eine zweiseitige PDF kann beide Seiten auf einmal liefern.</p></div>`,
    `<div class="guide-intro"><span class="eyebrow">AUS EINER KARTE WIRD DEINE KARTE.</span><h2>Was soll sich je Empfänger ändern?</h2><p>Ein persönliches Feld ist ein Platzhalter. Im fertigen Mailing wird daraus zum Beispiel der Firmenname oder der Link zum jeweiligen Chatbot.</p></div><div class="personalization-example"><div><span>Im Design</span><code>Hallo {{first_name}},</code></div><b>→</b><div><span>Mit deinen Empfängerdaten</span><strong>Hallo Anna,</strong></div></div><div class="guide-side-select"><label for="guide-field-side">Felder hinzufügen auf</label><select id="guide-field-side"><option value="front">Vorderseite</option><option value="back">Rückseite</option></select></div><div class="guide-field-grid">${[['company','type','Firmenname','So sieht der Empfänger sofort: Das ist für mein Unternehmen.'],['salutation','user','Persönliche Ansprache','Aus „Hallo {{first_name}},“ wird eine persönliche Begrüßung.'],['qr','qr','Eigener QR-Code','Jeder Code öffnet genau den Link aus der Empfängerzeile.']].map(([action,ic,title,desc])=>`<button data-guide-action="field-${action}" class="guide-field-card">${icon(ic)}<strong>${title}</strong><p>${desc}</p><span>Feld hinzufügen +</span></button>`).join('')}</div><div class="guide-field-status">${front.fields.length+back.fields.length} Elemente angelegt · ${button('edit-fields','Im Design platzieren ↗')}</div><label class="guide-optional"><input id="skip-personalization" type="checkbox" ${campaign.onboarding?.personalizationSkipped?'checked':''}> Für diese Kampagne brauche ich keine Personalisierung.</label>`,
    `<div class="guide-intro"><span class="eyebrow">FANG MIT EINEM MENSCHEN AN.</span><h2>Dein erster Empfänger.</h2><p>Zum Ausprobieren reicht ein Kontakt. Der Firmenname füllt deine Textfelder. Der vollständige persönliche Link wird zum QR-Code. Später kannst du weitere Kontakte als CSV hinzufügen.</p></div>${campaign.recipients.length?`<div class="guide-recipient-ready">${icon('check')}<div><strong>${campaign.recipients.length} Empfänger vorhanden</strong><p>${h(campaign.recipients.slice(0,3).map(r=>r.company||'Ohne Firmennamen').join(' · '))}</p></div>${button('recipients','Liste bearbeiten ↗')}</div>`:''}<form id="guide-recipient-form" class="brief-grid"><label>Firmenname <span>Pflichtfeld</span><input name="company" required maxlength="240" placeholder="z. B. Nordlicht Hotel"></label><label>Vorname<input name="first_name" maxlength="120" placeholder="z. B. Anna"></label><label class="brief-wide">Persönlicher Ziel-Link <span>Für QR-Codes</span><input name="chatbot_url" type="url" maxlength="1000" placeholder="https://deine-seite.de/persoenliche-demo"><small>Hier kommt ein bereits vorhandener Link hinein. Das Studio erstellt den QR-Code dafür.</small></label><div class="brief-wide guide-recipient-actions"><button type="submit" class="button primary">${icon('plus')} Empfänger hinzufügen</button>${button('csv','Stattdessen CSV importieren')}</div></form><div class="guide-tip">${icon('info')}<p>Keine erfundenen Kontakte: Deine Kampagne enthält nur Empfänger, die du selbst einträgst oder importierst. Fehlende Werte kannst du später ergänzen.</p></div>`,
    `<div class="guide-intro"><span class="eyebrow">JETZT WIRD DEINE IDEE GREIFBAR.</span><h2>Einmal drehen. Alles prüfen.</h2><p>In der 3D-Ansicht kannst du dein Mailing in die Hand nehmen – virtuell. Drehe es auf die Rückseite, schiebe es hin und her und prüfe die Personalisierung pro Empfänger.</p></div><div class="guide-finish-grid"><div class="guide-finish-art"><div class="finish-card back-card">${icon('qr')}</div><div class="finish-card front-card"><span>${h(brief.sender||'DEINE MARKE')}</span><strong>Dein nächster<br>guter Kontakt.</strong><b>↗</b></div></div><div><h3>Dein Entwurf wartet auf dich.</h3><div class="guide-summary">${GUIDE_STEPS.slice(0,5).map((t,i)=>`<div>${icon(progress[i]?'check':'info')}<span>${t}</span><b>${progress[i]?'Vorbereitet':'Noch offen'}</b></div>`).join('')}</div>${button('three-d',icon('eye')+' Mailing in 3D ansehen',true)}${button('proof','2D-Ansicht & Prüfung')}</div></div><div class="guide-tip">${icon('lock')}<p>Du kannst alles weiter ändern. „Anleitung abschließen“ markiert nur deinen Einstieg als erledigt. Es wird kein Mailing bestellt oder verschickt.</p></div>`
  ];
  return `<div class="setup-shell"><aside class="setup-rail"><div class="eyebrow">DEINE ERSTE KAMPAGNE</div><h2>Von der Idee<br>zum Mailing.</h2><p>In deinem Tempo.<br>Jeder Schritt wird gespeichert.</p><nav aria-label="Anleitungsschritte">${GUIDE_STEPS.map((label,i)=>`<button data-guide-step="${i}" class="${i===step?'active':''} ${progress[i]?'complete':''}" aria-current="${i===step?'step':'false'}"><span>${progress[i]?icon('check'):String(i+1).padStart(2,'0')}</span><div><strong>${label}</strong><small>${i===step?'Du bist hier':progress[i]?'Vorbereitet':'Noch vor dir'}</small></div></button>`).join('')}</nav><div class="setup-rail-note">${icon('lock')}<span>Dein eigener Entwurf.<br>Keine Beispieldaten.</span></div></aside><div class="setup-content"><div class="setup-progress"><span>SCHRITT ${step+1} VON 6</span><div>${GUIDE_STEPS.map((_,i)=>`<b class="${i<=step?'filled':''}"></b>`).join('')}</div></div>${bodies[step]}<div class="guide-bottom"><button class="button" data-guide-action="previous" ${step===0?'disabled':''}>← Zurück</button><span>${step===2?'Du kannst die Designs auch später ergänzen.':step===4?'Weitere Empfänger kannst du jederzeit hinzufügen.':'Du kannst jeden Schritt später wieder öffnen.'}</span><button class="button primary" data-guide-action="${step===5?'finish':'next'}">${step===5?'Anleitung abschließen':'Weiter'} ${step===5?'✓':'→'}</button></div></div></div>`;
}
