import {isSelfmailer} from './formats.js';
import {renderCanvas} from './render.js';
import {Mailing3D} from './three-d.js';
import {pointOnQuad,faceToSpread,spreadToFace} from './fold-coordinates.js';
// Picking and pins use the same immutable review snapshot and spread coordinates.
export function mountReviewFold(root,project,{initialState=null,flatSelectors=[],comments=[],resolved=new Set(),editable=true,onMark=()=>{},onComment=()=>{}}={}){
 if(!root||!isSelfmailer(project))return null;
 if(!document.querySelector('link[data-fold-styles]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/assets/selfmailer-3d.css';link.dataset.foldStyles='';document.head.append(link);}
 const shell=document.createElement('div');shell.className='review-fold';
 shell.innerHTML='<div class="review-fold-heading"><strong>Dein Mailing. Dein Feedback.</strong><p class="review-fold-hint"></p></div><div class="review-face-tools" role="group" aria-label="Mailingseite"><button type="button" data-review-face="cover">Titelseite</button><button type="button" data-review-face="inside-top">Innenseiten</button><button type="button" data-review-face="postal">Anschrift</button><button type="button" data-review-zoom="out" aria-label="Verkleinern">−</button><button type="button" data-review-zoom="in" aria-label="Vergrößern">+</button></div><div class="review-fold-stage" tabindex="0" role="group" aria-label="Mailing: Ziehen zum Drehen, eine Stelle zum Kommentieren anklicken. Mit Enter die Mitte markieren."><div class="mailing-3d-card"><canvas data-fold-source="front" hidden></canvas><canvas data-fold-source="back" hidden></canvas></div></div><p class="review-fold-help" role="status">Design wird geladen …</p>';
 root.prepend(shell);const stage=shell.querySelector('.review-fold-stage'),help=shell.querySelector('.review-fold-help'),flat=flatSelectors.flatMap(selector=>[...root.querySelectorAll(selector)]),hiddenState=new Map(flat.map(n=>[n,n.hidden])),events=new AbortController();for(const node of flat)node.hidden=true;
 let disposed=false,ready=false,gesture=null,pendingTap=null;const viewer=new Mailing3D(stage);viewer.setSelfmailer(true);if(initialState){Object.assign(viewer.state,initialState.state);viewer.fold.set(initialState.open);viewer.paint();}stage.classList.toggle('review-readonly',!editable);
 const hint=editable?'Eine Stelle anklicken und kommentieren. Ziehen zum Drehen.':'Freigegebener Stand · Ziehen zum Drehen und Aufklappen.';shell.querySelector('.review-fold-hint').textContent=hint;
 const faces=new Map();for(const canvas of stage.querySelectorAll('[data-fold-face]')){const surface=canvas.parentElement,name=canvas.dataset.foldFace;surface.dataset.reviewSurface=name;for(const [x,y] of [[0,0],[1,0],[1,1],[0,1]]){const probe=document.createElement('i');probe.className='fold-corner';probe.style.left=x*100+'%';probe.style.top=y*100+'%';surface.append(probe);}faces.set(name,surface);}
 function pin(p,label,cls=''){const surface=faces.get(p.face),el=document.createElement('button');el.type='button';el.className='fold-comment-pin '+cls;el.style.left=p.x*100+'%';el.style.top=p.y*100+'%';el.textContent=label;surface.append(el);return el;}
 function clearPoint(){shell.querySelectorAll('.fold-pending-pin').forEach(n=>n.remove());}
 comments.forEach((c,i)=>{if(!c.side)return;const el=pin(spreadToFace(c),String(i+1),resolved.has(c.id)?'resolved':'');el.dataset.foldComment=c.id;el.setAttribute('aria-label','Kommentar '+(i+1)+' ansehen');el.addEventListener('pointerdown',e=>e.stopPropagation());el.onclick=e=>{e.stopPropagation();onComment(c);};});
 function showFace(face){viewer.fold.stop();viewer.state.panX=viewer.state.panY=0;if(face==='cover')viewer.front();else if(face==='postal')viewer.back();else{viewer.state.x=-12;viewer.state.y=-12;viewer.fold.animate(100);viewer.paint();}}
 function markAt(face,x,y){if(!ready||!editable)return;const surface=faces.get(face);if(!surface)return;const points=[...surface.querySelectorAll('.fold-corner')].map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y};}),p=pointOnQuad(points,x,y);if(!p)return;clearPoint();const el=pin({face,...p},'+','fold-pending-pin');el.tabIndex=-1;el.setAttribute('aria-hidden','true');onMark(faceToSpread(face,p));}
 stage.addEventListener('pointerdown',e=>{if(e.target.closest('.fold-comment-pin'))return;pendingTap=null;if(gesture){gesture.cancelled=true;return;}const surface=e.target.closest('[data-review-surface]');gesture={id:e.pointerId,x:e.clientX,y:e.clientY,face:surface?.dataset.reviewSurface,cancelled:false};},{signal:events.signal});
 stage.addEventListener('pointermove',e=>{if(gesture&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>7)gesture.cancelled=true;},{signal:events.signal});
 stage.addEventListener('pointerup',e=>{if(!gesture||e.pointerId!==gesture.id)return;const g=gesture;gesture=null;if(!g.cancelled&&g.face)pendingTap={face:g.face,x:e.clientX,y:e.clientY};},{signal:events.signal});
 stage.addEventListener('pointercancel',()=>{gesture=null;pendingTap=null;},{signal:events.signal});
 // Open only on the completed click, so a synthesized touch click cannot hit the new dialog.
 stage.addEventListener('click',e=>{const tap=pendingTap;pendingTap=null;if(!tap||e.target.closest('.fold-comment-pin'))return;e.preventDefault();e.stopPropagation();markAt(tap.face,tap.x,tap.y);},{signal:events.signal});
 stage.addEventListener('keydown',e=>{if(e.target!==stage||e.key!=='Enter')return;e.preventDefault();const r=stage.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height*.48,surface=document.elementFromPoint(x,y)?.closest('[data-review-surface]');if(surface)markAt(surface.dataset.reviewSurface,x,y);},{signal:events.signal});
 document.addEventListener('close',clearPoint,{capture:true,signal:events.signal});
 shell.querySelectorAll('[data-review-face]').forEach(b=>b.onclick=()=>showFace(b.dataset.reviewFace));shell.querySelectorAll('[data-review-zoom]').forEach(b=>b.onclick=()=>viewer.zoom(b.dataset.reviewZoom==='in'?1.15:1/1.15));
 const pending=(async()=>{const front=shell.querySelector('[data-fold-source=front]'),back=shell.querySelector('[data-fold-source=back]');await Promise.all([renderCanvas(front,project,'front',project.recipients[0],{scale:5}),renderCanvas(back,project,'back',project.recipients[0],{scale:5})]);if(!disposed){viewer.setSpreads(front,back);ready=true;help.textContent=editable?'Deine Markierungen bleiben direkt an der richtigen Stelle des Mailings.':'Dieser Designstand ist bestätigt.';}})().catch(()=>{if(!disposed){viewer.setVisible(false);stage.hidden=true;for(const [n,hidden] of hiddenState)n.hidden=hidden;help.textContent='Die Falzansicht ist gerade nicht verfügbar. Du kannst unten auf dem Druckbogen kommentieren.';}});
 return {ready:pending,snapshot:()=>({state:{...viewer.state},open:viewer.fold.open}),promptMark(){viewer.fold.stop();help.textContent='Tippe oder klicke jetzt direkt auf die Stelle im Mailing.';stage.scrollIntoView({behavior:'smooth',block:'center'});stage.focus({preventScroll:true});},showPoint(p){const point=spreadToFace(p);showFace(point.face);stage.scrollIntoView({behavior:'smooth',block:'center'});},destroy(){disposed=true;events.abort();viewer.destroy();shell.remove();for(const [n,hidden] of hiddenState)n.hidden=hidden;}};
}
