import {resolveText} from './core.js';
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const TUTORIAL_STEPS=['Dein Beispiel','Design & Format','Platzhalter verstehen','Text ausprobieren','Beispieldaten ändern','Persönliche QR-Codes','In 3D ansehen','Prüfen & exportieren'];
const btn=(action,label,primary=false)=>`<button class="button ${primary?'primary':''}" data-tutorial-action="${action}">${label}</button>`;
export function tutorialHTML(campaign,index=0){
 const step=campaign.tutorial.step,r=campaign.recipients[index]||{},field=campaign.sides.back.fields.find(f=>f.id===campaign.tutorial.fieldId);
 if(!campaign.recipients.length||!field)return `<div class="tutorial-content"><header class="tutorial-intro"><h2>Deine Übungsdaten haben sich verändert.</h2><p>Der Übungstext oder die Beispielkontakte wurden im Editor entfernt. Du kannst diese Kampagne weiter frei bearbeiten oder ein neues Tutorial mit vollständigen Beispieldaten starten. Dein bisheriger Entwurf bleibt erhalten.</p></header>${btn('fresh','Neues Tutorial mit Beispieldaten starten',true)}${btn('skip','Tutorial überspringen ↗')}</div>`;
 const text=field?.text||'Hallo {{first_name}},';
 const selector=`<label class="tutorial-person-label">Beispielkontakt<select id="tutorial-person">${campaign.recipients.map((r,i)=>`<option value="${i}" ${index===i?'selected':''}>${h(r.first_name)} · ${h(r.company)}</option>`).join('')}</select></label>`;
 const proof=side=>`<figure class="tutorial-proof"><canvas id="tutorial-${side}" aria-label="${side==='front'?'Vorderseite':'Rückseite'} für ${h(r.company)}"></canvas><figcaption>${side==='front'?'Vorderseite':'Rückseite'} · echte Vorschau für <b>${h(r.company)}</b></figcaption></figure>`;
 const intro=(title,copy)=>`<header class="tutorial-intro"><h2 tabindex="-1" id="tutorial-title">${title}</h2><p>${copy}</p></header>`;
 const mapping=[['company','Firmenname'],['first_name','Vorname'],['salutation','Ansprache'],['chatbot_url','Persönlicher Link']];
 const bodies=[
 `${intro('Wir bauen ein Mailing für Anna.','Deine erste Kampagne beginnt mit einer kurzen Übung. Du lernst mit einer fertigen Fotokampagne. Alle Namen und Anschriften sind erfunden. Du darfst hier alles ausprobieren; deine bisherigen Kampagnen bleiben erhalten.')}<div class="tutorial-contacts">${campaign.recipients.map((p,i)=>`<button data-tutorial-person="${i}" class="${i===index?'active':''}" aria-pressed="${i===index}"><span>${h((p.first_name||'?').slice(0,1))}</span><strong>${h(p.first_name)}</strong><p>${h(p.company)}</p><small>Beispielkontakt ${i+1}</small></button>`).join('')}</div>${proof('front')}<div class="tutorial-note"><strong>Das lernst du:</strong> Design ansehen, Platzhalter einsetzen, Namen verändern, QR-Codes verstehen und eine personalisierte PDF exportieren.</div>`,
 `${intro('Eine Karte. Zwei Seiten.','Vorn weckst du Interesse. Hinten erklärst du dein Angebot und zeigst den nächsten Schritt. Das Beispiel ist DIN A5 quer: 210 × 148 mm.')}${selector}<div class="tutorial-spread">${proof('front')}${proof('back')}</div><div class="tutorial-note">Foto, Texte und farbige Flächen sind einzelne Elemente. Im Editor kannst du sie anklicken, verschieben und ändern. Ein vorhandenes Design lädst du als PDF, PNG, JPG oder WebP hoch.</div><div class="tutorial-actions">${btn('design','Design im Editor ausprobieren ↗')}${btn('upload','Eigenes Design hochladen ↗')}</div>`,
 `${intro('Aus {{company}} wird ein Firmenname.','Ein Platzhalter ist ein wiederverwendbarer Verweis auf eine Spalte deiner Empfängerliste. Die zwei geschweiften Klammern zeigen: Hier setzt Kontaktstoff den passenden Wert ein.')}${selector}<div class="tutorial-mapping"><div class="tutorial-mapping-head"><span>Platzhalter im Design</span><span>Wert für diesen Kontakt</span></div>${mapping.map(([key,label])=>`<div><span><small>${label}</small><code>{{${key}}}</code></span><span class="tutorial-map-value">${h(r[key]||'Noch leer')}</span></div>`).join('')}</div><div class="tutorial-note"><strong>Probiere den Kontaktwechsel oben aus.</strong> Aus Anna wird Jonas, aus Nordlicht Immobilien wird Studio Hafenblick. Der Platzhalter bleibt derselbe. Nur sein Inhalt wechselt.</div>`,
 `${intro('Schreib einen Text mit Platzhaltern.','Hier bearbeitest du das echte Ansprachefeld auf der Rückseite. Klicke einen Platzhalter an oder schreibe selbst. Rechts siehst du sofort den Text für deinen gewählten Kontakt.')}${selector}<div class="tutorial-playground"><div><label for="tutorial-text">Dein Text im Design</label><textarea id="tutorial-text" maxlength="180" spellcheck="false">${h(text)}</textarea><div class="tutorial-tokens">${['first_name','company','salutation'].map(k=>`<button data-tutorial-token="${k}">{{${k}}}</button>`).join('')}</div><p>Beispiel: <code>Hallo {{first_name}},</code><br>Fest geschriebene Wörter bleiben für alle gleich.</p></div><div class="tutorial-result"><span>SO LIEST ES ${h(r.first_name||'DEIN KONTAKT').toUpperCase()}</span><strong id="tutorial-resolved">${h(resolveText(text,r))}</strong><p id="tutorial-text-help" role="status"></p></div></div>${proof('back')}<div class="tutorial-actions">${btn('reset-text','Beispieltext wiederherstellen')}</div>`,
 `${intro('Ändere Anna in deinen eigenen Beispielnamen.','Ein Design greift immer auf die aktuelle Empfängerzeile zu. Ändere die Angaben unten und verlasse das Eingabefeld: Vorschau und Platzhalter werden aktualisiert.')}${selector}<div class="tutorial-data-form"><label>Vorname<input data-tutorial-data="first_name" maxlength="120" value="${h(r.first_name)}"></label><label>Firmenname<input data-tutorial-data="company" maxlength="240" value="${h(r.company)}"></label><label class="tutorial-wide">Ansprache<input data-tutorial-data="salutation" maxlength="240" value="${h(r.salutation)}"></label></div><div class="tutorial-note">Die Ansprache ist eine eigene Spalte: <code>{{salutation}}</code> übernimmt ihren vollständigen Inhalt. <code>Hallo {{first_name}},</code> setzt nur den Vornamen ein. Im Tutorial passen wir beim Ändern des Vornamens auch die Ansprache an.</div>${proof('front')}<div class="tutorial-csv"><h3>Später: viele Kontakte auf einmal</h3><p>Eine CSV-Datei hat Spaltennamen in der ersten Zeile und einen Kontakt pro weiterer Zeile. Die Spaltennamen sind zugleich deine Platzhalter.</p><pre>company;first_name;salutation;chatbot_url
Nordlicht Immobilien;Anna;Hallo Anna,;https://chattastic.de/?beispiel=nordlicht
Studio Hafenblick;Jonas;Hallo Jonas,;https://chattastic.de/?beispiel=hafenblick</pre><div class="tutorial-actions">${btn('csv','Beispieldaten als CSV herunterladen')}${btn('recipients','Empfängerliste öffnen ↗')}</div></div>`,
 `${intro('Ein Kontakt. Ein Link. Ein QR-Code.','Das QR-Feld enthält {{chatbot_url}}. Kontaktstoff liest den Link des gewählten Empfängers und erzeugt genau dafür einen scannbaren Code.')}${selector}<div class="tutorial-qr-layout"><div><span class="tutorial-label">IM QR-FELD</span><code>{{chatbot_url}}</code><label for="tutorial-url">Ziel-Link für ${h(r.first_name)}<input id="tutorial-url" type="url" maxlength="1000" value="${h(r.chatbot_url)}"></label><p>Trage später den bereits vorhandenen persönlichen Chatbot-Link ein. Dieses Studio erstellt den QR-Code, nicht den Chatbot.</p><p class="tutorial-note">Die Beispiel-Links sind unterschiedlich, öffnen aber alle die chattastic-Startseite. Es sind keine individuellen Demo-Chatbots.</p></div><div class="tutorial-qr-card"><canvas id="tutorial-qr" aria-label="QR-Code für den aktuellen Beispielkontakt"></canvas><strong>${h(r.company)}</strong><p id="tutorial-qr-status" role="status"></p></div></div>${proof('back')}`,
 `${intro('Jetzt nimmst du dein Mailing virtuell in die Hand.','Die 3D-Ansicht zeigt deine tatsächlichen Designseiten. Ziehen dreht die Karte. Mit „Mailing wenden“ siehst du die Rückseite. „Verschieben“ bewegt die ganze Karte.')}${selector}${proof('front')}<ol class="tutorial-instructions"><li>Öffne die 3D-Ansicht und wende die Karte.</li><li>Wechsle den Beispielkontakt und vergleiche Namen und QR-Code.</li><li>Über „Zurück zum Tutorial“ kommst du genau hierher zurück.</li></ol>${btn('three-d','Jetzt in 3D ausprobieren ↗',true)}`,
 `${intro('Dein erstes persönliches Mailing ist bereit zur Prüfung.','Du kennst jetzt den Weg von einer Empfängerzeile über Platzhalter zum fertigen Design. Prüfe vor der Übergabe alle Kontakte und exportiere eine Ansicht.')}${selector}${proof('back')}<div class="tutorial-final-cards"><article><h3>1. Alle Kontakte prüfen</h3><p>Findet fehlende Werte, ungültige Links und Texte, die nicht in ihr Feld passen. Ein korrekt geschriebener Link ist noch kein Erreichbarkeitstest.</p>${btn('audit','Kampagne prüfen ↗')}</article><article><h3>2. Persönliche PDF ansehen</h3><p>Vorder- und Rückseite mit den Daten des ausgewählten Kontakts. Beim ZIP-Paket kommen CSV, Projekt und Prüfbericht hinzu.</p>${btn('pdf','PDF für diesen Kontakt herunterladen',true)}${btn('package','Zur Kampagnenübergabe ↗')}</article></div><div class="tutorial-note">Die PDFs sind RGB-Ansichten ohne Beschnitt. Druckfreigabe und Versand erfolgen separat. Sichere dein Projekt als Datei, bevor du Browserdaten löschst.</div><div class="tutorial-actions">${btn('blank','Eigene Kampagne von null starten ↗')}${btn('finish','Tutorial abschließen',true)}</div>`
 ];
 return `<div class="tutorial-shell"><aside class="tutorial-nav"><span class="eyebrow">MITMACH-TUTORIAL</span><h2>Persönlich.<br>Schritt für Schritt.</h2><p>Mit echten Designseiten und fiktiven Kontakten.</p><nav aria-label="Tutorialschritte">${TUTORIAL_STEPS.map((label,i)=>`<button data-tutorial-step="${i}" class="${i===step?'active':''}" aria-current="${i===step?'step':'false'}"><span>${i+1}</span>${label}</button>`).join('')}</nav><p>Dein Fortschritt wird gespeichert. Du kannst jederzeit weiterbearbeiten.</p></aside><div class="tutorial-content"><div class="tutorial-skip"><span>Erst ausprobieren. Dann deine eigene Kampagne gestalten.</span>${btn('skip','Tutorial überspringen ↗')}</div><div class="tutorial-progress">SCHRITT ${step+1} VON ${TUTORIAL_STEPS.length}<span>${TUTORIAL_STEPS[step]}</span></div>${bodies[step]}<div class="tutorial-bottom">${step===0?'<button class="button" disabled>← Zurück</button>':btn('previous','← Zurück')}<span>${step===7?'Du kannst jeden Schritt wiederholen.':'Probiere es aus. Dann geht’s weiter.'}</span>${step<7?btn('next','Weiter →',true):btn('restart','Noch einmal ansehen ↺')}</div></div></div>`;
}
