import {resolveText} from './core.js';
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const TUTORIAL_STEPS=['Karte ansehen','Namen ändern','Link einsetzen','Eigenes Mailing'];
const btn=(action,label,primary=false)=>`<button class="button ${primary?'primary':''}" data-tutorial-action="${action}">${label}</button>`;
export function tutorialHTML(campaign,index=0){
 const step=campaign.tutorial.step,r=campaign.recipients[index]||{},field=campaign.sides.back.fields.find(f=>f.id===campaign.tutorial.fieldId);
 if(!campaign.recipients.length||!field)return `<div class="tutorial-content"><header class="tutorial-intro"><h2>Deine Übung wurde verändert.</h2><p>Starte mit einem vollständigen Beispiel neu. Dein bisheriger Entwurf bleibt erhalten.</p></header>${btn('fresh','Beispiel neu starten',true)}${btn('skip','Ohne Anleitung starten')}</div>`;
 const proof=side=>`<figure class="tutorial-proof"><canvas id="tutorial-${side}" aria-label="${side==='front'?'Vorderseite':'Rückseite'} deines Beispiels"></canvas><figcaption>${side==='front'?'Vorderseite':'Rückseite'} · DIN A5 · Beispieldesign</figcaption></figure>`;
 const intro=(title,copy)=>`<header class="tutorial-intro"><h2 tabindex="-1" id="tutorial-title">${title}</h2><p>${copy}</p></header>`;
 const bodies=[
 `${intro('Fangen wir mit einer fertigen Karte an.','Du musst noch nichts gestalten. Wir zeigen dir an diesem Beispiel, wie ein Mailing persönlich wird. Danach kannst du das Design für deine eigene Kampagne übernehmen.')}${proof('front')}<p class="focus-reassurance">Das ist eine Übung mit erfundenen Kontakten. Es wird nichts verschickt.</p>`,
 `${intro('Mach aus Anna einen anderen Namen.','Ändere den Vornamen oder die Firma. Auf der Karte siehst du sofort, was sich verändert.')}<div class="focus-edit-grid"><div><div class="tutorial-data-form"><label>Vorname<input data-tutorial-data="first_name" maxlength="120" value="${h(r.first_name)}"></label><label>Firmenname<input data-tutorial-data="company" maxlength="240" value="${h(r.company)}"></label></div><div class="focus-token-example"><span>IM DESIGN STEHT</span><code id="tutorial-pattern">${h(field.text)}</code><span>AUF DER KARTE STEHT</span><strong id="tutorial-resolved">${h(resolveText(field.text,r))}</strong></div><details class="focus-details"><summary>Was ist ein Platzhalter?</summary><p><code>{{first_name}}</code> bedeutet „Hier den Vornamen einsetzen“. Der gleiche Text wird so für jeden Empfänger persönlich.</p><label for="tutorial-text">Ansprache selbst ausprobieren</label><textarea id="tutorial-text" maxlength="180">${h(field.text)}</textarea><p id="tutorial-text-help" role="status"></p>${btn('reset-text','Beispieltext wiederherstellen')}</details></div>${proof('back')}</div>`,
 `${intro('Wohin soll der QR-Code führen?','Jeder Empfänger kann einen eigenen Link bekommen. Der Code wird automatisch daraus erstellt. Probiere hier einen Link aus.')}<div class="tutorial-qr-layout"><div><label for="tutorial-url">Link für diesen Empfänger<input id="tutorial-url" type="url" maxlength="1000" value="${h(r.chatbot_url)}" placeholder="https://deine-website.de/demo"></label><p class="focus-reassurance">Der Beispiel-Link öffnet chattastic.de. Für deine Kampagne verwendest du später deinen eigenen Chatbot- oder Website-Link.</p><details class="focus-details"><summary>Wie funktioniert das je Empfänger?</summary><p>Im QR-Feld steht <code>{{chatbot_url}}</code>. Für jeden Kontakt wird dessen Link eingesetzt. Den Chatbot oder die Zielseite legst du außerhalb dieses Studios an.</p></details></div><div class="tutorial-qr-card"><canvas id="tutorial-qr" aria-label="QR-Code für den Beispielkontakt"></canvas><canvas id="tutorial-back" hidden></canvas><strong>Dein QR-Code</strong><p id="tutorial-qr-status" role="status"></p></div></div>`,
 `${intro('Jetzt kannst du dein eigenes Mailing starten.','Wir übernehmen dieses Design für dich. Die Beispielkontakte werden nicht mitgenommen. Als Nächstes trägst du deinen ersten echten Empfänger ein.')}<div class="tutorial-spread">${proof('front')}${proof('back')}</div><details class="focus-details"><summary>Das Beispiel noch genauer ansehen</summary><div class="tutorial-actions">${btn('three-d','Karte in 3D drehen')}${btn('pdf','Beispiel-PDF herunterladen')}</div></details>`
 ];
 const next=['Jetzt den Namen ändern →','Weiter zum QR-Code →','Mein Ergebnis ansehen →','Design übernehmen & starten →'];
 return `<div class="tutorial-shell"><div class="tutorial-content"><div class="focus-topline"><span>BEISPIEL AUSPROBIEREN · ${step+1} VON 4</span>${btn('skip','Überspringen')}</div><div class="focus-progress" aria-label="Fortschritt">${TUTORIAL_STEPS.map((label,i)=>`<span class="${i===step?'current':i<step?'done':''}" ${i===step?'aria-current="step"':''}><b>${i+1}</b>${label}</span>`).join('')}</div>${bodies[step]}<div class="tutorial-bottom">${step===0?'<span></span>':btn('previous','← Zurück')}${btn(step===3?'own':'next',next[step],true)}</div></div></div>`;
}
