import {mkdir,writeFile} from 'node:fs/promises';
import {createClientCampaign} from '../studio/src/client-campaigns.js';
import {CLIENT_PAGES} from '../clients/catalog.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function buildClientPages(){
 for(const c of CLIENT_PAGES){
  if(!/^[a-z0-9-]+$/.test(c.id))throw Error('Invalid customer slug');
  const people=createClientCampaign(c.id).recipients;
  const html=`<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Ein persönlicher Kampagnenvorschlag von Kontaktstoff für ${esc(c.name)}. Mit Mailing-Design, 3D-Vorschau und Pilotkonzept."><title>${esc(c.name)} × Kontaktstoff · Eure Mailing-Idee</title><link rel="icon" href="/assets/mark.svg"><link rel="stylesheet" href="/clients/base.css"><link rel="stylesheet" href="/clients/style.css"></head>
<body class="client-page" data-client="${c.id}"><a class="skip-link" href="#main">Zum Inhalt</a>
<header class="client-header"><nav class="client-container"><a class="wordmark" href="/">kontaktstoff<span>.</span></a><span class="collab-name">× ${esc(c.name)}</span><a class="button client-button" href="#anfrage">Pilot planen ↗</a></nav></header>
<main id="main">
<section class="client-hero client-container"><div class="client-eyebrow"><span></span> EINE IDEE. PERSÖNLICH FÜR EUCH.</div><p class="client-addressee">Für ${esc(c.addressee)}</p><h1>${esc(c.title)}</h1><p class="client-intro">${esc(c.intro)}</p><a class="button client-button" href="#entwurf">Euren Mailing-Entwurf ansehen <span>↓</span></a><p class="proposal-label">Ein Kampagnenvorschlag von Kontaktstoff · Noch kein beauftragtes Projekt</p><div class="client-promise-strip"><span><b>01</b> Passende ${esc(c.audienceLabel||'Agenturen')}</span><span><b>02</b> Persönliche Nachricht</span><span><b>03</b> ${esc(c.nextLabel||'Direkter Gesprächstermin')}</span></div></section>
<section class="client-container client-design" id="entwurf"><div class="client-section-heading"><div><div class="client-eyebrow">EUER AUFTRITT. ZUM ANFASSEN.</div><h2>${esc(c.concept)}</h2></div><p>${esc(c.designDescription||'Vorne eine Frage, die hängen bleibt. Hinten eine Nachricht, die zur Agentur passt.')}</p></div>
<div class="client-audience-picker" role="group" aria-label="Beispiel-Zielgruppe">${people.map((p,i)=>`<button data-client-person="${i}" aria-pressed="${i===0}"><strong>${esc(p.segment)}</strong><span>${esc(p.first_name)} · ${esc(p.company)}</span></button>`).join('')}</div><div class="client-preview-shell"><div class="client-preview-top"><span>DIN A5 · Vorder- & Rückseite</span><div class="view-switch" role="group" aria-label="Darstellung"><button data-view="3d" aria-pressed="true">In 3D</button><button data-view="flat" aria-pressed="false">Beide Seiten</button></div></div>
<div id="client-stage" class="hero-stage" tabindex="0" role="group" aria-label="Mailing drehen: ziehen oder Pfeiltasten nutzen." aria-busy="true"><div class="hero-shadow"></div><div id="client-card" class="hero-card"><div class="card-face card-front"><canvas id="client-front" aria-label="Vorderseite des Mailing-Entwurfs"></canvas></div><div class="card-face card-back"><canvas id="client-back" aria-label="Rückseite des Mailing-Entwurfs"></canvas></div></div><span class="table-note">210 × 148 mm · Designvorschlag</span></div>
<div id="client-flat" class="client-flat" hidden><figure><canvas id="flat-front" aria-label="Vorderseite flach"></canvas><figcaption>01 / Vorderseite</figcaption></figure><figure><canvas id="flat-back" aria-label="Rückseite flach"></canvas><figcaption>02 / Rückseite</figcaption></figure></div>
<div class="client-preview-controls"><span>Mit der Maus oder dem Finger drehen</span><button id="client-flip">Rückseite ansehen ↻</button><button id="client-reset" aria-label="Ansicht zurücksetzen">↺</button></div>
<details class="client-customize"><summary>Nachricht selbst anpassen</summary><div class="client-personalize"><div><h3>Dein Kontakt. Deine Nachricht.</h3><p>Die Änderungen erscheinen direkt auf der Karte.</p></div><label>Vorname<input id="client-name" value="${esc(people[0].first_name)}" maxlength="35" autocomplete="off"></label><label>Unternehmen<input id="client-company" value="${esc(people[0].company)}" maxlength="65" autocomplete="off"></label></div><label class="client-personal-note">Anrede<input id="client-salutation" value="${esc(people[0].salutation)}" maxlength="100"></label><label class="client-personal-note">Der persönliche Gesprächsanlass<textarea id="client-note" rows="3" maxlength="350"></textarea><small>Die Beispielunternehmen sind erfunden. Für echte Empfänger stimmen wir den Anlass anhand eurer Kontaktliste ab.</small></label></details>
<div class="client-preview-foot"><label class="placeholder-toggle"><input id="client-placeholders" type="checkbox"> Platzhalter zeigen</label><span id="client-status" role="status">Vorschau wird geladen …</span><button id="client-pdf" class="text-link">Entwurf als PDF ↓</button></div><p id="client-error" role="alert" hidden></p></div>
<p class="client-design-note">${esc(c.note||'Fiktiver Beispielkontakt. Der QR-Code öffnet eure echte Terminseite mit Beispiel-Kampagnenparametern.')} <a href="${esc(c.target)}" target="_blank" rel="noopener noreferrer">Zielseite ansehen ↗</a> · <a id="client-studio" href="/studio/?client=${c.id}">Diesen Entwurf im Studio weiterbearbeiten ↗</a></p>
</section>
<section class="client-container client-reason"><div><div class="client-eyebrow">WARUM DAS ZU EUCH PASST</div><h2>Eure Ansprache.<br>Ein weiterer Weg<br>zu euren Wunschkunden.</h2><p>${esc(c.rationale)}</p><a class="source-link" href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">Grundlage: euer aktueller Webauftritt ↗</a></div><ol><li><span>01</span><div><h3>Bei den passenden Menschen landen.</h3><p>Gemeinsam wählen wir die Zielgruppe aus: ${esc(c.audience)}. Qualität und Relevanz stehen vor einer großen Versandmenge.</p></div></li><li><span>02</span><div><h3>Schon auf der Karte persönlich werden.</h3><p>Name, Unternehmen und der passende Akquise-Anlass gehören in die Nachricht. Für jeden Kontakt formulieren wir einen nachvollziehbaren Grund für das Gespräch.</p></div></li><li><span>03</span><div><h3>Den nächsten Schritt einfach machen.</h3><p>${esc(c.digitalStep||'Ein Scan führt zu eurer Terminseite. Es braucht für den Pilot kein neues Buchungssystem. Kampagnenparameter helfen bei der Zuordnung in eurer Webanalyse.')}</p></div></li></ol></section>
<section class="client-pilot" id="pilot"><div class="client-container"><div class="client-section-heading"><div><div class="client-eyebrow">UNSER VORSCHLAG FÜR DEN START</div><h2>${c.pilot} passende Kontakte.<br>Ein klarer erster Test.</h2></div><p>Ein überschaubarer Pilot mit ${c.pilot} ausgewählten Kontakten. Danach entscheiden echte Rückmeldungen über den nächsten Versand.</p></div><div class="pilot-facts"><div><strong>${c.pilot}</strong><span>persönliche Mailings</span></div><div><strong>2</strong><span>gestaltete Seiten pro Karte</span></div><div><strong>1</strong><span>klares Ziel: ${esc(c.goalLabel||'ein Strategiegespräch')}</span></div></div><div class="client-test-plan"><article><span>VOR DEM VERSAND</span><h3>Gemeinsam auswählen.</h3><p>${esc(c.pilotDescription||'Agenturtyp, Ansprechpartner und Anlass prüfen. Dann die persönliche Nachricht und die zwei Kartenseiten freigeben.')}</p></article><article><span>NACH DEM VERSAND</span><h3>Gespräche statt Bauchgefühl.</h3><p>${esc(c.resultsDescription||'Terminbuchungen und qualifizierte Gespräche zur Kampagne erfassen. Tracking und Zuordnung richten wir vorher mit euch ein.')}</p></article></div><div class="pilot-scope"><div><h3>Das Kampagnenpaket</h3><p>Konzept & Texte · Design beider Seiten · Personalisierung aus eurer Kontaktliste · QR-Verknüpfung · Vorschau & finale Abstimmung.</p></div><div><h3>Gemeinsam abstimmen</h3><p>Zielgruppe, Adressliste, Auflage, Papier, Druck und Versand. Ihr bekommt vor einer Beauftragung ein Angebot mit den vereinbarten Leistungen und Kosten.</p></div></div><p class="pilot-note">Vorgeschlagener Umfang, keine Ergebnisgarantie. Die Erfolgsmessung wird vor dem Versand mit eurer Website und den gewählten Zielaktionen abgestimmt.</p></div></section>
<section class="client-container client-next" id="anfrage"><div><div class="client-eyebrow">DER NÄCHSTE SCHRITT</div><h2>Lust, daraus eure<br>erste Kampagne<br>zu machen?</h2><p>Wählt die Zielgruppe und die Auflage für euren Pilot. Der Kampagnenbrief hält euren ausgewählten Entwurf und die nächsten Entscheidungen fest.</p><p class="client-next-note">Designvorschlag von Kontaktstoff für ${esc(c.name)}. Namen und Marke werden hier nur zur Veranschaulichung eurer möglichen Kampagne verwendet.</p></div><form id="client-request"><label>Wen wollt ihr erreichen?<select name="audience">${(c.audienceOptions||['Webdesign-Agenturen','KI- & Automationsagenturen','Content- & Kreativagenturen','Gemischte Agenturliste']).map(label=>`<option>${esc(label)}</option>`).join('')}</select></label><label>Gewünschte Auflage<select name="quantity"><option value="250">250 Karten · Pilotvorschlag</option><option value="500">500 Karten</option><option value="1000">1.000 Karten</option></select></label><label>Euer Name<input name="name" autocomplete="name" placeholder="Wer ist unser Ansprechpartner?" maxlength="100"></label><label>Was ist euch wichtig?<textarea name="notes" rows="3" maxlength="2000" placeholder="Zum Beispiel: Zielgruppe, Termin, Anpassung am Design …"></textarea></label><button class="button client-button" type="submit">Kampagne anfragen ↗</button><p id="request-hint">Prüfe deinen Entwurf im Kundenbereich. Zum Anfragen legst du dein Unternehmenskonto an; es wird noch nichts bestellt.</p><div id="request-result" role="status" hidden></div></form></section>
</main><footer class="client-footer client-container"><a class="wordmark" href="/">kontaktstoff<span>.</span></a><p>Persönlich kommt weiter.</p><a href="/fuer/">Alle Kundenkonzepte ↗</a></footer><script type="module" src="/clients/app.js"></script></body></html>`;
  await mkdir(`fuer/${c.id}`,{recursive:true});await writeFile(`fuer/${c.id}/index.html`,html);
 }
 await writeFile('fuer/index.html',`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Kundenkonzepte · Kontaktstoff</title><link rel="stylesheet" href="/clients/base.css"><link rel="stylesheet" href="/clients/style.css"></head><body class="client-directory"><header class="client-container"><a class="wordmark" href="/">kontaktstoff<span>.</span></a></header><main class="client-container"><p class="eyebrow">PERSÖNLICHE KAMPAGNENVORSCHLÄGE</p><h1>Eine Idee für<br>euer Unternehmen.</h1><p>Eigene Designs. Passende Zielgruppen. Ein konkreter Vorschlag für den ersten Versand.</p><div class="client-directory-grid">${CLIENT_PAGES.map(c=>`<a href="/fuer/${c.id}/"><span>01 / KAMPAGNENKONZEPT</span><h2>${esc(c.name)}</h2><p>${esc(c.concept)}</p><b>Konzept & Mailing ansehen ↗</b></a>`).join('')}</div></main></body></html>`);
}
